### ISSUE TITLE
Can't send an activation mail to gmail

### ISSUE THREAD

**Issue by MaxShvets** [rainlab/user-plugin#100]
So, I have an activation mode set to user and while I'm able to send activation email to yandex email, I'm unable to do the same for the gmail one. As it says in backend section, mail is successfully sent, though It doesn't appear in my inbox. I'm using a php mail method. Any help would be appreciated.

**Comment by chrisvidal** [comment]
same issue here with the following errors :
"Connection to tcp://smtp.gmail.com:465 Timed Out" on line 404 of Sites/prototypes/octobercms/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php

**Comment by LukeTowers** [comment]
Are you guys trying to send emails via Gmail SMTP to your own email address?
Also, closing as it has been over a month since any activity on this occurred.
