### ISSUE TITLE
Plugin:refresh There is no column with name 'username' on table 'users'.

### ISSUE THREAD

**Issue by flyingbaba** [rainlab/user-plugin#105]
After making some changes I tried to execute: 

```
php artisan plugin:refresh RainLab.User
```

But it is throwing an error: 

```
[Doctrine\DBAL\Schema\SchemaException]
There is no column with name 'username' on table 'users'.
```

Of course I have username column inside the users table.

Things I tried already: Move column username to the create_users_table.php, modifying version.yaml. I even tried to leave only the creation of users table without it's dependencies. 
Please help ))

**Comment by daftspunk** [comment]
Now that we have a stable release this should be fixed. If this is still occurring please log another issue.
