### ISSUE TITLE
using the method hasRole in backend

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/user-plugin#108]
Im not sure how to use the hasRole method for the backend.
basically, i just need to know if the current logged backend use has a role or not, so im trying to use this method like this : 
Group::hasRole('Staff', BackendAuth::getUser() )
But then an exception is raised on this following line :
$userRoles = json_decode(User::find( $user == null ? $account->user()->id : $user)->groups);
which i found a bit weird, why do we search a user if we already passed the user into the argument ?
User::find($user) does not work and raise the exception apparently
to fix this i changed the code to 
$userRoles = json_decode(User::find( $user == null ? $account->user()->id : $user->id)->groups);

**Comment by daftspunk** [comment]
Where did you find the `hasRole` method?

**Comment by chrisvidal** [comment]
it is coming from the User Front End Permission plugin in this model class
use ShahiemSeymor\Roles\Models\Group;

**Comment by chrisvidal** [comment]
not related to the user plugin indeed, sorry about that.
will post under the right support plugin forum
