### ISSUE TITLE
Add surname column to users table

### ISSUE THREAD

**Issue by Flynsarmy** [rainlab/user-plugin#11]
It's not very forward thinking to have a `name` column over `first_name, last_name` with a dynamically generated `name` column. A lot of sites like having a *Hello, first!* message in the header. I can see it becoming a common complaint from clients.

**Comment by firemankurt** [comment]
Since this has not changed I added a similar change as a fork.
I really require separate First,Last Names.

**Comment by Flynsarmy** [comment]
...or you could send a PR?

**Comment by Flynsarmy** [comment]
Added in https://github.com/rainlab/user-plugin/commit/126399ba3bb4148c9ece7cdd20df04959a476ae8
