### ISSUE TITLE
No login and no registration

### ISSUE THREAD

**Issue by Salmonrules** [rainlab/user-plugin#121]
Hi there,
I am trying to use this plugin in OctoberCMS. Installation goes fine, but when I am goin to try to login or register the post values will be shown in my address bar of my browser, but no actions.

OctoberCMS build: 303.
User Plugin version: 1.1.2

Thanks for the help

**Comment by daftspunk** [comment]
Can you confirm that you have jQuery and the `{% framework extras %}` tag located somewhere in your layout?

**Comment by Salmonrules** [comment]
Thank you for this comment. I forgot to include these in my layout...

**Comment by logicalguy** [comment]
Hi, I am having the same issue.  I have OctoberCMS build 309 and User Plugin version 1.1.2.  OnRegister and OnSignin methods are not being called (I have dd() statements in them to check).  OnRun is being called, though.  Where are the instructions about the jQuery and {% framework extras %} located?  I've not found any such in the documentation.

**Comment by janvandelaar** [comment]
Did you manage to get it working?

**Comment by daftspunk** [comment]
Make sure you don't include the component in a partial, it has known limitations.

**Comment by logicalguy** [comment]
Yes, it was working all the while.  dd statements don't work for ajax functions, I found out.
