### ISSUE TITLE
Error Messages still in extra Window / Flash

### ISSUE THREAD

**Issue by MichaelReich** [rainlab/user-plugin#126]
I tried to integrate that line:

```
{% flash %}
    <div class="alert alert-{{ type == 'error' ? 'danger' : type }}">{{ message }}</div>
{% endflash %}
```

That the errors show up there, but it wont work. When I enter false content it appears like normal in the extra window.

Watch the Error coming here twice: http://test.reich-michael.com/account

I build up the page like this:

```
<div class="row">
    <div class="col-md-12">
        {% flash %}
            <div class="alert alert-{{ type == 'error' ? 'danger' : type }}">{{ message }}</div>
        {% endflash %}
    </div>
</div>

{% if not user %}

    <div class="row">
        <div class="col-md-6">
            <h3>Einloggen</h3>
            <form
                    data-request="onSignin">
                    <div class="form-group">
                        <label for="userSigninLogin">{{ loginAttributeLabel }}</label>
                        <input
                            name="login"
                            type="text"
                            class="form-control"
                            id="userSigninLogin" />
                    </div>

                    <div class="form-group">
                        <label for="userSigninPassword">Passwort</label>
                        <input
                            name="password"
                            type="password"
                            class="form-control"
                            id="userSigninPassword" />
                    </div>

                    <button type="submit" class="btn btn-default">Einloggen</button>
                </form>
        </div>

        <div class="col-md-6">
            <h3>Registrieren</h3>
                <form
                    data-request="onRegister">
                    <div class="form-group">
                        <label for="registerName">Name</label>
                        <input
                            name="name"
                            type="text"
                            class="form-control"
                            id="registerName" />
                    </div>

                    <div class="form-group">
                        <label for="registerEmail">E-Mail</label>
                        <input
                            name="email"
                            type="email"
                            class="form-control"
                            id="registerEmail" />
                    </div>

                    <div class="form-group">
                        <label for="registerPassword">Passwort</label>
                        <input
                            name="password"
                            type="password"
                            class="form-control"
                            id="registerPassword" />
                    </div>

                    <button type="submit" class="btn btn-default">Registrieren</button>
                </form>
        </div>

    </div>

{% else %}

    {% partial account ~ '::activation_check' %}

    {% partial account ~ '::update' %}

{% endif %}
```

**Comment by chrisiek** [comment]
- I also get the same alert-error message twice when I try to activate already active account. I get two messages

`User is already active! 
User is already active! `

When I used this code:

`{% flash %}
 {{ message }} <br>
 {% endflash %}`

it appears that message is put twice in Flash session then rendered twice on page.

- The second case is this: I click the activation link in the activation email like this:

`http://myproject.dev/account/5031!5ZcC6Ug75GBfkSh0Uhrb9GsrV4rV2LAwEuTmjyNOVk`

and I get two separate messages in Flash. I am not sure which came first.:

`Successfully activated your account. 
User is already active!`

English is not my native language but I am 100% sure that is incorrect.

**Comment by pat-och** [comment]
have similar issue here.
I use user plugin very basically with swal to display flash message.

When i click on the link in the activation email. I got `User is already active!` message instead of expected `Successfully activated your account` message

this is very disturbing for users

using debugbar, I could see that onRun method account is executed twice. first time is good since the account is activated but the second time procces failed into `User is already active!`  message and only this one appears for user.

this could be an issue cause by swal combined usage or intrinsic issue from user plugin ?

how to fixed it please ?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
