### ISSUE TITLE
Page Restriction by Group

### ISSUE THREAD

**Issue by michaelcooke** [rainlab/user-plugin#127]
Is there a way to implement page restriction by group rather by merely users/guests?

If not, consider this a feature request.

**Comment by adrenth** [comment]
This functionality would be very welcome.

**Comment by that0n3guy** [comment]
+1   It would also be nice to redirect based on groups (for all you know whats what you mean).

**Comment by cr2a-graphique** [comment]
i make this to use user group : 
- first create user group.
- use, user group ```id``` for next step (id=2 in this example)
- In your layout you can do this condition :
```
{% if user.groups.0.id == 2 %}
     <p>Hello {{ user.name }}</p>
{% else %}
     <p>Nobody is logged in</p>
{% endif %}
```
 
Enjoy

**Comment by CitrinoDeveloping** [comment]
Hi,
thanks for this snippet of code. The next step could be a redirect on else condition.
I try to use the redirect function of the account component but can't work. I created a partial accessGroup insert this code and then create a function for redirect.

```
{% if user.groups.0.id == 1 %}
      <p>Hello {{ user.name }}</p>
{% else %}
      {{ urlredir }}
{% endif %}
```
```
function onRun()
    {
        $redirectUrl ['urlredir'] = $this->controller->pageUrl($this->property('redirect'));
        $allowedGroup = $this->property('security', self::anteprima);
        $isAuthenticated = Auth::check();
        if (!$isAuthenticated && $allowedGroup == self::ALLOW_USER) {
            return Redirect::guest($redirectUrl);
        }
        elseif ($isAuthenticated && $allowedGroup == self::ALLOW_GUEST) {
            return Redirect::guest($redirectUrl);
        }
        $this->page['user'] = $this->user();
    }
```

Have you some ideas? 
The better thing, could be insert a param group in the session component inspector, we can work on it.
Cit.

**Comment by daftspunk** [comment]
For sure it is possible to implement this by using the code, or even your own component. It would be so much nicer to make this functionality native, we can do it now that we have [the Inspector 2.0 features](http://octobercms.com/docs/ui/inspector).

- Add a new property called `groups` to the `Session` component
- Displayed as a checkbox list  (called `set` -- see below) showing a list of available groups
- That allows selection of groups who can view the page.
- The set `items` would be a list of group **codes** (not IDs for happy humans)
- The `default` would be null
- When the value is null, no security redirect is applied
- When the value contains group codes, check if the user belongs to that group
- If user does not belong to said group, redirect away (same as security redirect logic)

Inspector 2.0 `set` type:

```
{
    "property": "context",
    "title": "Context",
    "type": "set",
    "items": {
        "create": "Create",
        "update": "Update",
        "preview": "Preview"
    },
    "default": ["create", "update"]
}
```

Someone feel free to implement this as a Pull Request, it is a great idea we would love to see.

:v: & :heart:

**Comment by jBOKA** [comment]
PR https://github.com/rainlab/user-plugin/pull/230

Is there also a way to hide the groupsAllowed inspector option if ALL or GUEST is selected and only show it if security is set to USER?

If so, I'll add it...

**Comment by Cleanse** [comment]
Can we get this merged?

**Comment by LukeTowers** [comment]
If somebody can come with a solution to @jBOKA's suggestion, then yes

**Comment by Cleanse** [comment]
Can you point me to where this logic is in the api?

> **depends**	an array of property names a dropdown property depends on. See the dropdown properties below.

**Comment by jBOKA** [comment]
Backend UI Inspector

**Comment by LukeTowers** [comment]
Another approach you could look at doing is only defining the userGroups property if the groupsAllowed property is `user`

**Comment by LukeTowers** [comment]
#230 has been merged, closing this
