### ISSUE TITLE
Can we combine frontend User and Backend Users in this plugin?

### ISSUE THREAD

**Issue by ichakesachin30** [rainlab/user-plugin#133]
Hi..
I think this question could be not valid but i have requirement like this.

User plugin is generally built for front end user management, but i want to do it like:
suppose i added new user and select checkbox as admin user then this user should work as backend user.

Please suggest me, how to proceed?

**Comment by Twiebie** [comment]
I'm wondering the same thing. Any news on this?

**Comment by nedpals** [comment]
I think they will not do this for the sake of security. But I think connecting a backend user to a frontend user instead will be a better idea for this.

**Comment by matheusrrocha** [comment]
I need the same feature in my own project. This will be kind of useful.

**Comment by daftspunk** [comment]
This is not a feature we plan to add to this plugin for security reasons. It is possible to develop a plugin to do this by hooking the afterSave event on the user model and [extending the user plugin](https://vimeo.com/108040919) to add a checkbox. After a RainLab.User is saved, it can be syncronised to the Backend User model.
