### ISSUE TITLE
Redirection Issues?

### ISSUE THREAD

**Issue by Asinox** [rainlab/user-plugin#134]
Hi there, i'm don't know if i'm wrong or if this behavior is just weird to me.

There is a settings to be complete with the plugin (Account component), and this settings is the "Redirect to",  but the plugin is ignoring the "redirection" settings, instead the plugin is always redirecting  to a previous page.

This is the normal behavior? 

There is a way to "fix" this?
Thank you

**Comment by daftspunk** [comment]
This is normal behavior only when the user has hit a page that requires authentication. Otherwise the normal redirect is used.
