### ISSUE TITLE
Problem with max length in restore password

### ISSUE THREAD

**Issue by jbartoszek** [rainlab/user-plugin#139]
Hi everybody,

I found a bug with register and restore password. 
In ResetPassword.php file you have a rules on email for validation -  max 32 chars.
Please tell me why? In onRegister trigger you do not have a the rule. I registered new account with 
e-mail(33 chars) and i can not reset my password.

I hope that you will solve the problem quickly
Jacek Bartoszek

**Comment by daftspunk** [comment]
Fixed by #120
