### ISSUE TITLE
Logout Redirection shows popup when logout from wrong URL?

### ISSUE THREAD

**Issue by ichakesachin30** [rainlab/user-plugin#140]
Suppose user entered wrong URL while navigation in website, then suddenly click on logout button,
It logout but redirection not happen properly.
Getting Popup with Base URL.

Please suggest the appraoch?

**Comment by ichakesachin30** [comment]
Thanks for update.

**Comment by LukeTowers** [comment]
@ichakesachin30 Does this problem still exist for you?

**Comment by ichakesachin30** [comment]
I have not checked yet.

Regards,
Sachin Ichake.
