### ISSUE TITLE
Implement workflow for lost activation email

### ISSUE THREAD

**Issue by kdon80** [rainlab/user-plugin#141]
How does resend activation code supposed to work? I look at the code and doesn't seem to be right!
In the code, if the user clicks on 'resend activation code', it checks if user is logged in, it would then pass the 'user' object to the sendEmail method. But the problem is user can never log in if user is not activated! So how is the user ever supposed to request activation code to be resent to the user?

**Comment by daftspunk** [comment]
#### Activation

Activation is a process of vetting a user who joins the site. By default, users are activated automatically when they register and an activated account is required to sign in.

The **Activation mode** specifies the activation workflow:

- **Automatic**: This mode will automatically activate a user when they first register. This is the same as disabling activation entirely and is the default setting.
- **User**: The user can activate their account by responding to a confirmation message sent to their nominated email address.
- **Administrator**: The user can only be activated by an administrator via the back-end area.

You can allow users to sign in without activating by switching **Sign in requires activation** to the OFF setting. This is useful for minimising friction when registering, however with this approach it is often a good idea to disable any "identity sensitive" features until the user has been activated, such as posting content. Alternatively, you could implement a grace period that deletes users (with sufficient warning!) who have not activated within a given period of time.

**Comment by kdon80** [comment]
Thanks for the response but I'm talking about "re-sending activation code" not the activation code per se. As in, the user never received the activation code, or his activation code was deleted and the user needs a new activation code.

**Comment by daftspunk** [comment]
Added to the docs:

Users have the ability to resent the activation email by clicking **Send the verification email again** found in the Account component.

Thanks!

**Comment by daftspunk** [comment]
Do you mean: If a user signs up with an email and doesn't receive the confirmation email? How do they activate? It is a rare event, they should contact the site administrator to be activated manually from the backend. We don't have a workflow implemented to self-serve this scenario.

**Comment by kdon80** [comment]
Yes, precisely. Thanks

**Comment by kdon80** [comment]
Instead of creating new forms, one simple and neat solution would be to tie this functionality to the "login" function. If user who hasn't activated the account, and tries to login, it will automatically resend the activation code to the user.
Currently, when such users try to login, they get an error saying they are not activated (from Auth/Manager.php)

    public function login($user, $remember = true)
    {
        if ($this->requireActivation && !$user->is_activated) {
            $login = $user->getLogin();
            throw new AuthException(sprintf('Cannot login user "%s" as they are not activated.', $login));
        }


So if you resend the activation code here, you can then add to the error message saying the activation has been resent.

**Comment by daftspunk** [comment]
We should find a case study to find how other sites handle this.

**Comment by TechInterMezzo** [comment]
Maybe I'm missing something for the current implementation, but I've got the following problem:
You can't login with an account that is not activated. (As mentioned above it throws an AuthException.)
To be able to resend the activation mail, the method/event "onSendActivationEmail" requires you to be logged in.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by ImadUllah** [comment]
When you create user from back-end then it requires activation, even if I choose Automatic activation? 
![Capture](https://user-images.githubusercontent.com/35524866/54196839-32619900-44e4-11e9-8a9b-a2f5b9191611.PNG)
![Capture1](https://user-images.githubusercontent.com/35524866/54196843-368db680-44e4-11e9-86eb-0b606141602c.PNG)

,

**Comment by w20k** [comment]
@ImadUllah if it's a bug please create another issue.
