### ISSUE TITLE
Can't Login a User

### ISSUE THREAD

**Issue by pratyushpundir** [rainlab/user-plugin#148]
I'm not exactly sure what's happening but it seems that the check() method is being called on my model instead of the Auth class because every time to login a user I get this error:

"Call to undefined method October\Rain\Database\QueryBuilder::check()"

Any pointers would be very helpful.

**Comment by pratyushpundir** [comment]
SOLVED: As most of the times with such issues. This was a typo at my end. Darn autocorrect!!

**Comment by daftspunk** [comment]
:+1:
