### ISSUE TITLE
AJAX Handler onLogout() not found

### ISSUE THREAD

**Issue by nedpals** [rainlab/user-plugin#149]
Like the title says, the onLogout() does not working and displays a message that the ajax handler was not found. I followed what is said on the documentation but still doesn't work.

Is there any solid solution or temporary fix for this? Thanks in advance.

**Comment by nedpals** [comment]
up

**Comment by daftspunk** [comment]
Can you provide more information, what does your layout / page structure look like? 

Are you including `[session]` inside a partial? If so, AJAX handlers will not work here, try adding to the layout instead.

**Comment by nedpals** [comment]
Nevermind I forgot to put `[session]` into my layout and it is now working.
