### ISSUE TITLE
Problem editing User in 1.2.2

### ISSUE THREAD

**Issue by Eoler** [rainlab/user-plugin#150]
Exception:
**Call to a member function diffForHumans() on null**
in
`<path>/plugins/rainlab/user/controllers/users/_preview_scoreboard.htm on line 13`

**Comment by daftspunk** [comment]
Thanks for reporting

Perform a "Force update" to get the fix

**Comment by Eoler** [comment]
Useful user preview, thanks.
Am I only one that gets: 
`Call to undefined method October\Rain\Database\QueryBuilder::getLocalRootPath()`
on avatar upload (after forcing full CMS update)?

**Comment by daftspunk** [comment]
Would need to see the full stack trace in storage/logs/system.log to see why that is happening. I can't seem to get it to happen on my end.

**Comment by Eoler** [comment]
Avatar image upload error was from responsive images plugin, case closed.
