### ISSUE TITLE
SQL integrity

### ISSUE THREAD

**Issue by MarvinDurot** [rainlab/user-plugin#151]
Hello,

First, I find your work wonderful and useful for my projects!

But I don't understand why you don't use foreign keys in your tables: records might be wrong later. Imagine you have a user attached to a user group and you delete it. Currently, the association table "users_groups" will keep the deleted record and it will cause bugs.

Yours sincerly,
Marvin.

**Comment by daftspunk** [comment]
Without going in to too much detail, this will be [fixed in the next major version](https://github.com/octobercms/library/commit/2d29cbc42e7a29d3312493b0b741f92b433606aa).
