### ISSUE TITLE
Register and Login page

### ISSUE THREAD

**Issue by dehboris** [rainlab/user-plugin#158]
Hi,
Thanks for this plugin. It's amazing.
But I did't find the registration page and user authentication.
You can help me please.
Thanks you.

**Comment by nedpals** [comment]
Hi! You must be the one create the login and registration pages in order for it to work. Further details can be read from the README.md file in this repo or the plugin page ( https://octobercms.com/plugin/rainlab-user).

**Comment by dehboris** [comment]
Ok, Thanks you

**Comment by nedpals** [comment]
Please close the issue if you have resolved it. Thanks
