### ISSUE TITLE
Three Email problem when using "Forgot Password"

### ISSUE THREAD

**Issue by nhuzaa** [rainlab/user-plugin#160]
Whenever I try to reset the password, three emails are sent. Only the recent email will have the valid token for resetting the password.

**Comment by daftspunk** [comment]
Please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by nhuzaa** [comment]
I had added the three references for the Ajax Framework. I removed the extras now its working fine. 
Thank you Anyways.
