### ISSUE TITLE
Error when using with Relation Manager

### ISSUE THREAD

**Issue by mbaxter91288** [rainlab/user-plugin#164]
Hi,

I'm trying to create an order which `belongsTo` a `Rainlab\User\Models\User`. I've extended the `User` model to include `hasMany -> Orders`.

Using the `partial` form type with the `<?= $this->relationRender('user') ?>` code within the `_users.htm` file renders the relation manager in my forms. Creating a new user works fine, but selecting and linking an existing user causes an error. When clicking the `Link User` button the popup appears with the full list of Users, then when selecting a User I get the following error:

```
Invalid argument supplied for foreach()" on line 557 of /home/vagrant/Sites/laravel/jps/vendor/october/rain/src/Auth/Models/User.php
```

Not sure what's going on but can anyone help please?

Regards,
Mat

**Comment by LukeTowers** [comment]
@mbaxter91288 Please provide full instructions on how to replicate this using the [test plugin](https://github.com/daftspunk/oc-test-plugin); ideally in the form of a PR to the test plugin so that we can test this.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
