### ISSUE TITLE
[Question] What about flexibility for "afterAuthenticate" ?

### ISSUE THREAD

**Issue by mahony0** [rainlab/user-plugin#167]
Idk if any other logical way but I need this flexibility. I want to Redirect user dynamically to "before page" by url param (i.e: /login/user-panel) should redirect back to "user-panel" page after successful log-in

[Account.php#L135](https://github.com/rainlab/user-plugin/blob/master/components/Account.php#L135)

already has beforeAuthenticate, should we repeat similar event for L138 (or before Redirect::intended)?

I didn't send PR for maybe already has same logic in other way but i don't know how..

**Comment by daftspunk** [comment]
There are a few ways to handle this. You should use a custom AJAX handler that calls the account handler.

```
function onCustomSignIn()
{
    $this->account->onSignin();
    return Redirect::to('user-panel');
}
```

You could pass it via the URL:
http://.../login?redirect=user-panel

You could pass it via a hidden input in the form:
```
<input type="hidden" name="redirect" value="{{ 'user-panel'|page }}" />
```

**Comment by mahony0** [comment]
custom ajax handler method is what I'm looking for. I also customized register handler, thanks..
