### ISSUE TITLE
How to delete users?  They are just disabled...

### ISSUE THREAD

**Issue by that0n3guy** [rainlab/user-plugin#170]
This seems like a security bug sorta.   If I "delete" a user in the backend, they are soft deleted (which is normal laravel behavior)... but this means they are just de-activated.  

But that user can just re-activate there account by re-logging in.  To me "delete" and "deactive" should be different things.   Or maybe user deactivated vs admin deactivated should be different things.

Am I missing something?  How do I hard delete someone?

**Comment by daftspunk** [comment]
This is addressed in the latest version. It is released as an edge update.
