### ISSUE TITLE
How to override url.intended at onRegister?

### ISSUE THREAD

**Issue by leocavalcante** [rainlab/user-plugin#172]
Tried `redirect` property of Account component, tried a hidden `<input>` named `redirect`...
Nothing makes the form of `onRegister` redirects to somewhere different from the previously intended URL.
This seams so basic, obviously I'm doing something wrong. Any help?

**Comment by daftspunk** [comment]
Hidden input with `redirect` should work, as directed by this code

            if ($redirectUrl = post('redirect', $redirectUrl)) {
                return Redirect::intended($redirectUrl);
            }

Note it uses `Redirect::intended` that will override any value if preceded by `Redirect::guest`, this would be the only reason I can think of why the hidden input would be ignored, since it comes in at 2nd place in the priority chain.

**Comment by leocavalcante** [comment]
Thanks, and yes, this is probably what is [happen](https://github.com/rainlab/user-plugin/blob/master/components/Session.php#L64).

When user clicks on my `/foo` page I have a `[session]` there redirecting non-users to `/bar` and at `/bar` I display both *sign in* and *register* forms. But I want that when someone registers it redirects to `/baz` that have a nice message to wait for admin activation.

**Comment by daftspunk** [comment]
Override it with a custom AJAX handler
```
function onMyRegister()
{
    $this->account->onRegister();
    return Redirect::to($this->pageUrl('nicepage'));
}
```

**Comment by leocavalcante** [comment]
Awesome. Did work. Thanks.
