### ISSUE TITLE
Accessing the {{user}} variable in PHP section

### ISSUE THREAD

**Issue by munikarmanish** [rainlab/user-plugin#179]
Is there a way to access the {{**user**}} variable in **PHP section**?

I've tried **$this**['_user_'] and **$user**. None worked.

**Comment by daftspunk** [comment]
It comes from the `[session]` component? So it would be `$this->session->user`

**Comment by munikarmanish** [comment]
Nope. `$this->session->user` doesn't seem to work either.
It throws an exception __Trying to get property of non-object__.

**Comment by daftspunk** [comment]
Sounds like you are calling it too early. Please study the execution life cycle for more details:
http://octobercms.com/docs/cms/layouts#layout-life-cycle

**Comment by munikarmanish** [comment]
The [Pages](http://octobercms.com/docs/cms/pages#page-life-cycle) documentation reads:
> The `onEnd()` function is executed before the page is rendered and after the page components are executed. In the `onStart` and `onEnd` functions you can inject variables to the Twig environment.

The `Session` component reads:
```
public function onRun() {
       . . .
       $this->page['user'] = $this->user();
}
```

My page's code:
```
function onEnd() {
    $name1 = $this->session->user->name;
    $name2 = $this->page['user']->user->name;
}
```

Still the same error! :/

**Comment by daftspunk** [comment]
It is hard to debug without seeing the full picture. I just tested this code and it works

```
[session]
==
function onEnd() {
    if ($user = $this['user']) {
        return 'Hi there, ' . $user->name;
    }
}
==
```

**Comment by munikarmanish** [comment]
Weird, I had tried that as well. Anyway, it works now. Thanks! :+1: 

Anyway, can you please look at this forum topic: https://octobercms.com/forum/post/how-to-generate-a-profile-for-an-existing-user-when-logging-in
