### ISSUE TITLE
Auth::getUser()->id return null

### ISSUE THREAD

**Issue by timmarner** [rainlab/user-plugin#180]
Hi,

Im using the 'Plan' plugin which requires the Rainlab 'User' plug and also the 'Roles' plugin. Ive tried asking on the support page of the 'Plan' plugin but got no response.

However ive noticed that if i use Auth::getUser()->id it doesn't return anything. but Auth::getUser()->name does. the user id is there however if i test by echoing Auth::getUser().

Is there any reason why Auth::getUser()->id would not return the users ID.

Any help would be great

**Comment by daftspunk** [comment]
Not sure why this would happen, if it returns name, then it should also return id.

**Comment by timmarner** [comment]
I Know. I have the Plans, Roles & User plugin installed. ive even tried this.

    $user_array = $user->toArray();
$user_id = $user_array['id'];

But i still can't retrieve the 'id'. Even though the array contains the 'id';

    array(13) { ["id"]=> int(1).....
