### ISSUE TITLE
Form behavior used in RainLab\User\Controllers\Users does not have a model defined.

### ISSUE THREAD

**Issue by michaelchukwu** [rainlab/user-plugin#181]
I keep getting this when ever I try to create a New user from the back end

**Comment by JoniDias** [comment]
Make sure formExtendModel method on RainLab\User\Controllers\Users of your plugin version is returning the model object:

```
public function formExtendModel($model)
    {
        $model->block_mail = MailBlocker::isBlockAll($model);

        $model->bindEvent('model.saveInternal', function() use ($model) {
            unset($model->attributes['block_mail']);
        });

        return $model;
    }
```

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.
