### ISSUE TITLE
Auth::register without sending activation email

### ISSUE THREAD

**Issue by carlosdubus** [rainlab/user-plugin#186]
Hi,

I know you can do Auth::register([], true) to auto activate. Is there any way to do that without sending the activation successful email?

**Comment by WebShapedBiz** [comment]
Can you please share your solution. I would also like not to send any emails.

Cheers.

**Comment by daftspunk** [comment]
`Auth::register([], true)` does not send the activation email. The activation email is sent as part of the `Account` component.
