### ISSUE TITLE
Activation Check Issue

### ISSUE THREAD

**Issue by moshemo** [rainlab/user-plugin#193]
I can't seem to get the activation check to work properly.  Either I get a popup message saying that the user is not authenticated -- although this is NOT the 'Your email address has not yet been verified'.

Or, alternatively, I can get the message to show up -- but then it ALWAYS shows up on the signin page -- even after the user has signed out.

Here is the current version of the code I'm using:

```
title = "Signin"
url = "/account/signin"
layout = "Base"
description = "Sign in page"
is_hidden = 0

[account]
redirect = "account/welcome"
paramCode = "code"
==
{% put class %}account{% endput %}


{% if user %}

    <div class="activation_check">
        {% partial account ~ '::activation_check' %}
    </div>

{% endif %}

{% if not user %}

        <div class="account_form signin_form">
            <h3>Login</h3>
            {% partial account ~ '::signin' %}
        </div>

{% endif %}
```

And I've moved the activation_check to a partial - but it's essentially the same, I just changed the text of the message slightly.

Any idea of what I'm doing wrong?

Thanks.

**Comment by daftspunk** [comment]
Activation requires a code parameter in the URL, it is specified as `paramCode` in the `account` component. Try updating the url to this:

```
url = "/account/signin/:code?"
```

**Comment by SaifurRahmanMohsin** [comment]
Shouldn’t this be a separate component? What if registration is closed but still users need to verify their email through activation? Hmm

**Comment by daftspunk** [comment]
Moved to #97
