### ISSUE TITLE
Create an "Online Users" component

### ISSUE THREAD

**Issue by Shiro-dono** [rainlab/user-plugin#198]
Hello, 
Is there a code for the display of the users that are register or online for the front end part?
Thx

**Comment by daftspunk** [comment]
This should do it

```
\RainLab\User\Models\User::where('last_login', '>', \Carbon\Carbon::now()->subMinutes(5))->get();
```

**Comment by Shiro-dono** [comment]
I am a little new to this, can you show me how the code should look? And is there a possibility that you will integrate this in the future to drag and drop in a page?

**Comment by daftspunk** [comment]
It is possible to make a component for this, yes. That could be nice. We'll leave this open as a feature request.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
