### ISSUE TITLE
Setting to put new registered users into a default User Group

### ISSUE THREAD

**Issue by greggh** [rainlab/user-plugin#199]
This doesnt seem to exist, but would be really helpful. I would like to see a setting that allows me to choose a default user group for new registered users to be added to automatically.

**Comment by daftspunk** [comment]
Makes sense, we recently added a default code called `registered`, perhaps we can use this.

**Comment by jiiis** [comment]
Is this still working? It seems newly created users are not put in the `registered` group.

**Comment by SchneiderDe** [comment]
Unfortunately NO!

I am shocked to see that this problem, newly created users are not registered users, is not a problem of my playing around with Ajax forms but comes from the User plugin.

Why on earth should someone think that it is totally unnecessary to have newly created users belonging to no group? Whats the purpose of User activation then?

In my last 20 years of experience, I take notice of this problem for the first time, especially such an excellent coding of OctoberCMS and an extra-ordinary work of the developers team.

Funny enough is the status declared to this report, which has "Priority: Medium"! 

The developers definitely requires to understand the problems from the side of users in creating a website with OctoberCMS and maintaining it. This should also include an easy entry point to the CMS coding as a starter. Currently, the entry point defined is that of an amateur developer, which should be brought down by offering user friendly  Wizards that helps people to have an easy start.

Without this fundamental function, I cannot even work with this on production site any more! I hope developers have time to offer a solution very soon.

**Comment by abhi1693** [comment]
I tried to this same thing using the way it has been implemented i the backend for the administrators. But it didn't work for me. Is there a way to achieve this?

**Comment by LukeTowers** [comment]
In the meantime until this feature is implemented, hook into the newly added `rainlab.user.register` event to accomplish this yourself.

**Comment by CianHooper** [comment]
is there any update on this? or any guides on how to use `rainlab.user.register`?

**Comment by zhangwen9229** [comment]
+1

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
