### ISSUE TITLE
Account Component, Separate redirect pages for Update, Signin, and Register

### ISSUE THREAD

**Issue by greggh** [rainlab/user-plugin#200]
I want to redirect users who register to a thank you page that tells them to check their email. But I don't want to send people who signed in to that page. Right now it only lets me choose one page to end everyone too.

How can I set separate pages for each of these things?

**Comment by daftspunk** [comment]
You can override the component markup and pass a custom redirect inside each form

```
<input type="hidden" name="redirect" value="{{ 'thankyou'|page }}" />
```

**Comment by daftspunk** [comment]
Alternatively you could override the onRegister handler

```
function onRegister()
{
    $this->account->onRegister();
    return Redirect::to($this->pageUrl('thankyou'));
}
```

**Comment by greggh** [comment]
That worked. Thank you.
