### ISSUE TITLE
How to set different language

### ISSUE THREAD

**Issue by McSuckelaer** [rainlab/user-plugin#201]
Hi, i searched a bit but i couldn't find how to translate the plugin from EN to NL without changing the backend language. I want my backend to stay in English.

**Comment by daftspunk** [comment]
You could change the `app.locale` setting in config/app.php to `nl` then change your backend preferences back to `en`.

**Comment by bekerov** [comment]
this doesn't help. changed 
`'locale' => 'ru',`
but still get errors on `en` locale.

![default](https://user-images.githubusercontent.com/2405629/46576240-cb3c3780-c9cd-11e8-9ce8-a7fd2cffdf72.png)

**Comment by LukeTowers** [comment]
@bekerov how is that related to this issue at all?

**Comment by LukeTowers** [comment]
This is about the backend interface language. Authexceptions aren't translated right now and there are plenty of existing issues discussing why.
