### ISSUE TITLE
Bug in plugin always block propagating of 'mailer.prepareSend' event.

### ISSUE THREAD

**Issue by bashorgru** [rainlab/user-plugin#203]
[Listener](https://github.com/rainlab/user-plugin/blob/bd45629fab0a0981de14a002911facee67544be1/Plugin.php#L42) of 'mailer.prepareSend' event always return boolean, never null. So, other plugins with listeners will **never** get that event after User.Plugin. I assume it's a bug in Rainlab.User.
First, \October\Rain\Mail\Mailer fire event '**mailer.prepareSend**' with halt flag ([code](https://github.com/octobercms/library/blob/762bb0a048d103db4d659d3749a02ea4877ba48f/src/Mail/Mailer.php#L60)).
Next, \Illuminate\Events\Dispatcher as Event start propagating event through listeners, call **that** function setted from \Rainlab\User\Plugin and then stop propagating to the rest of listeners.
Propagating stopped because **that** function returns a **result** (boolean). But it should return **null** to allow processing the rest of listeners ([read comments here](https://github.com/illuminate/events/blob/6b6a6c03cc116fb7033cceadf588cef0a2a5f235/Dispatcher.php#L223-L230)).

**Comment by daftspunk** [comment]
Good write up. This is indeed a bug.
