### ISSUE TITLE
No redirect after login

### ISSUE THREAD

**Issue by patrickvanharen** [rainlab/user-plugin#210]
After posting the login or registration form, the end user redirects to the login interface again.

As example, the user goes to the URL below which displays the login form again.
/account?login=USERNAME&password=PASSWORD

What's going wrong? Just followed the video guide.

**Comment by daftspunk** [comment]
Make sure the layout contains the `{% framework %}` tag to include the AJAX framework. It would appear this is missing from your site. The "RainLab.Vanilla" theme has a working example of this.

https://github.com/rainlab/vanilla-theme
