### ISSUE TITLE
Send email when user was registered

### ISSUE THREAD

**Issue by Asinox** [rainlab/user-plugin#215]
Hi guys!, please i would like to know if there is a way to send an email when the user was registered!

Thanks!

**Comment by daftspunk** [comment]
It is possible of course, in the page code if you override the `onRegister` handler. This is just one way you could do it.

```
function onRegister()
{
    $result = $this->account->onRegister();
    Mail::sendTo(input('email'), 'my-mail-template');
    return $result;
}
```

Another way is to make your own component.

**Comment by Asinox** [comment]
I was trying but nothing but error:

> Call to a member function onRegister()

Any idea?

**Comment by daftspunk** [comment]
This code assumes you have the account component attached to the page, using an alias of `account`. See the documentation for details.

```
title = "my page"
url = "/account"

[account]
==
function onRegister()
{
    $result = $this->account->onRegister();
    Mail::sendTo(input('email'), 'my-mail-template');
    return $result;
}
==
{% component 'account' %}
```
