### ISSUE TITLE
Avoid multiple access

### ISSUE THREAD

**Issue by acurquiola** [rainlab/user-plugin#221]
Hey, guys! 

I need to restrict the concurrent sessions in my app. How i do that?
 I can not allow users to login in different devices in same time. 

Thanks!

**Comment by daftspunk** [comment]
This feature has been implemented. Available in v1.3.3+

> As a security precaution, you may restrict users from having sessions across multiple devices at the same time. Enable the **Prevent concurrent sessions** to use this feature. When a user signs in to their account, it will automatically sign out the user for all other sessions.

**Comment by acurquiola** [comment]
When be disponible this version? The current version is the 1.3.2

Thanks for your help!

**Comment by daftspunk** [comment]
Should be available now: http://octobercms.com/plugin/rainlab-user
