### ISSUE TITLE
Update user's group

### ISSUE THREAD

**Issue by bbrandtlv** [rainlab/user-plugin#224]
Hey,

Didnt find a way to update user's group (to add to a group)

`$user = new User;
$user->group = 'AAA';
$user->save();`

Not working. Please advice?
didnt find it in docs and in the code. 

Thanks

**Comment by daftspunk** [comment]
```
$user = new User;
$user->group = UserGroup::whereCode('AAA')->first();
$user->save();
```

We will look at improving the [related models docs](http://octobercms.com/docs/database/relations#inserting-related-models) to make this API more obvious. Thanks

**Comment by bbrandtlv** [comment]
`$user->group = UserGroup::whereCode('buyer')->first();
  $user->save();`


`"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'group' in 'field list' (SQL: update `users` set `group` = {"id":3,"name":"Buyer","code":"buyer","description":"Buyers group","created_at":"2016-11-20 18:08:51","updated_at":"2016-11-20 18:09:01"}, `updated_at` = 2016-11-25 14:32:42 where `id` = 42)" on line 662 of /Applications/MAMP/htdocs/fidgycube.co/vendor/laravel/framework/src/Illuminate/Database/Connection.php
`
Getting this (

**Comment by Eoler** [comment]
Relating models is probably more like this:
```
$user->group()->associate( UserGroup::whereCode('buyer')->first() );

**Comment by daftspunk** [comment]
The relationship may be called "groups" instead of "group".

```
$user->groups = UserGroup::whereCode('AAA')->first();
```

**Comment by bbrandtlv** [comment]
Samuel, 
i changed to 

$user->groups = UserGroup::whereCode('AAA')->first();

and now getting

"Type error: Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array, integer given, called in /Applications/MAMP/htdocs/fidgycube.co/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 340" on line 118 of /Applications/MAMP/htdocs/fidgycube.co/vendor/laravel/framework/src/Illuminate/Database/Grammar.php

**Comment by bbrandtlv** [comment]
@Eoler 
Not working. Gives no error, but not saving into groups table

**Comment by daftspunk** [comment]
Are you sure a group with code AAA exists? This will protect you if it doesn't:

```
$user->groups = UserGroup::whereCode('AAA')->first() ?: null;
```

**Comment by bbrandtlv** [comment]
hey @daftspunk 
Mine is $user->group()->associate( UserGroup::whereCode('buyer')->first() );
bayer and it exists.

**Comment by daftspunk** [comment]
These all should work:

```
$group = UserGroup::whereCode('buyer')->first();

$user->group()->associate($group);

$user->group()->add($group);

$user->group = $group;

$user->group = $group->id;
```

**Comment by bbrandtlv** [comment]
`"Call to undefined method October\Rain\Database\QueryBuilder::associate()" on line 2123 of /Applications/MAMP/htdocs/fidgycube.co/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php`

**Comment by bbrandtlv** [comment]
`$group = UserGroup::whereCode('buyer')->get();`
gives me ID
something wrong with relation as far as i see

**Comment by daftspunk** [comment]
@bbrandtlv, sorry to say we are stabbing in the dark here. Perhaps you can share your code with us so we can give some more educated advice.

**Comment by bbrandtlv** [comment]
(( sad!
Ok. 

`<?php namespace Bbrand\Shop\Components;

use Jiri\JKShop\Components\Basket;
use Session;
use Redirect;
use Mail;
use \RainLab\User\Models\User;
use \RainLab\User\Models\UserGroup;
use Auth;
use Database;

class Basketextend extends Basket
{
    public function componentDetails()
    {
        return [
            'name'        => 'basketextend Component',
            'description' => 'No description provided yet...'
        ];
    }

    public function defineProperties()
    {
        $parentProps = parent::defineProperties();
        $properties = array_merge(
            $parentProps,
                [
                    'myWrapper' => [
                    'title'       => 'Wrapper for content',
                    'description' => 'Wrapper for rendered content',
                    'default'     => '.popup-content',
                    'type'        => 'string'
                    ],  
                    'paypal_business' => [
                        'title'       => 'Paypal Business',
                        'default'     => '.popup-content',
                        'description' => 'Your bussines account',
                        'type'        => 'string'
                    ],
                    'paypal_return_url' => [
                        'title'       => 'Return URL',
                        'description' => 'Use full url where will be your customer redirect after paid "http://www.example.com/paypal-success"',
                        'type'        => 'string'
                    ],
                    'paypal_use_sandbox' => [
                        'title'       => 'Use sandbox',
                        'description' => 'For testing only!',
                        'type'        => 'checkbox'
                    ],  
                    'slug' => [
                        'title'       => 'URL Order ID',
                        'description' => 'URL Order ID',
                        'default'     => '{{ :slug }}',
                        'type'        => 'string'
                    ],
                    'stripe_publishable_key' => [
                        'title'       => 'Publishable Key',
                        'description' => 'For testing you can use: "xxxx"',
                        'type'        => 'string'
                    ],
                    'stripe_secret_key' => [
                        'title'       => 'Secret Key',
                        'description' => 'For testing you can use: "xxx"',
                        'type'        => 'string'
                    ],
                    'stripe_return_url' => [
                        'title'       => 'Success URL',
                        'description' => 'Use full url where will be your customer redirect after paid "http://www.example.com/paypal-success"',
                        'type'        => 'string'
                    ],

                ]
            );

        return is_array($properties) ? $properties : $parentProps;
    }


    public function onCheckEmail($email)
    {
        return Auth::findUserByLogin($email) ? 1 : 0;
    }

    public function onBasket(){
        $data = [];
        $data["basket"] = $this->getSessionBasket();
        $data["jkshopSetting"] = \Jiri\JKShop\Models\Settings::instance();
        
        return [ 
            $this->property('myWrapper') => $this->renderPartial('::basket-0', $data) 
        ];
    }

    public function onMyCompleteOrder() {
        
        $jkshopSetting = \Jiri\JKShop\Models\Settings::instance();
        
        // create order
        $basket = $this->getSessionBasket();
        $order = new \Jiri\JKShop\Models\Order();
        $order->createFromBasket($basket);
        $order->save();
        // $this->page['slug'] = $order->id;
        $order = \Jiri\JKShop\Models\Order::find($order->id);        
        $this->page["order"] = $order;
        
        // paypal details
        $this->page["paypal_business"] = $this->property('paypal_business');
        $this->page["paypal_currency_code"] = $order->paymentGateway->gateway_currency;
        $this->page["paypal_return_url"] = $this->property('paypal_return_url');
        $this->page["paypal_use_sandbox"] = $this->property('paypal_use_sandbox');
        $this->page["jkshopSetting"] = $jkshopSetting;
        
        // Mail::sendTo('admin@domain.tld', 'acme.blog::mail.message', $params);

        if ( !($this->onCheckEmail($order->contact_email)) ){
            $user = new User;
            $user = Auth::register([
                'name' => $order->ds_first_name,
                'email' => $order->contact_email,
                'password' => 'changeme',
                'password_confirmation' => 'changeme',
                'username' => $order->contact_email,
                'jkshop_ds_first_name' => $order->ds_first_name,
                'jkshop_ds_last_name' => $order->ds_last_name,
                'jkshop_ds_address' => $order->ds_address,
                'jkshop_ds_address_2' => $order->ds_address_2,
                'jkshop_ds_postcode' => $order->ds_postcode,
                'jkshop_ds_city' => $order->ds_city,
                'jkshop_ds_county' => $order->ds_county,

                'jkshop_is_first_name' => ($order->is_first_name) ? : $order->ds_first_name,
                'jkshop_is_last_name' => ($order->is_last_name) ?  : $order->ds_last_name,
                'jkshop_is_address' => $order->is_address,
                'jkshop_is_address_2' => $order->is_address_2,
                'jkshop_is_postcode' => $order->is_postcode,
                'jkshop_is_city' => $order->is_city,
                'jkshop_is_county' => $order->is_county,
                'jkshop_contact_email' => $order->contact_email,
                'jkshop_contact_phone' => $order->contact_phone,
            ]);
            
            $group = UserGroup::whereCode('buyer')->get();
            // $user->associate($group);
            // $user->group()->add($group);
            $user->save();

            
        }

        $data = ['name' => $order->ds_first_name .' '. $order->ds_last_name, 'email' => $order->contact_email, 'orderid' => $order->id];

        Mail::send('bbrand.shop::mail.neworder', $data, function($message) use ($data){
            
            $message->bcc( $data['email'], 'Alexei Kositsin' );
            $message->to( $data['email'], $data['name'] );
            $message->from( 'info@fidgycube.co', 'FidgyCube.co' );
            $message->subject( 'FidgyCube.co order' );

        });

        // clear basket
        Session::forget('jkshop-basket');
        
        if ($order->payment_gateway_id == 1)
        return [
            $this->property('myWrapper') => $this->renderPartial('::basket-4-thanks-paypal') 
        ];
        else if
        ($order->payment_gateway_id == 2){
            $this->page["stripe_publishable_key"] = $this->property('stripe_publishable_key');
            $this->page["stripe_secret_key"] = $this->property('stripe_secret_key');
            $this->page["stripe_currency_code"] = $order->paymentGateway->gateway_currency;
            $this->page["stripe_return_url"] = $this->property('stripe_return_url');
            return [
                $this->property('myWrapper') => $this->renderPartial('::custom-strupe-checkout') 
            ];
        }
    }  

     public function onSubmitPay() {
        //  return 'fuck';

        $stripe = [
          'secret_key'      => $this->property('stripe_secret_key'),
          'publishable_key' => $this->property('stripe_publishable_key')
        ];
        \Stripe\Stripe::setApiKey($stripe['secret_key']);
        
        // save IN to events
        $eventLog = new \System\Models\EventLog();
        $data = array();
        $data["name"] = "Stripe Response";
        $data["post"] = post();
        $eventLog->message = json_encode($data);
        $eventLog->save();

        $order_id = post('order_id');
        // get order
        $order = \Jiri\JKShop\Models\Order::find( $order_id );

        if ($order != null) {
            $token  = post('stripeToken');
            $customer = \Stripe\Customer::create(array(
                'email' => $order->contact_email,
                'card'  => $token
            ));
            
            $charge = \Stripe\Charge::create(array(
                'customer' => $customer->id,
                'amount'   => ($order->total_price + $order->shipping_price)*100,
                'currency' => $order->paymentGateway->gateway_currency
            ));
            
            // check response
            $order->orderstatus = $order->paymentGateway->orderStatusAfter;
            $order->paid_date = \Carbon\Carbon::now();
            $order->paid_detail = $charge;
            $order->save();
            
            $data = ['name' => $order->ds_first_name . ' ' . $order->ds_last_name , 'email' => $order->contact_email, 'orderid' => $order->id];

            Mail::send('bbrand.shop::mail.payment', $data, function($message) use ($data) {
                
                $message->bcc('info@fidgycube.co', 'Alexei Kositsin');
                $message->to( $data['email'], $data['name'] );
                $message->from('info@fidgycube.co', 'FidgyCube.co');
                $message->subject('FidgyCube.co order');

            });

            return 'dsd';
            // return Redirect::to($this->property('stripe_return_url'));   //Redirect::to("/");
        }        
        
    }


}
`
using JIRI shop plugin. 

![screen shot 2016-11-29 at 22 18 22](https://cloud.githubusercontent.com/assets/21307256/20727358/d871a2e8-b681-11e6-93e1-c2608a6a8568.png)

**Comment by daftspunk** [comment]
Ok, I see the issue:

This code returns a COLLECTION (an array of groups):

```
// Do not use get()
$group = UserGroup::whereCode('buyer')->get();
```

This code should be used to return a SINGLE group:

```
// Use first()
$group = UserGroup::whereCode('buyer')->first();
```

The relationship name is not called GROUP:

```
// Do not use group()
$user->group()->associate(...);
```

This code should reference GROUPS:

```
$user->group()->associate(...);
```

As before, here is the complete working code

```
$group = UserGroup::whereCode('buyer')->first();

$user->group()->associate($group);

$user->group()->add($group);

$user->group = $group;

$user->group = $group->id;
```

**Comment by bbrandtlv** [comment]
( no
code still not working.
you wrote that I should reference to groups (but wrote group)
I changed it to `$user->groups()->associate($group);`
and now it cannot find associate() method. 
I know that I took much of your time, but i cannot find a way to make this working.

i can go hardcore and simply update user_groups table with ids, but i'm sure you didnt ment for this.

ill try to dig more... hopefully will find it.
Thanks

**Comment by bbrandtlv** [comment]
@daftspunk 

Hey
This one is working:

`            $group = array(UserGroup::whereCode('buyer')->first());
            
            $user->groups()->attach($group[0]->id);

            $user->save($group);`

But i'm dont like this solution. (

Hope this will help to somebody.

**Comment by daftspunk** [comment]
Thanks, we have removed `attach()` and `associate()` from the documentation to prevent this kind of confusion. In all cases `add()` should be used instead.

**Comment by bbrandtlv** [comment]
!!!!!!! FINALLY!
`$user->groups()->add(UserGroup::whereCode('buyer')->first());

            $user->save($group);
            `

This one is good!!!!
Thanks again!
