### ISSUE TITLE
How to create the users table first?

### ISSUE THREAD

**Issue by ambitiousguy127** [rainlab/user-plugin#225]
I am using this plugin in my plugin.
In my table, I set user id(users table) as a foreign key.
When I create a table, I encountered this error "Foreign key constraint is incorrectly formed".
I know the reason. This is because my table is created before creating users table.
How can I set the order of table so that the users table is created for the first time.
Please need your help

**Comment by daftspunk** [comment]
Make sure your plugin declares the User plugin as a dependency. This will ensure the User plugin's tables are created before your plugin. See docs for more information:

http://octobercms.com/docs/plugin/registration#dependency-definitions

**Comment by greatking127** [comment]
Thanks for your reply.

I created plugin A and it declares the User plugin as a dependency.
And several tables in plugin A has user id as a foreign key.
In this case, it works fine.

But in another case this doesn't work anyway. This is the scenario.
I want to create a table and user table should this table's id as foreign key.
In this case php artisan october:up command occur migration error.
