### ISSUE TITLE
field validation [question]

### ISSUE THREAD

**Issue by webeks** [rainlab/user-plugin#226]
I want to add extended fields to frontend (either by my own implementation or by your User Plus+ plugin).

Now I am curios how to validate the fields? If I am not mistaken registration is made by _onRegister_ method inside _components/Account_. I don't see any events that I could use to extend validation. 

Any suggestions?

Thanks!

**Comment by daftspunk** [comment]
At this point you are probably much better off building your own component to handle the custom fields, validation and logic. While it is [possible to extend the account form](https://www.youtube.com/watch?v=gBGVOspf1NY) for simple tasks. In this case, you would add to the `$rules` property of the user model when extending it, just like Watch + Learn has done for the "fillable" property.

```
User::extend(function($user) { 
    $user->rules['myfield'] = 'required';
});
```

There is also the `beforeValidate` event you can use.

**Comment by webeks** [comment]
Thanks. I will look into beforeValidate. Could you maybe point me in the direction where this function is called? I cant seem to find any fire event for it? Is it some magic method naming that I am unaware of? 

Thanks!

**Comment by Eoler** [comment]
It's Laravel's Eloquent magic - package that OctoberCMS models are built upon:
https://octobercms.com/docs/database/model#events
