### ISSUE TITLE
Activation check message

### ISSUE THREAD

**Issue by jiiis** [rainlab/user-plugin#235]
Hi,

Is there a way to show this `activation check message` after registration if the activation mode is `user`?

I noticed that after registration, there would still be no `user` twig variable in the session, which means there would be no chance to check `user.is_activated`.

Thanks.

**Comment by jiiis** [comment]
Can we allow signing in unactivated user and in the account page just showing the `activation check message`?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
