### ISSUE TITLE
[Suggestion] Check UserSetting in backend controller User

### ISSUE THREAD

**Issue by Yaha** [rainlab/user-plugin#242]
Hi, I offers a small improvement.
Can you check "Require Activation" setting before adding the class "disabled" in controller Users::listInjectRowClass(), and in the "preview.htm" view before include the "hint_activate" partial?
When we do not use the "Require Activation", this is confusing.
Thanks

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
