### ISSUE TITLE
Error when user deactivates their account.

### ISSUE THREAD

**Issue by pmhou** [rainlab/user-plugin#243]
The following SQL error occurs when a user deactivates their account. It appears that a new user record is being inserted with the same credentials and failing on the duplicate id.
```sql
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' 
```

Looking at the onDeactivate() method in components/Account.php, the issue seems to occur when the user is soft deleted then logged out. T
```php
Auth::logout();
```
This in turn calls `October\Rain\Auth\Manager->logout()` where the `forceSave()` method is called.

```php
/**
     * Logs the current user out.
     */
    public function logout()
    {
        if ($this->user) {
            $this->user->setRememberToken(null);
            $this->user->forceSave();
        }

        $this->user = null;

        Session::forget($this->sessionKey);
        Cookie::queue(Cookie::forget($this->sessionKey));
    }
```

Stack trace attached
[stack.txt](https://github.com/rainlab/user-plugin/files/716374/stack.txt)

**Comment by sgreener** [comment]
Can confirm I have encountered this bug as well, is there a way to get around it?

My steps that reproduce it are;

1. create new account, get redirected back to the same page
2. now deactivate this account just created.

Bug: error thrown 'Integrity constraint violation'

**Comment by LukeTowers** [comment]
@sgreener @pmhou Please confirm that #245 fixes this for you
