### ISSUE TITLE
Option to Disable Username Change

### ISSUE THREAD

**Issue by MattMcManis** [rainlab/user-plugin#254]
I set Login attribute to Username.

![Login Attribute](https://i.imgur.com/3WJW5Oy.jpg)

If I go to Update User Details Page, it shows the inputs a user can change:

- Full Name `name`
- Email `email`
- New Password
- Confirm Password

Though someone can add the Username field just by inspecting element, edit the HTML, add the input with `name="username"` `value="Desired Name"`, submit and it will change the name and update the `username` column in the database.

Could an option be added to Account.php `update()` function to disable which fields a user can Update?

**Comment by LukeTowers** [comment]
I'm not sure this is desired functionality, you'd have to have an entirely separate option to prevent users from changing their username, we can't just block the updating of whatever login attribute wasn't selected by default; that could break things for developers that let their users change those values even if they don't use them for logging in.

**Comment by PowerUpio** [comment]
@LukeTowers  I was able to disable the username change by extending the user model and adding:

```
\RainLab\User\Models\User::extend(function($model) {
    $model->bindEvent('model.beforeUpdate', function() use ($model) {
        # Deny Username Change
        if ($model->isDirty('username')) {
            throw new \ValidationException(['username' => 'Username change disabled.']);
        }
    });
}); 
```

**Comment by MattMcManis** [comment]
@LukeTowers I was able to disable the username change by extending the user model and adding:

\RainLab\User\Models\User::extend(function($model) {
    $model->bindEvent('model.beforeUpdate', function() use ($model) {
        # Deny Username Change
        if ($model->isDirty('username')) {
            throw new \ValidationException(['username' => 'Username change disabled.']);
        }
    });
});

**Comment by LukeTowers** [comment]
@MattMcManis You can also hook into `beforeSave` to handle model creation as well. Glad you were able to find a solution for your use case!

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
