### ISSUE TITLE
Activation code using Auth::register facade

### ISSUE THREAD

**Issue by Asinox** [rainlab/user-plugin#257]
Hello guys, im having an issue, and i would like to ask if there is a way to generate the activation code when im using the  Auth Facade:

```
$user = Auth::register([
    'name' => 'Some User',
    'email' => 'some@website.tld',
    'password' => 'changeme',
    'password_confirmation' => 'changeme',
]);
````
Eveything is fine, but i cant see the activation code generated... any idea?

Thank you

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
