### ISSUE TITLE
Fillable avatar

### ISSUE THREAD

**Issue by FelixINX** [rainlab/user-plugin#260]
Hello,

I am wondering why the avatar field isn't fillable. For instance, the social login plugin could use this to add Google/Facebook profile picture to the user model.

I can make a pull-request, but why it is not there already? Maybe there is a good reason.

Code: https://github.com/rainlab/user-plugin/blob/master/models/User.php#L40-L51

**Comment by LukeTowers** [comment]
Good question, I appreciate the pre-PR issue you created for this. You'd have to ask @daftspunk about that however.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
