### ISSUE TITLE
Call to undefined method AuthManager::createUserModelQuery()

### ISSUE THREAD

**Issue by jareis** [rainlab/user-plugin#261]
Hello,
After upgrading the user-plugin i started to the error  "_Call to undefined method RainLab\\User\\Classes\\AuthManager::createUserModelQuery()_"

**Octobercms**: 
 - system build: 345
 - rainlab/user-plugin: 1.3.4
 - PHP 5.6.30

log: [https://pastebin.com/FamRqyp5](https://pastebin.com/FamRqyp5)

Best regards...

**Comment by LukeTowers** [comment]
How on earth were you able to upgrade the plugin without also upgrading the build of October? Your system build is ~70 builds out of date

**Comment by jareis** [comment]
Oh! I didn't notice that...

1. Every single plugin, in use, are up to date (i have double checked),
2. I have changed the platform to a dev server, and reset the all config files to default.

And when i:
`
$php artisan october:update 
Updating October...
No new updates found
`

Should this even be possible?
I'm i missing something?

**Comment by LukeTowers** [comment]
in config/cms.php is your `disableCoreUpdates` set to true?

**Comment by jareis** [comment]
Meanwhile, I installed and set the default config files. 
Everything is working ok now.

The origin of the problem was the `disableCoreUpdates=>true` (as @LukeTowers suggested)

Thank you
