### ISSUE TITLE
How to invite, convert or activate users in bulk?

### ISSUE THREAD

**Issue by yapsr** [rainlab/user-plugin#266]
I have imported many users. Now I would like to invite, convert to registered user or activate multiple users in het backend, but these bulk actions are not available from the drop down menu.

How do I add extra bulk actions in the in `plugins/rainlab/user/controllers/users/_list_toolbar.htm` ?

How do I add extra bulk actions in the users controller (`plugins/rainlab/user/controllers/Users.php`) to the bulk action method `\RainLab\User\Controllers\Users::index_onBulkAction` ?

Any help would be appreciated.

**Comment by daftspunk** [comment]
Interesting, must've missed this one. You can submit a Pull Request if you like! 😃

**Comment by yapsr** [comment]
Hello @daftspunk , I've created a small Pull Request to add the activation option. Please see https://github.com/rainlab/user-plugin/pull/267

I did not add the options to invite or convertToRegistered users, because they require parameters, which makes it a bit more complicated than necessary for my direct needs.

**Comment by daftspunk** [comment]
Fixed by #267
