### ISSUE TITLE
How to restrict access before onStart() or Ajax method on a page is called?

### ISSUE THREAD

**Issue by yapsr** [rainlab/user-plugin#268]
I would like to achieve that all pages (and ajax requests) behind some url path (i.e. `http://example.com/my/pages`) are accessible only to logged in users.

I think the place where the session component kicks in in the OctoberCMS lifecycle is not correct. At least, it is nog suitable for my situation.

Example of a page:
```
url = "/my/record/update/:id"

[session]
security="user"

==
function onAjaxCheck() {
    // Process ajax request here...
}

function onStart() {
    // Do something before displaying the page
}

==
<h1>Edit Some Record</h1>
...
```
Current situation:  The session component checks if user is allowed access to this page only AFTER the page onStart() or onAjaxCheck() method has been called. 

Desired situtation: The session component checks if user is allowed access to this page BEFORE the page onStart() method or onAjaxCheck() is called. 

How do I achieve this?

I tried this, but I find it is ugly because it is not DRY, and it causes the session onRun method to run twice.
```
url = "/my/record/update/:id"

[session]
security="user"

==
function onAjaxCheck() {
    if ($result = $this->components['session']->onRun()) {
        return $result;
    }
   // Process ajax request here...
}
function onStart() {
    if ($result = $this->components['session']->onRun()) {
        return $result;
    }
    // Do something before displaying the page
}
==
<h1>Edit Some Record</h1>
...
```
And because, above all, I think the session component should run this check BEFORE any other page method.

Or should I use the AuthMiddleware solution?

Any ideas on this, anyone?

**Comment by LukeTowers** [comment]
@yapsr Try changing `function onRun` to `function init` in https://github.com/rainlab/user-plugin/blob/master/components/Session.php. Let me know how that works for you

**Comment by yapsr** [comment]
That works out perfectly!

**Comment by yapsr** [comment]
Added a pull request here: https://github.com/rainlab/user-plugin/pull/270

**Comment by LukeTowers** [comment]
Merged, happy to help!
