### ISSUE TITLE
Users tab bug with Forum Plugin

### ISSUE THREAD

**Issue by JohnsonJackblue** [rainlab/user-plugin#27]
hi, i found a bug on User tab if you have already installed User and Forum Plugin and you click on "Forum username" tab, you have this exception :

SQLSTATE[42S22]: Column not found: 1054 Unknown column '@username' in 'order clause' (SQL: select `users`.*, (select rainlab_forum_members.username from `rainlab_forum_members` where `rainlab_forum_members`.`user_id` = `users`.`id`) as `forum_member_username` from `users` order by `@username` desc limit 20 offset 0)

Thank you in advance for solving this problem :)

Cordially, Jackblue

**Comment by sulazix** [comment]
Same for me : 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rainlab_forum_members.username' in 'field list' (SQL: select `new_users`.*, (select rainlab_forum_members.username from `new_rainlab_forum_members` where `new_rainlab_forum_members`.`user_id` = `new_users`.`id`) as `forum_member_username` from `new_users` order by `name` desc limit 20 offset 0)

Only append when forum is enabled
