### ISSUE TITLE
Issue with logout AJAX

### ISSUE THREAD

**Issue by alexCollienne** [rainlab/user-plugin#276]
Hi,

I try to set the logout link but I get the following answer : "AJAX manager "onLogout" can not be found". I found nothing into the code to figure out what happens. So, can you help me please?

Best regards,

Alexandre Collienne

**Comment by davethepottingshed** [comment]
Hi Alex

Do you have the Session component on the layout or page you are trying to logout from?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
