### ISSUE TITLE
Banned users

### ISSUE THREAD

**Issue by davethepottingshed** [rainlab/user-plugin#279]
When banning a user is does not stop them from logging in

**Comment by LukeTowers** [comment]
Feel free to dig into this yourself and provide a PR fixing it :)

**Comment by davethepottingshed** [comment]
OK great.

Will do when I have the time

**Comment by davethepottingshed** [comment]
@LukeTowers 

Currently extending the plugin by running the following method on boot:

Please let me know if I need to do anything else.


>     /**
>      * Check If User is Banned.
>      */
>     public function checkIfUserIsBanned()
>     {
>         Event::listen('rainlab.user.beforeAuthenticate', function ($component, $credentials) {
>             $user = Auth::authenticate($credentials, true);
>             if ($user->isBanned()) {
>                 Auth::logout();
>                 throw new AuthException('Sorry, this user is currently not activated. Please contact us for further assistance.');
>             }
>         });
>     }

**Comment by LukeTowers** [comment]
Perfect, thanks!
