### ISSUE TITLE
Build 422 Auth Facade Fails

### ISSUE THREAD

**Issue by pixelhn** [rainlab/user-plugin#282]
The static method Auth::check() and Auth::getUser() return a false/null response

**Comment by LukeTowers** [comment]
Where? Have you looked at http://octobercms.com/support/article/rn-9, the session handling middleware is no longer applied to all requests, you have to manually add it with `middleware('web')`. There are lots of reported issues for this.

**Comment by pixelhn** [comment]
ok, my problem is  from routes.php, can you give me an example?

**Comment by LukeTowers** [comment]
Paste your routes.php here and I can do that for you

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
