### ISSUE TITLE
Account activation check runs twice on one request

### ISSUE THREAD

**Issue by pat-och** [rainlab/user-plugin#283]
using rainlab user plugin very basically, i got `Your account is already activated!` message when landing on the page containing the component account from mail activation link.

by using debugbar,  i saw that the account.php component onRun method is executed 2 times. first time, the account is ativated and second time, process fail into `Your account is already activated!` exception

it is very disturbing stuff for user.

have you some idea why having this behavior ? seems there is a redirect but didn't find it by now

note: The activation mail link is well builded (with https and www so my .htaccess redirect seems not responsible)

_environment:_
https
oc build 419, rainlab user 1.3.4, Sweet Alert 1.1.0

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
