### ISSUE TITLE
Register username

### ISSUE THREAD

**Issue by skobeo** [rainlab/user-plugin#284]
seems that field name in register.html default is name, as in account validation rules, when login attribute is LOGIN_USERNAME field name is username. So do not match and no error returned by validation when field is empty.
Try to replace name by username in register.html, and all is ok.
Dit i miss something ?
Thanks

**Comment by JBonnyDev** [comment]
To clarify on this.   
The field with the attribute name="name" in the register.htm file for the Account component has nothing to do with managing the login and authentication of a user. This field simply allows users to designate their own alias or leave it empty to be "anonymous".
As per the readme.md file:
> By default the User plugin will use the email address as the login name. To switch to using a user defined login name, navigate to the backend under System > Users > User Settings and change the Login attribute under the Sign in tab to be Username. Then simply ask for a username upon registration by adding the username field:

    <form data-request="onRegister">
        <label>Full Name</label>
        <input name="name" type="text" placeholder="Enter your full name">

        <label>Email</label>
        <input name="email" type="email" placeholder="Enter your email">

        <label>Username</label>
        <input name="username" placeholder="Pick a login name">  // NEW FIELD FOR USERNAME

        <label>Password</label>
        <input name="password" type="password" placeholder="Choose a password">

        <button type="submit">Register</button>
    </form>

**Comment by LukeTowers** [comment]
We could probably add the field to the default component markup when that mode is in use however @JBonnyDev. Would you be willing to make that a PR?

**Comment by JBonnyDev** [comment]
@LukeTowers Yeah I can take a look at it.
