### ISSUE TITLE
Default display is bootstrap

### ISSUE THREAD

**Issue by skobeo** [rainlab/user-plugin#285]
Hi,
using october for first time, i discover that class col-md-6 is hardcoded in account/default.html
So i have to override if i do not use bootstrap ? Is it correct ? And then, which is the best pratcie to override it in my theme ?
thanks

**Comment by bhargavy** [comment]
Check documentation for [Overriding Partials](https://octobercms.com/docs/cms/components#overriding-partials)

**Comment by LukeTowers** [comment]
Thanks @bhargavy
