### ISSUE TITLE
If forceUrl = 1 can't login get redirected to auth page

### ISSUE THREAD

**Issue by roulendz** [rainlab/user-plugin#287]
The issue is that when I turn on forceUrl = 1, Authentication and Registration does not work.
If I turn it off, language switching does not work.
In a video, you can see my issue in more details.

Here I made a video, sorry that handheld.
https://www.youtube.com/watch?v=9cAoE_sRvPI
[Stabilized video]
https://www.youtube.com/watch?v=h__GyP4FAP8
Please let me know where could be my problem.

Thanks

**Comment by LukeTowers** [comment]
Look at the RainLab.Translate plugin, I believe the forceUrl thing was a workaround for session handling on build 420+ if I remember correctly. 

Try taking a stab at digging into what forceUrl on the RainLab.Translate plugin component is doing to the RainLab.User plugin yourself and keep us updated on your progress. Good luck!

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
