### ISSUE TITLE
session recording does not work

### ISSUE THREAD

**Issue by NicolasFR-45** [rainlab/user-plugin#288]
I can not use the sessions on my page :(
I created a new member in http://october/admin/rainlab/user/users and that I activated.

My account.htm page ...
```
title = "Membership Area"
url = "/account/:code?"
layout = "octaskin"
description = "Member page"
is_hidden = 0

[Account]
paramCode = "code"
forceSecure = 0

[session]
security = "all"
```

The code :
`{% component 'account'%}`
displays well the forms to register and connect but the code:
`{% if user %}
    <p>Hello {{ user.name }}</p>
{% else %}
    <p>Nobody is logged in</p>
{% endif %}`
always returns to the same page without connecting, why?

Thank you for your help :)

**Comment by Ronnon78** [comment]
Similarly to me. I had everything working. Something happened that stopped working. I check it out on a clean instance.

**Comment by Ronnon78** [comment]
I found a problem. Rainlab.User does not work with the plug-in: Extend Translate (https://octobercms.com/plugin/panakour-translate). After removing everything has returned to normal.

**Comment by LukeTowers** [comment]
@panakour please investigate.

**Comment by panakour** [comment]
@LukeTowers the plugin that @Ronnon78 says, the only thing that is doing is to select different menu  depending on the current locale. `StaticMenuMultilingual ` component does not do anything more than the `RainLab StaticMenu` plugin does, especially something related to the sessions.

**Comment by LukeTowers** [comment]
@Ronnon78 input?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
