### ISSUE TITLE
Support social login

### ISSUE THREAD

**Issue by tplessis** [rainlab/user-plugin#29]
Hi,

Would it be possible to login with social networks such as Twitter, Facebook, Google, Yahoo and more in the next release ?

Thx,

**Comment by tplessis** [comment]
Yes, but it would be better to have an "official" support of sociale login in the rainlab user plugin. Why to not use socialite : https://github.com/laravel/socialite ?

**Comment by daftspunk** [comment]
This should be handled as a separate plugin, social login is outside the scope of standard account management
