### ISSUE TITLE
Redirect back to requested url after login

### ISSUE THREAD

**Issue by Asinox** [rainlab/user-plugin#290]
Hey guys, this is question, i can't see in the documentation nothing related to redirect back to requested url after login, i mean, hitting a protected url redirect to login form (if im not logged in)... how the plugin can take my back to the requested protected url after success login?

Thanks!

**Comment by Asinox** [comment]
I did, just adding a missing form field named "redirect" and fill it with the previous url.

**Comment by mjauvin** [comment]
@Asinox this is handled by the framework using the "url.intended". You can also check #258 which gives detailed example scenarios (this was done to explain a bug which is currently being addressed when backend/frontend sessions were used simultaneously).
