### ISSUE TITLE
Exception when resetting password

### ISSUE THREAD

**Issue by alexCollienne** [rainlab/user-plugin#294]
Hello,

When I try to reset the password, everything is ok until the last action. When I have the right code and I set my new password, on the validation, I get this error message : ""The Response content must be a string or object implementing __toString(), "boolean" given." on line 399 of /home/normbelcaw/www/protected/vendor/symfony/http-foundation/Response.php".

Any idea where I can fix this please?

Thanks.

**Comment by LukeTowers** [comment]
Not a clue. We'd need to see the full stack trace to have any hope of helping you with that.

**Comment by alexCollienne** [comment]
Unfortunatly, I've no more informations. Everything is in AJAX and I just get an error 500 on the request.

How can I help you to help me?

**Comment by LukeTowers** [comment]
Check your event logs in the backend and see if you can find it. It should have logged the stack trace.

**Comment by alexCollienne** [comment]
Here is the stack trace I get:

Stack trace:
#0 /pathTo/vendor/laravel/framework/src/Illuminate/Http/Response.php(54): Symfony\Component\HttpFoundation\Response->setContent(false)
#1 /pathTo/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(false)
#2 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Array, 200, Array)
#3 /pathTo/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Routing\ResponseFactory->make(Array, 200)
#4 /pathTo/modules/cms/classes/Controller.php(662): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#5 /pathTo/modules/cms/classes/Controller.php(330): Cms\Classes\Controller->execAjaxHandlers()
#6 /pathTo/modules/cms/classes/Controller.php(213): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#7 /pathTo/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run('password-oublie')
#8 [internal function]: Cms\Classes\CmsController->run('password-oublie')
#9 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#10 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('run', Array)
#11 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Cms\Classes\CmsController), Object(Illuminate\Routing\Route), 'run')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Cms\Classes\CmsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
#18 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Cms\\Classes\\Cms...', 'run')
#19 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#20 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#27 /pathTo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#28 /pathTo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#30 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /pathTo/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#34 /pathTo/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#37 /pathTo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#40 /pathTo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 /pathTo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /pathTo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 /pathTo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 /pathTo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#50 /pathTo/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#51 {main}

I forgot to tell the reset of the password is working. I got this error as an alert and any redirection is launch.

**Comment by LukeTowers** [comment]
@alexCollienne please post stack traces inside of code blocks to prevent creating unnecessary references to early issues.

**Comment by alexCollienne** [comment]
Ok, sorry.

**Comment by LukeTowers** [comment]
Hmm, this is odd. What build of October are you using and what plugins and versions of those plugins are you using?

**Comment by alexCollienne** [comment]
The October version is 419.

Here you can find all the plugin I use in the project.

- October Demo | Provides features used by the provided demonstration theme. | 1.0.1 | Alexey Bobkov, Samuel Georges
- Contact Us | A simple, complete and modular contact form | 1.0.2 | DevINX
- Google Analytics | Provides the Google Analytics tracking and reporting. | 1.2.1 | Alexey Bobkov, Samuel Georges
- Pages | Fonctionnalités de pages et menus statiques. | 1.2.16 | Alexey Bobkov, Samuel Georges
- Utilisateur | Gestion des utilisateurs Front-End. | 1.3.4 | Alexey Bobkov, Samuel Georges
- JKShop | Le meilleur plugin eCommerce pour OctoberCMS | 1.6.9 | Jiri Kubak
- SiteSearch | Global search for your frontend | 1.3.2 | OFFLINE LLC
- Traductions | Permet de créer des sites Internet multilingues | 1.2.11 | Alexey Bobkov, Samuel Georges
- Slider | Add sliders to your website. | 1.0.5 | getRight
- Newsletter | Plugin de la newsletter. | 1.0.2 | InIT.biz Ltd.
- Social Sharing Buttons | Display buttons to share content on different social networks | 1.3.0.1 | Martin
- EUCookieLawMadness | Display an EU cookie law popup. | 1.0.2 | Miha Trtnik

Thanks for helping. Let me know if you need more information.

**Comment by LukeTowers** [comment]
@alexCollienne are you able to update to the latest build and let me know if the issue is still present?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
