### ISSUE TITLE
Functionality to detect if a user belongs to a group

### ISSUE THREAD

**Issue by maartenmachiels** [rainlab/user-plugin#295]
I've been using the User plugin for an administration system and it works very well, except for one detail. 
Since the User plugin has functionality for groups, I'd like to detect if a user is part of a group on the frontend. I've seen multiple questions (review section of User plugin & stackoverflow) regarding this, haven't found a clear solution yet.

Would it be possible to do something like:
```
        {% if user inGroup("employees") %}
        // Some text for employees
        {% endif %}
```
where `employees` would be the group code?

I've been messing around with things like:
```
        {% if ( user and "employees" in user.groups | keys ) %}
        // Some text for employees
        {% endif %}
```
but this definitely doesn't work.

Below solution does work, but as you can see it is far from elegant or efficient:
```
       {% for group in user.groups %}
            {% if group.code == "employees" %}
            // Some text for employees
            {% endif %}
        {% endfor %}
```

Any suggestions?

**Comment by JBonnyDev** [comment]
If you are not satisfied with the last solution I would suggest taking a look at extending twig.   
[Extending Twig](http://octobercms.com/docs/plugin/registration#extending-twig)

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by maartenmachiels** [comment]
Hi Ben, sorry for leaving this for such a long time and thank you for your follow-up. I've tested the solution as provided by @joakimbo and it werks perfectly. My workaround beforehand was this eyesore:

```
{% for group in user.groups %}
    {% if group.code == "my_user_group" %}
       Yes, I belong to my_user_group
    {% endif %}
{% endfor %}
```
Thank you @joakimbo and @bennothommo !!

**Comment by bennothommo** [comment]
Not a problem, @maartenmachiels. Thank you for confirming the fix too! :)

**Comment by snipiba** [comment]
Just why guys?
```
{% if user.groups.pluck('code').contains('<groupname>') %}
....
{% endif %}
```
