### ISSUE TITLE
Missing german languages

### ISSUE THREAD

**Issue by mikestraczek** [rainlab/user-plugin#296]
Hey,

I wondering, that i get only english text and I saw in the "de/lang.php" missing languages.

Example
rainlab.user::lang.account.banned

And I get sometimes the english language, but the german language exists and in my "app/config.php" is the locale on "de" and in backend i set german as default language and delete the english language.

Greetz
Mike Straczek

**Comment by LukeTowers** [comment]
Feel free to make a PR to add the missing translations.
