### ISSUE TITLE
Wrong password on login that contains characters of actual password gives too much info

### ISSUE THREAD

**Issue by hbakkercg** [rainlab/user-plugin#297]
if a wrong password is entered that is close to real password an error is shown in popup that says:

"A user was found to match all plain text credentials however hashed credential "password" did not match.

This allows for hacker to know that they have right username and are pretty close on the password.

Looks like this is due to an exception thrown on the Auth::authenticate() call whereby the catch block does a Flash::error($ex->getMessage());

Requesting that the Flash error be more generic or even parameterized to where a message can be configured.

**Comment by hbakkercg** [comment]
Actually figured out how to override the onSignIn()

**Comment by LukeTowers** [comment]
@hbakkercg that message is only shown when debug mode is enabled for your project. Also, it has nothing to do with how "close" they are on the password, only that the password is invalid while the username is valid.
