### ISSUE TITLE
attributes for validation doesn't work

### ISSUE THREAD

**Issue by HekmatFavid** [rainlab/user-plugin#302]
I want change "The login field is required" validation message to "The mail field is required" .
by add attributes array  to localization file in lang folder dosent change any thing, please help me how to change attributes for validation?
thank's.

**Comment by LukeTowers** [comment]
What have you already tried?

**Comment by HekmatFavid** [comment]
I solve this problem, my mistake was attempt to change attributes in user plugin's folder but attributes array is in Modules/System/lang folder.
I test it for example:
    'attributes' => [
        'login'=>'user name',
    ],
and instead of validation message 'The "login" field is required' show 'The username field is required'

**Comment by LukeTowers** [comment]
@HekmatFavid See my https://github.com/octobercms/october/issues/2804#issuecomment-350747579
