### ISSUE TITLE
How to localize activated user attempt login validation message ?

### ISSUE THREAD

**Issue by HekmatFavid** [rainlab/user-plugin#304]
Is the way to change localization of not activated user login attempt by following message ?
"cannot login user "foo@bar.com" as they are not activated"
and another validation messages like user suspended and so on.

**Comment by HekmatFavid** [comment]
I want localize some authentication messages like "A user was found to match all plain text credentials however hashed credential "%s" did not match" for wrong password . i found it under vendor\october\rain\src\Auth\Manager.php path but there is not any lang folder for localize messages.
please add localization data in this section.
thank's.

**Comment by LukeTowers** [comment]
@HekmatFavid comment on https://github.com/rainlab/user-plugin/issues/223, this is a duplicate of that.
