### ISSUE TITLE
Success Flash Message doesn't show after ajax call

### ISSUE THREAD

**Issue by HekmatFavid** [rainlab/user-plugin#305]
I have form with data-request="onUpdate" and data-request-update="'alert' : '#msg'"

alert.htm
```

{% flash %}
<div id="flsh" class="alert alert-{{ type == 'error' ? 'danger' : type }}">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
</div>
{% endflash %}
```
`<div id="msg">{% partial 'alert' %}</div>`

when i post form and my input fields update properly success flash doesn't show and after refresh current page flash message appear. i want see flash message after ajax call without refresh page.
Is way to do this?

**Comment by LukeTowers** [comment]
@HekmatFavid You need to make sure you load framework.js and framework.extras.js on your pages and then include the snippet [here](http://octobercms.com/docs/ajax/javascript-api#global-events-examples) for the global configuration options.

**Comment by Samuell1** [comment]
@LukeTowers I findout forms need to have attribute `data-request-flash` to make it work. Maybe something was changed?

**Comment by LukeTowers** [comment]
@Samuell1 did you add my snippet:

```js
$(document).on('ajaxSetup', function(event, context) {
    // Enable AJAX handling of Flash messages on all AJAX requests
    context.options.flash = true

    // Enable the StripeLoadIndicator on all AJAX requests
    context.options.loading = $.oc.stripeLoadIndicator

    // Handle Error Messages by triggering a flashMsg of type error
    context.options.handleErrorMessage = function(message) {
        $.oc.flashMsg({ text: message, class: 'error' })
    }

    // Handle Flash Messages by triggering a flashMsg of the message type
    context.options.handleFlashMessage = function(message, type) {
        $.oc.flashMsg({ text: message, class: type })
    }
})
```

**Comment by Samuell1** [comment]
@LukeTowers does this triggers the twig "flash" method?
