### ISSUE TITLE
Uploading Avatar image from frontend

### ISSUE THREAD

**Issue by DraganGagi** [rainlab/user-plugin#308]
Hey, how can i make it possible that users upload their avatar images from account page when they are already logged in and registered (update partial)? I tried modifing update partial with something like this but it didnt work. 

 ` <label>User Avatar</label>
    <input type="file" name="avatar" accept="image/*"  data-request-files data-request-flash>`

**Comment by LukeTowers** [comment]
Try reading https://octobercms.com/forum/post/frontend-file-upload
