### ISSUE TITLE
Registering a user does not allow deferred bindings to be added to the user model

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/user-plugin#311]
It's common behavior to add an avatar to a user. For example in the user's dashboard/profile environment he/she can upload an avatar or some other file. The problem I've ran into today it that the same functionality does not work during the registration process. 

The current (documented) way is by using the `responsiv.uploader` plugin, and binding the model to the currently logged in `user`. In this flow, it makes use of the `onUpdate` method inside the `account` component. So the plugin works. 

The `onRegister` method on the other hand does not work. Even when using the `form()` helpers to generate `_session_key` that is used by the deferrend binding, the user it created in such a way that the deferred binding is not called. Effectively meaning that with the provided components, there is no simple way to attach files to the user during registration.

The onRegister method makes use of the `Auth` facade and I think that doesn't allow or is incompatible with the way `responsiv.uploader` or perhaps deferred bindings in general work. The facade belongs to the backend, and is not a new class specifically for this plugin.

Is there something I'm not getting here, or is **the way of creating a new user through the front-end currently incompatible with deferred bindings?**

**Comment by LukeTowers** [comment]
If you want to do some additional data processing on the user when they're signing up, then look at the rainlab.user.beforeRegister and rainlab.user.register events; that should be what you need to do what you're trying to.
