### ISSUE TITLE
User activation mode not working

### ISSUE THREAD

**Issue by hoekie** [rainlab/user-plugin#32]
I've set the 'Activation mode' in the backend to 'user' but there is no message on the page after registration and the account activation email is sent with no activation code in the link: 

Hello Richard Hoek,

We need to verify that this is your email address.

Please click the link below to confirm your account:
https://richardhoek.nl/account

Have I missed something?

Thanks for all your hard work!

Richard

**Comment by queiroz** [comment]
Hi @hoekie 

I have tested and the activation code was successfully sent to the email, now regarding the message after registration indicating that the user should follow the instructions on the email provided for registration was not set, however I have just submitted a pull-request [#44](https://github.com/rainlab/user-plugin/pull/44) fixing the issue.

**Comment by hoekie** [comment]
Hi @queiroz 

Thanks for the pull-request!
The reason why there was no activation code in the mail was that I did'nt add :code? to the url. (Duh!)

And thanks for your solution for the flash messages on the frontend!

Richard
