### ISSUE TITLE
Invalid URL: "http://www.."

### ISSUE THREAD

**Issue by micadeyeye** [rainlab/user-plugin#329]
Hello,

Please take a look at the address bar in the attached image.

![text](https://user-images.githubusercontent.com/1431306/39559381-541980c0-4ec8-11e8-8587-b0e03de5f630.png)

All emails point to the wrong website. The URLs in the emails always contain double dots i.e. "**http://www..**TLD". I have checked the entire backend if I entered the wrong URL somewhere at some point but not so. May I add that the /storage/logs/system.log, environment.php and app.php indicate the correct URL i.e. https://www.TLD. How come the contents of the emails get altered?

OctoberCMS build version: 434

**Comment by LukeTowers** [comment]
@micadeyeye take a look at https://github.com/rainlab/user-plugin/blob/master/components/ResetPassword.php#L145 and do some debugging in that method to see why it's generating the wrong URL.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
