### ISSUE TITLE
Activation code supplied is called twice

### ISSUE THREAD

**Issue by jordanplamondon** [rainlab/user-plugin#331]
How : By clicking on the activation link in the email, the Activation code supplied is called twice.
Result : The message "User is already active!" is shown.

```
/*
* Activation code supplied
*/
if (!$this->user() && $code = $this->activationCode()) {
     $this->onActivate($code);
}
```

Changing this in the onRun() method of Account component fix my issue.

**Comment by LukeTowers** [comment]
@jordanplamondon make a PR detailing the issue, reproduction steps, and how your fix works please.

**Comment by Teranode** [comment]
@LukeTowers im not sure how he does his but i put my account component in the layouts section and so the code param is shared with the code param for password reset so when im there i gotta change the param code

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
