### ISSUE TITLE
How to localize exception messages?

### ISSUE THREAD

**Issue by meysammahfouzi** [rainlab/user-plugin#338]
What's the recommended way of localizing exception messages?
```
try {
    $this->account->onSignin();
}
catch(Exception $e) {
    // should I check for the exception message here and throw a new message accordingly? 
    throw new AuthException('exception message in another language');
}
```
I am specifically asking about exceptions that are thrown from `\October\Rain\Auth\Manager`, which are hard coded and and are not available in language files, for example in the `findUserByCredentials` method:

```
if (!$user = $query->first()) {
    throw new AuthException('A user was not found with the given credentials.');
}
```

Any advice would be appreciated!

**Comment by LukeTowers** [comment]
@meysammahfouzi try https://github.com/rainlab/user-plugin/issues/223#issuecomment-303826726
