### ISSUE TITLE
"New User is registered" email is sent to admins without possibility to disable it

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/user-plugin#341]
If the `activation` setting is set to: `administrator` an email is sent to the admin(s) that a new user has been registered. (mailtemplate: `rainlab.user::mail.new_user` ). There is no option in the CMS to disable the sending of this specific email. 

Commenting [Line 66 of the plugin.php file](https://github.com/rainlab/user-plugin/blob/master/Plugin.php#L66) disables this email. It seems that the Notification engine registers a notification rule, without the possibility to disable it.

**Comment by LukeTowers** [comment]
@cptmeatball is there no way to disable it in the notify plugin interface?

**Comment by CptMeatball** [comment]
Unfortunately not. The Notify interface only shows one pre-registered event and that is the "send welcome mail" event.

**Comment by LukeTowers** [comment]
@cptmeatball what changes could be made to improve this?

**Comment by CptMeatball** [comment]
Honestly I'm not even sure what triggers is. I can't seem to find the new_user mail template reference anywhere in the plugin files. 

Might be something with the `Auth` facade?

**Comment by LukeTowers** [comment]
Are you sure it's not a custom notification rule that's been setup for you? There are two preregistered events available for the user plugin in the notify plugin. Are you running the latest versions?

**Comment by CptMeatball** [comment]
I'm sure to the point that the notification rule is not present in the notification settings. Might be worth mentioning that Notify was installed as dependency for User Plus. Will test some things out and see if I can replicate this on a clean install with only User and Notify installed.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
