### ISSUE TITLE
Sending password to user.

### ISSUE THREAD

**Issue by SalocinDotTEN** [rainlab/user-plugin#347]
Hi,

My client's site has a manual user activation (in which the administrator activates the user from the backend). 

After that, an email is sent to the registering front end user with the login information including a generated password which I have managed to do nicely.

I have tried to put the password as a Twig variable like {{ password }} in the email template, but the password does not show up.

However there is another email sent to the administrator on user registration that has the same field and the password does show up.

Is it the built-in limitation of October CMS or is there something that I am missing out on?

Thank you.

**Comment by LukeTowers** [comment]
Please post the code that's generating the message that's supposed to have the password in it (including the part where you pass the password to the user) that is not working as well as the code that is working.

**Comment by SalocinDotTEN** [comment]
Hi @LukeTowers ,

Thanks for following up.

I have managed to resolve the issue by using the User Profile plugin https://octobercms.com/plugin/esroyo-userprofile and placing the generated password there which is auto deleted upon user activation. The fields that User Profile generates are compatible with the email templates.

The code is actually the email template that is used to send an email to the user upon activation by the admin, and there is no backend PHP code modification.

**Comment by LukeTowers** [comment]
@SalocinDotTEN ah, I see. The only time you (or anything in October) has access to the password in plain text is at registration. Beyond that the password is hashed and salted in the DB with no way for you to access what it is, which is how it should be.
