### ISSUE TITLE
Single Sign On

### ISSUE THREAD

**Issue by yapsr** [rainlab/user-plugin#350]
What would be a feasible solution to obtain a single sign feature on multiple instances of OctoberCMS with the user plugin?

I already have a centralized database with users and sessions. However, how do I manage to login a user on these other instances? Is it possible to share the session-ids?

**Comment by bennothommo** [comment]
This is outside the scope of this plugin. You could look to using something like this plugin instead:
https://octobercms.com/plugin/miniorange-samlsp
