### ISSUE TITLE
Help: How to overide default index in backend Users list.

### ISSUE THREAD

**Issue by roulendz** [rainlab/user-plugin#351]
Need some tips, for overriding index method when generating users list in the backend!
Can anyone give me some hints? 

I need to insert a check/filter to see just specific frontend users, based on Backend permissions.

Thank you, any help would be appreciated.

**Comment by LukeTowers** [comment]
@roulendz You can use the list.extendQuery event: http://octobercms.com/docs/api/backend/list/extendquery

Example as follows:
```php
Event::listen('backend.list.extendQuery', function ($listWidget, $query) {
    if ($listWidget->getController() instanceof \RainLab\User\Controllers\Users) {
        $query->whereIn('id', $listOfIdsAllowedToView);
    }
});
```
