### ISSUE TITLE
Random password length

### ISSUE THREAD

**Issue by obuchmann** [rainlab/user-plugin#353]
https://github.com/rainlab/user-plugin/blob/efa31448a9fadb0fb72fefaccd4c5b179998d451/models/User.php#L421

Why is the generated Random Password only 6 chars long?

**Comment by LukeTowers** [comment]
Feel free to submit a PR to change it to 8 and also add a setting in settings/fields.yaml for changing how long it is.

**Comment by bennothommo** [comment]
Fixed by #354.
