### ISSUE TITLE
Login Redirect

### ISSUE THREAD

**Issue by Moonfizzle** [rainlab/user-plugin#358]
Hi,

I have just taken over a a website and am currently having an issue getting it up and running.

I am having an issue whereby when a user logins they are just automatically redirected back to the login page via a 302 redirect even when all the credentials are correct and the plugin is configured to redirect to an account overview page. 

Any ideas?

**Comment by LukeTowers** [comment]
Could be a session issue with Redirect::intended?

**Comment by Moonfizzle** [comment]
Sorry very new to the platform :)

As in its losing the intended redirect URL used in the return in the below section of account.php?

Redirect::intended($redirectUrl);

**Comment by LukeTowers** [comment]
Correct. Please post your component configuration (i.e. login page) here.

**Comment by Moonfizzle** [comment]
Markup

{% if not user %}

    <div class="row">

        <div class="col-md-12">

            <div class="log-in-form">
            <h3>Account Log-In</h3>
            {% partial account ~ '::signin' %}

            <div class="forgotten-password-container text-center">
            <a href="/forgot-password" class="secondary-button">Forgotten Password?</a>
            </div>

            </div>

            <div class="return-main-website-container">
            <a href="https://www.tribeimpactcapital.com" style="text-decoration: none;"><button class="btn btn-default btn-block btn-pink">Return to our main website</button></a>
            </div>


        </div>

    </div>

<script type="text/javascript">

</script>
{% endif %}

Account Config

Alias: Account
Redirect To: Overview
Activation Code Param: Code
Force Secure: true

**Comment by LukeTowers** [comment]
@Moonfizzle post the contents of the page file itself, from the filesystem.

**Comment by Moonfizzle** [comment]
**Login-Page**

title = "Company Name"
url = "/login"
layout = "pure"
is_hidden = 0
robot_index = "noindex"
robot_follow = "nofollow"

[RainLab\User\Components\Account account]
redirect = "overview"
paramCode = "code"
forceSecure = 1
==
{% if not user %}

    <div class="row">

        <div class="col-md-12">

            <div class="log-in-form">
            <h3>Account Log-In</h3>
            {% partial account ~ '::signin' %}

            <div class="forgotten-password-container text-center">
            <a href="/forgot-password" class="secondary-button">Forgotten Password?</a>
            </div>

            </div>

            <div class="return-main-website-container">
            <a href="https://www.companyname.com" style="text-decoration: none;"><button class="btn btn-default btn-block btn-pink">Return to our main website</button></a>
            </div>


        </div>

    </div>

<script type="text/javascript">

</script>
{% endif %}``

**Comment by LukeTowers** [comment]
@Moonfizzle yes

**Comment by Moonfizzle** [comment]
**Signin.htm**

{{ form_ajax('onSignin') }}
    <div class="form-group">
        <label for="userSigninLogin">{{ loginAttributeLabel }}</label>
        <input
            name="login"
            type="text"
            class="form-control"
            id="userSigninLogin"
            autocomplete="off"
            placeholder="Enter your {{ loginAttributeLabel|lower }}" />
    </div>

    <div class="form-group">
        <label for="userSigninPassword">Password</label>
        <input
            name="password"
            type="password"
            class="form-control"
            id="userSigninPassword"
            autocomplete="off"
            placeholder="Enter your password" />
    </div>

    <button type="submit" class="btn btn-default">Sign in</button>
{{ form_close() }}

**Comment by Moonfizzle** [comment]
**account.php**

<?php namespace RainLab\User\Components;

use Lang;
use Auth;
use Mail;
use Event;
use Flash;
use Input;
use Request;
use Redirect;
use Validator;
use ValidationException;
use ApplicationException;
use Cms\Classes\Page;
use Cms\Classes\ComponentBase;
use RainLab\User\Models\Settings as UserSettings;
use Exception;

class Account extends ComponentBase
{
    public function componentDetails()
    {
        return [
            'name'        => 'rainlab.user::lang.account.account',
            'description' => 'rainlab.user::lang.account.account_desc'
        ];
    }

    public function defineProperties()
    {
        return [
            'redirect' => [
                'title'       => 'rainlab.user::lang.account.redirect_to',
                'description' => 'rainlab.user::lang.account.redirect_to_desc',
                'type'        => 'dropdown',
                'default'     => ''
            ],
            'paramCode' => [
                'title'       => 'rainlab.user::lang.account.code_param',
                'description' => 'rainlab.user::lang.account.code_param_desc',
                'type'        => 'string',
                'default'     => 'code'
            ],
            'forceSecure' => [
                'title'       => 'Force secure protocol',
                'description' => 'Always redirect the URL with the HTTPS schema.',
                'type'        => 'checkbox',
                'default'     => 0
            ],
        ];
    }

    public function getRedirectOptions()
    {
        return [''=>'- none -'] + Page::sortBy('baseFileName')->lists('baseFileName', 'baseFileName');
    }

    /**
     * Executed when this component is bound to a page or layout.
     */
    public function onRun()
    {
        /*
         * Redirect to HTTPS checker
         */
        if ($redirect = $this->redirectForceSecure()) {
            return $redirect;
        }

        /*
         * Activation code supplied
         */
        $routeParameter = $this->property('paramCode');

        if ($activationCode = $this->param($routeParameter)) {
            $this->onActivate($activationCode);
        }

        $this->page['user'] = $this->user();
        $this->page['loginAttribute'] = $this->loginAttribute();
        $this->page['loginAttributeLabel'] = $this->loginAttributeLabel();
    }

    /**
     * Returns the logged in user, if available
     */
    public function user()
    {
        if (!Auth::check()) {
            return null;
        }

        return Auth::getUser();
    }

    /**
     * Returns the login model attribute.
     */
    public function loginAttribute()
    {
        return UserSettings::get('login_attribute', UserSettings::LOGIN_EMAIL);
    }

    /**
     * Returns the login label as a word.
     */
    public function loginAttributeLabel()
    {
        return $this->loginAttribute() == UserSettings::LOGIN_EMAIL
            ? Lang::get('rainlab.user::lang.login.attribute_email')
            : Lang::get('rainlab.user::lang.login.attribute_username');
    }

    /**
     * Sign in the user
     */
    public function onSignin()
    {
        try {
            /*
             * Validate input
             */
            $data = post();
            $rules = [];

            $rules['login'] = $this->loginAttribute() == UserSettings::LOGIN_USERNAME
                ? 'required|between:2,255'
                : 'required|email|between:6,255';

            $rules['password'] = 'required|between:4,255';

            if (!array_key_exists('login', $data)) {
                $data['login'] = post('username', post('email'));
            }

            $validation = Validator::make($data, $rules);
            if ($validation->fails()) {
                throw new ValidationException($validation);
            }

            /*
             * Authenticate user
             */
            $credentials = [
                'login'    => array_get($data, 'login'),
                'password' => array_get($data, 'password')
            ];

            Event::fire('rainlab.user.beforeAuthenticate', [$this, $credentials]);

            $user = Auth::authenticate($credentials, true);

            /*
             * Redirect to the intended page after successful sign in
             */
            $redirectUrl = $this->pageUrl($this->property('redirect'))
                ?: $this->property('redirect');

return Redirect::intended('/my-portfolio');

throw new ValidationException([$user]);
            if ($redirectUrl = input('redirect', $redirectUrl)) {
                return Redirect::intended($redirectUrl);
            }
        }
        catch (Exception $ex) {
            if (Request::ajax()) throw $ex;
            else Flash::error($ex->getMessage());
        }
    }

    /**
     * Register the user
     */
    public function onRegister()
    {
        try {
            if (!UserSettings::get('allow_registration', true)) {
                throw new ApplicationException(Lang::get('rainlab.user::lang.account.registration_disabled'));
            }

            /*
             * Validate input
             */
            $data = post();

            if (!array_key_exists('password_confirmation', $data)) {
                $data['password_confirmation'] = post('password');
            }

            $rules = [
                'email'    => 'required|email|between:6,255',
                'password' => 'required|between:4,255|confirmed'
            ];

            if ($this->loginAttribute() == UserSettings::LOGIN_USERNAME) {
                $rules['username'] = 'required|between:2,255';
            }

            $validation = Validator::make($data, $rules);
            if ($validation->fails()) {
                throw new ValidationException($validation);
            }

            /*
             * Register user
             */
            $requireActivation = UserSettings::get('require_activation', true);
            $automaticActivation = UserSettings::get('activate_mode') == UserSettings::ACTIVATE_AUTO;
            $userActivation = UserSettings::get('activate_mode') == UserSettings::ACTIVATE_USER;
            $user = Auth::register($data, $automaticActivation);

            /*
             * Activation is by the user, send the email
             */
            if ($userActivation) {
                $this->sendActivationEmail($user);

                Flash::success(Lang::get('rainlab.user::lang.account.activation_email_sent'));
            }

            /*
             * Automatically activated or not required, log the user in
             */
            if ($automaticActivation || !$requireActivation) {
                Auth::login($user);
            }

            /*
             * Redirect to the intended page after successful sign in
             */
            $redirectUrl = $this->pageUrl($this->property('redirect'))
                ?: $this->property('redirect');

            if ($redirectUrl = post('redirect', $redirectUrl)) {
                return Redirect::intended($redirectUrl);
            }

        }
        catch (Exception $ex) {
            if (Request::ajax()) throw $ex;
            else Flash::error($ex->getMessage());
        }
    }

    /**
     * Activate the user
     * @param  string $code Activation code
     */
    public function onActivate($code = null)
    {
        try {
            $code = post('code', $code);

            /*
             * Break up the code parts
             */
            $parts = explode('!', $code);
            if (count($parts) != 2) {
                throw new ValidationException(['code' => Lang::get('rainlab.user::lang.account.invalid_activation_code')]);
            }

            list($userId, $code) = $parts;

            if (!strlen(trim($userId)) || !($user = Auth::findUserById($userId))) {
                throw new ApplicationException(Lang::get('rainlab.user::lang.account.invalid_user'));
            }

            if (!$user->attemptActivation($code)) {
                throw new ValidationException(['code' => Lang::get('rainlab.user::lang.account.invalid_activation_code')]);
            }

            Flash::success(Lang::get('rainlab.user::lang.account.success_activation'));

            /*
             * Sign in the user
             */
            Auth::login($user);

        }
        catch (Exception $ex) {
            if (Request::ajax()) throw $ex;
            else Flash::error($ex->getMessage());
        }
    }

    /**
     * Update the user
     */
    public function onUpdate()
    {
        if (!$user = $this->user()) {
            return;
        }
        /*
        $validationRules = [
            'password' => 'required:create|between:4,255|confirmed',
            'password_confirmation' => 'required_with:password|between:4,255'
        ];
        */
        $validationRules = [
            'password' => 'required:create|between:4,255|confirmed',
            'password_confirmation' => 'required_with:password|between:4,255'
        ];
        
        
        $validation = Validator::make(post(), $validationRules);
        
        if ($validation->fails()) {
            throw new ValidationException($validation);
        }

        $user->update([
            'password'              => post('password'),
            'password_confirmation' => post('password')
        ]);

        /*
         * Password has changed, reauthenticate the user
         */
        if (strlen(post('password'))) {
            Auth::login($user->reload(), true);
        }

        Flash::success(post('flash', Lang::get('rainlab.user::lang.account.success_saved')));

        /*
         * Redirect
         */
        if ($redirect = $this->makeRedirection()) {
            return $redirect;
        }
    }

    /**
     * Deactivate user
     */
    public function onDeactivate()
    {
        if (!$user = $this->user()) {
            return;
        }

        if (!$user->checkHashValue('password', post('password'))) {
            throw new ValidationException(['password' => Lang::get('rainlab.user::lang.account.invalid_deactivation_pass')]);
        }

        $user->delete();
        Auth::logout();

        Flash::success(post('flash', Lang::get('rainlab.user::lang.account.success_deactivation')));

        /*
         * Redirect
         */
        if ($redirect = $this->makeRedirection()) {
            return $redirect;
        }
    }

    /**
     * Trigger a subsequent activation email
     */
    public function onSendActivationEmail()
    {
        try {
            if (!$user = $this->user()) {
                throw new ApplicationException(Lang::get('rainlab.user::lang.account.login_first'));
            }

            if ($user->is_activated) {
                throw new ApplicationException(Lang::get('rainlab.user::lang.account.already_active'));
            }

            Flash::success(Lang::get('rainlab.user::lang.account.activation_email_sent'));

            $this->sendActivationEmail($user);

        }
        catch (Exception $ex) {
            if (Request::ajax()) throw $ex;
            else Flash::error($ex->getMessage());
        }

        /*
         * Redirect
         */
        if ($redirect = $this->makeRedirection()) {
            return $redirect;
        }
    }

    /**
     * Sends the activation email to a user
     * @param  User $user
     * @return void
     */
    protected function sendActivationEmail($user)
    {
        $code = implode('!', [$user->id, $user->getActivationCode()]);
        $link = $this->currentPageUrl([
            $this->property('paramCode') => $code
        ]);

        $data = [
            'name' => $user->name,
            'link' => $link,
            'code' => $code
        ];

        Mail::send('rainlab.user::mail.activate', $data, function($message) use ($user) {
            $message->to($user->email, $user->name);
        });
    }

    /**
     * Redirect to the intended page after successful update, sign in or registration.
     * The URL can come from the "redirect" property or the "redirect" postback value.
     * @return mixed
     */
    protected function makeRedirection()
    {
        $redirectUrl = $this->pageUrl($this->property('redirect'))
            ?: $this->property('redirect');

        if ($redirectUrl = post('redirect', $redirectUrl)) {
            return Redirect::to($redirectUrl);
        }
    }

    /**
     * Checks if the force secure property is enabled and if so
     * returns a redirect object.
     * @return mixed
     */
    protected function redirectForceSecure()
    {
        if (
            Request::secure() ||
            Request::ajax() ||
            !$this->property('forceSecure')
        ) {
            return;
        }

        return Redirect::secure(Request::path());
    }
}

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
