### ISSUE TITLE
flag is_superuser [Question]

### ISSUE THREAD

**Issue by LucasZdv** [rainlab/user-plugin#359]
What is the purpose or use of the flag, is_superuser in users.

I have noticed that in the backend I can not apply this flag to a user.

Can I add it to the user form?

**Comment by bennothommo** [comment]
It was added as part of version 1.1.3 of the User plugin [here](https://github.com/rainlab/user-plugin/commit/db490382ce2414f5ebb73c13544f2bfcac058916), however, it seems to have no purpose at this stage beyond being reserved for future use.

I'd probably recommend against using it in your form in case it does get used in the future - you don't want to inadvertently give users "super admin" access.
