### ISSUE TITLE
Add new groups and add a user to a group

### ISSUE THREAD

**Issue by nostradamnit** [rainlab/user-plugin#360]
Hi,
I'm a bit of a noob here but I'm trying to help someone setting up a site with October. 

We've got the registration setup and working, just not the inclusion in specific groups. Looking at the code, it appears that the plugin only supports 'guest' and 'registered' group. Also, I don't see a method anywhere to add someone to a group (but I could be missing it). 

So my question is, how to add new groups? I see in seed_user_groups_table.php that you add two groups. Should I add another file somewhere it add new groups?

Then, to add a new user to a new group, I don't see anything. I see the onRegister in Account.php but it doesn't do anything with groups. Can I inherit this class and add more functionality? 

Thanks in advance,
Sam

**Comment by bennothommo** [comment]
Groups can be added and assigned to users via the **Users** section in the Backend. The User plugin only provides the framework for users and groups - how you use it is completely up to you. You can extend the plugin to add your own features that may use the groups, for example.
