### ISSUE TITLE
Cannot get past the error of object user_group already exists error

### ISSUE THREAD

**Issue by Tranest8tion** [rainlab/user-plugin#361]
I am new to OctoberCMS and I am trying to use the User plugin, however, whenever I try to install the plugin, I ALWAYS get this error ""SQLSTATE[42S02]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'user_groups'. (SQL: select [user_groups].[id] from [user_groups] inner join [users_groups] on [user_groups].[id] = [users_groups].[user_group_id] where [users_groups].[user_id] is null)" on line 664 of \vendor\laravel\framework\src\Illuminate\Database\Connection.php"

Now even though I get this error, the Users menu appears in the backend, however, if I try to create a group, I get this error: "SQLSTATE[42S02]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'user_groups'. (SQL: select count(*) as aggregate from [user_groups])"

I get this user_group(s) error pretty much ANY time I try to install a plugin, or anything else. This is a clean install, version 443 on MS SQL dB, I have run the CONCAT MS SQL scripts already. I cannot find any info on this.

Any and all assistance is greatly appreciated!

**Comment by Tranest8tion** [comment]
So I just setup the OctoberCMS install on a localhost using MySQL with MAMP, and everything works perfect, so this must be something with the translation to MS SQL I assume? 

Thanks

**Comment by w20k** [comment]
@Tranest8tion, have you tried running: `php artisan october:down` and up, for your MS SQL?

If you have an option, not to use MS SQL for now, I'd stick with that plan.

**Comment by Tranest8tion** [comment]
Thank you so much for the help. The powers that be do not want me spending too much time trying to get this to work with MS SQL, so they have instructed me to use a different framework. Thank you for the help.
