### ISSUE TITLE
impossible to add a field in the database

### ISSUE THREAD

**Issue by simon511000** [rainlab/user-plugin#362]
Hello,
I want to add fields to the plugin, and to do, I look [this tutorial](https://www.youtube.com/watch?v=AomK1eYAq78&t=597s), but I can not add an element to the `user` table : 
![temp](https://user-images.githubusercontent.com/31013205/50546072-f8416480-0c21-11e9-8ef2-8d32e2a93a5f.PNG)

[Here is the source code](
https://autre.simon511000.fr/kod/index.php?share/folder&user=1&sid=XxZ3ugT6)

I want to clarify that I did exactly as in the tutorial.

Thanks

**Comment by LukeTowers** [comment]
```yaml
1.0.2:
    - add_new_fields.php
```
is not the syntax for running migrations. You must have a string element describing the version change as the first element before any of your migrations. See https://octobercms.com/docs/plugin/updates#version-file.

**Comment by simon511000** [comment]
Thank you very much! You are the best :D
