### ISSUE TITLE
Frontend file upload

### ISSUE THREAD

**Issue by frankwhitejr** [rainlab/user-plugin#367]
Hi,

I have extended the plugin to add some new fields which works fine for text fields but I can't make it work with file uploads,

Has anyone done this before and can point me in the right direction?

**Comment by w20k** [comment]
Hi, @frankwhitejr it's better to ask in the Slack to have a faster reply if devs already had this issue should be a matter of minutes to get your answer.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
