### ISSUE TITLE
Wrong Error Message For Passwords

### ISSUE THREAD

**Issue by GinoPane** [rainlab/user-plugin#371]
When creating a new user with wrong password or password confirmation field the message is shown for password reset field for no reason:

![image](https://user-images.githubusercontent.com/3897579/52622566-05e53d80-2ea2-11e9-8736-25d99cbf76a2.png)

**Comment by slowpokefarm** [comment]
Just got the same issue. Are there any news about it?

**Comment by GinoPane** [comment]
Looks like this one was abandoned for a while :) 
I didn't make any research on the issue, but it should be something pretty simple.

**Comment by w20k** [comment]
You could provide a PR to fix this one, should be fairly simple ;)

**Comment by slowpokefarm** [comment]
Ok, I found out that on my side the issue was caused by saving the user in the afterCreate event, which triggered a password confirmation validation. So not a real issue, after all.

**Comment by GinoPane** [comment]
@LukeTowers sorry, but this shouldn't be closed, I opened this issue for vanilla user plugin and he said @slowpokefarm has something project-specific.

**Comment by bennothommo** [comment]
@GinoPane This has been fixed in October CMS core, it will be available when build 458 is released.

**Comment by GinoPane** [comment]
@bennothommo cool, thanks!
