### ISSUE TITLE
Activation link in email without login.

### ISSUE THREAD

**Issue by borjadevelop** [rainlab/user-plugin#374]
Hi, 
I like to do a administrator activation users, with the button activation in email, but i only want that the button activate the user account, but no log in. 

Any idea?

**Comment by w20k** [comment]
@borjadevelop you could create API and generate URL with a sha256 value. Store this value and DB, find it when requested and activate the user.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
