### ISSUE TITLE
Old version in market

### ISSUE THREAD

**Issue by Nai4rus** [rainlab/user-plugin#378]
Latest version from market (1.4.6) does not contain this changes https://github.com/rainlab/user-plugin/commit/815b8819de01599bee71e8666cfa48849ff414e2#diff-d72eca169ee28622b92f6be159fd8105

**Comment by w20k** [comment]
@Nai4rus the new version with your changes wasn't released, yet.
Latest build was done based on this commit:
```Release Auth::register fix
@LukeTowers
LukeTowers committed on 22 May 2018```

**Comment by Nai4rus** [comment]
It is sad. Can I find out when an update is planned? May I help you somehow?

**Comment by w20k** [comment]
@Nai4rus you could make a PR to bump the version. Should be a good start.
Like this one:
https://github.com/rainlab/user-plugin/commit/70bdaf1226749b0dd0e5186b994f134d1a90fd9f

**Comment by Nai4rus** [comment]
I hope I understand you correctly :sweat_smile:
