### ISSUE TITLE
Make email optional

### ISSUE THREAD

**Issue by andredsp** [rainlab/user-plugin#381]
I know that email is currently a required info, and that I can add username as an alternate login, but in my current project I'll certainly need to make the email an optional information.

I'll make a fork with this change, but do you know if there any known caveat for this?

Thank you.

**Comment by bennothommo** [comment]
@andredsp currently the User model requires the email field, so this would need be extended or modified to support the email being optional.

The email is also required for the forgotten password functionality and the email sent out on registration. You would need to make these conditional on whether the email is provided or not.
