### ISSUE TITLE
"User is already active!"  Error - Line 232

### ISSUE THREAD

**Issue by seanthepottingshed** [rainlab/user-plugin#382]
- OctoberCMS Build: `455`
- PHP Version: `7.1.27`
- Database Engine: `mysql`
- Plugins Installed: `RainLab.User`

### Description:

Reactivating a user from the List View throws:

`"User is already active!"`

error on line 232 of `vendor/october/rain/src/Auth/Models/User.php`

### Steps To Reproduce:

- Create User
- Activate User
- Deactivate User
- Activate User

**Comment by DanHarrin** [comment]
Yup I can confirm that this is happening to me as well.

**Comment by bennothommo** [comment]
Fixed as of https://github.com/rainlab/user-plugin/commit/9edc9556b0e14aa1d44072b3f9ecd7a3ef6fb8ab. Will be released shortly in edge updates with v1.5.0 of the User plugin.

**Comment by skynetweb** [comment]
This message is a bit too much for the display 
"User is already active!" on line 232 of /home/xxx/public/vendor/october/rain/src/Auth/Models/User.php how can i get rid of the full path from the message popup

**Comment by bennothommo** [comment]
@skynetweb Do you have `debug` enabled in your config?

**Comment by XIOLog** [comment]
I have the same problem. `Debug` mode is disabled.

**Comment by bennothommo** [comment]
@XIOLog Are you saying the same problem as OP? Or the same issue with the full message being shown on the message popup?
