### ISSUE TITLE
How to make a user's profile page accessible to other users

### ISSUE THREAD

**Issue by Corymillz** [rainlab/user-plugin#384]
I know this might not be the right place to post this but I have been going over it for days. Asked on stackoverflow but no working answer yet. 

I created a User Profile that a user can get all his info displayed but I am trying t make one user's profile accessible to other users like when you click on example.com/profile/joe, it takes you to joe's profile. I currently have this on my profile file

````
title = "Profile"
url = "/profile/:id"
layout = "default"
is_hidden = 0

[session]

==
<?php

function onStart(){
	
$id  =  $this->param('id');

}
?>
==
````
this is linked with
````
 <a href="{{ 'profile'|page ({ id: user.name }) }}"><button style="font-family: arial" class="btn btn-sm btn-light rounded--lg-pill shadow rounded border col-6">View Profile</button></a>
````
for logged in users {{ user.name }} or {{ user.phone }} brings up their details with no issues but how to make one profile page available to other users is the problem.

Things i  have tried include changing my code to this
````
function onStart(){
	
$id  =  $this->param('id');


$this['userprofile'] = Auth::findUserById($id);
````
and my twig template to {{ userprofile.name }} or {{ userprofile.phone }} but that isn't showing up any info at all.  Please how can I get this done?

**Comment by LukeTowers** [comment]
@Corymillz what happens when you debug `{{ dump(userprofile) }}` after doing the method where you populate `$this['userprofile']` with the user record?

**Comment by Corymillz** [comment]
@lukeTowers it displays ```Object Variables NULL```

**Comment by LukeTowers** [comment]
@Corymillz how about if you do `\RainLab\User\Models\User::findOrFail($id);` instead?

**Comment by Corymillz** [comment]
It throws up an error 
> No query results for model [RainLab\User\Models\User] joe

**Comment by LukeTowers** [comment]
@Corymillz what is the id param that you are passing?

**Comment by Corymillz** [comment]
@LukeTowers   
{{ id: user.name }}
<a href="{{ 'profile'|page ({ id: user.name }) }}"><button>View Profile</button></a>

**Comment by Corymillz** [comment]
Actually i just realize this works
function onStart(){
````	
$id  =  $this->param('id');
$this['userprofile'] = Auth::findUserById($id);
````
if i change the id param to ````{{ id: user.id }}```` but want it to work using ````{{ id: user.name }}````

**Comment by LukeTowers** [comment]
@Corymillz Well you can't pass `name` as the `id` and expect it to work. If you wanted to, you could pass the first and last names and lookup the user via that, but you would not have any guarantee that you wouldn't have users with the same first and / or last names. What you could do if you wanted to have nicer URLs is implement the sluggable trait on a user model class that extends the base user model class and manage your users with that class and look them up with the slug property instead as that ensures that each user would have a different URL.

**Comment by Corymillz** [comment]
@lukeTowers Thank you very much.

**Comment by LukeTowers** [comment]
@Corymillz no problem!
