### ISSUE TITLE
Creating User or logging in doesn't work

### ISSUE THREAD

**Issue by emilaner** [rainlab/user-plugin#390]
I've been trying to get the front-end user plugin to work on a server and when installed and added to a page it just seems fine. The textfields are also appearing, but when trying to login or register and clicking 'login' or 'register' the page just reloads and clears out every field. Sadly I am not experienced in webdevelopment or scripting at all, so I have no idea what the issue could be. Running the plugin on a local installation just works fine. Is there a posibility that something in serverconfigurations (I don't know if there is something like that) can cause the plugin to malfunction?

**Comment by bennothommo** [comment]
@emilaner Sounds to me like it is an issue with your cookie or session settings. If the session and/or cookie are unable to be generated or saved upon login, it will appears as though no login or registration occurred.
