### ISSUE TITLE
Not updated_at User model at change UserGroup.

### ISSUE THREAD

**Issue by Dinver** [rainlab/user-plugin#396]
OctoberCMS Build: 455
PHP Version: 7.2-x64
Database Engine: mySQL
Plugins Installed: RainLab.User

At change user gpoup in backend panel, value "updated_at" model User not change.

With this method "updated_at" updated User model.
`$group = UserGroup::where('code', $select_group)->first();
$user->groups()->add($group);
$user->save();`

Is there any way to fix this?

**Comment by bennothommo** [comment]
@Dinver I believe that adding or removing a pivot record like above does not make the original model "dirty", so it would not update the "updated_at" timestamp. You should be able to confirm this by changing the groups of a user as well as changing a field for the user (ie. the email address or username). If you save then, the "updated_at" timestamp should update.

**Comment by Dinver** [comment]
**@Bennothommo** But the model UserGroup is a child model User. When changing only a child model, tracking changes is not possible, due to lack of property updated_at in table users_groups. Model UserGroup need property touches.

**Comment by bennothommo** [comment]
@Dinver You're correct that `UserGroup` is a child model of `User`, however, there's a pivot table called `backend_users_groups` that stores the link between the two, and the data is stored in a "pivot" model.

I presume you are trying to update the timestamp of the user if their group is changed, but this is currently not possible through the code you have provided in your example above. If you add `$user->touch()` to the code, it should work.

**Comment by LukeTowers** [comment]
@bennothommo we could setup https://octobercms.com/docs/database/relations#touching-parent-timestamps on the UserGroup model.

**Comment by daftspunk** [comment]
This is by design to reduce complexity. If this is still a requirement and you need help implementing this logic by extension, feel free to [send us an email](https://octobercms.com/support). Thanks
