### ISSUE TITLE
Cannot redeclare React\Promise\Timer\reject()

### ISSUE THREAD

**Issue by eggY493** [rainlab/user-plugin#398]
I'm getting Cannot redeclare React\Promise\Timer\reject() (previously declared in /var/www/html/vendor/react/promise-timer/src/functions.php:76) after installing user plugin

**Comment by LukeTowers** [comment]
This is not caused by anything to do with this plugin. Remove the plugin and you'll see that you still get it. If you don't then my guess is that you have another plugin that's detecting when this one exists and the problem exists in that one.
