### ISSUE TITLE
Add ability to set user as an admin user

### ISSUE THREAD

**Issue by pyrello** [rainlab/user-plugin#4]
I would like to suggest adding a feature to hook into the core admin user system, so that a user, as provided by this plugin, can also be an admin user, so it is not necessary to define separate user accounts for the front-end and back-end of the site.

Nice work on this system!

**Comment by gavinengel** [comment]
Can a single-table user system can be adopted instead?  A dual backend/frontend user system feels very odd to me.

**Comment by that0n3guy** [comment]
@gavinengel This seemed very odd to me at first too.  I came from Drupal and a user was a user... just different permissions.  I've come to appreciate the difference now though.  Most use cases don't need a mix of the 2.

**Comment by daftspunk** [comment]
octobercms/october#219 describes the reasons.

The user plugin is optional, some websites don't have front-end users. Also it is a security hazard to share the same table for normal and privileged users.

**Comment by gavinengel** [comment]
Yeah, I still think this is bizarre.  Advice, don't include this extra junk and focus on truly getting back to basics.
