### ISSUE TITLE
Redirect after impersonate

### ISSUE THREAD

**Issue by rubenvanerk** [rainlab/user-plugin#400]
I would like to redirect the backend user to the frontend after succesfully impersonating a user. Is this currently possible by extending the plugin?

Or could an event be fired after succesfully impersonating a user?

**Comment by bennothommo** [comment]
@rubenvanerk As far as I can tell, there is an event fired on the `User` model when impersonation is taking place - `model.auth.beforeImpersonate`, however, this happens before the impersonation is actually stored in the session, so you could latch to that event, but you would have to activate and store the impersonation manually.

**Comment by rubenvanerk** [comment]
That's an option, but it's not ideal.
Would it be okay if I added a new event fire through a pull request?

**Comment by bennothommo** [comment]
@rubenvanerk By all means - however, you would likely want to make the change in the October Rain library here: https://github.com/octobercms/library/blob/4bda08c826fc3ac1efba32fa8799d25ced14191f/src/Auth/Manager.php#L692

**Comment by rubenvanerk** [comment]
Will do, thanks!

**Comment by LukeTowers** [comment]
@rubenvanerk 
```php
\RainLab\User\Controllers\Users::extend(function ($controller) {
    $controller->bindEvent('ajax.beforeRunHandler', function ($handler) use ($controller) {
        if ($handler === 'onImpersonateUser') {
            // Process the impersonation
            $controller->preview_onImpersonateUser();
            // Redirect to the frontend
            return redirect('/');
        }
    });
});

**Comment by rubenvanerk** [comment]
@LukeTowers Thanks for the solution!

`$controller->preview_onImpersonateUser();` needs the record id as a parameter. I used `Request::segment(6)` to get this id. Is there a better way to do this?

**Comment by LukeTowers** [comment]
@rubenvanerk I think you can do `Backend\Classes\BackendController::$params` to get the action parameters as an array: https://github.com/octobercms/october/blob/master/modules/backend/classes/Controller.php#L135

**Comment by rubenvanerk** [comment]
Looks good, thanks!
