### ISSUE TITLE
Provide frontend translations ?

### ISSUE THREAD

**Issue by aurelien-roy** [rainlab/user-plugin#402]
I know that frontend translations are normally defined in the theme files (with the Translate plugin), however I think translating the different frontend forms and mails is something that many october users will do when starting a new project, and it is time consuming.

It would be great and reaaally time-saving to have a localized user plugin "out of the box" (just like the backend is).

Couldn't backend translation system be used as well for frontend localization ? (Backend translations can be accessed in frontend with the |trans Twig function)

Alternatively, the Translate plugin could be refactored to support frontend localizations provided by plugins and overridable by themes).

**Comment by aurelien-roy** [comment]
So, [here is an example](https://github.com/aurelien-roy/user-plugin/commit/47cff8cc6e1b439f96d4f1216cc9e59bbb8ff969) with a partial on what it may looks like.

What's great here is : 
- most labels already have a translation available (I only had to add translation for input placeholders)
- ajax error messages were already translated

What's less great : 
- Repeating the plugin name is verbose... but it's already what is done in the component file for ajax messages localization. So I guess we'll keep  it that way ?
- Another solution would be to add "rainlab.user::lang." as a constant in every component file (thought initially to add it in the Plugin.php file, but I can't find a way to access it from the twig template)

What do you think @LukeTowers  ?

**Comment by LukeTowers** [comment]
twig comment sounds good to me. Only other request is space before and after pipe character: `'string' | trans`

**Comment by alxy** [comment]
Wouldn't it make sense to source these translation out to a separate lang file, like `lang/xx/frontend.php`? First of all, that would be easier to override if necessary (otherwise one would manually need to look for the language keys) and on the other hand for users that only need the backend translated, they will have an easier job when there are fewer strings to translate (if they were to add a new language version).

**Comment by aurelien-roy** [comment]
Thought that initially, but it seems there are many translations in common between front and backend. So how do you deal with that ? Either you will end up with a lot of duplicated strings in frontend.php and lang.php, or you'll have templates with a mix of frontented/backend translation keys.

**Comment by alxy** [comment]
Yeah, you will certainly have duplicates. But frontend strings are far more likely to be customized, as it is the one the client sees. From my experiences, backend administrators do not care too much about wordings...

**Comment by LukeTowers** [comment]
@alxy if `backend administrators do not care too much about wordings...` is the case then I don't see any problem with having the backend's translations change along with the frontend's whenever people customize them.

**Comment by alxy** [comment]
@LukeTowers Yeah, this is not the problem. The situation is I want to change the translation for signup form in German. Now, what I need to do is look up all the strings in the (large) language file to find the ones I want to change (and they are not even concentrated at a single location, but all over the file, as we reuse some strings on multiple locations). If we had a separate file, I would just take this and its obvious that I need to change exactly these values (or leave them as is).

**Comment by LukeTowers** [comment]
@alxy I'm not too concerned about that particular use case because what you could do instead is just look at the twig file for the view that you want to translate and pull the keys out of that instead, which is what I would probably be doing in the first place.

**Comment by aurelien-roy** [comment]
Is this "mess" acceptable ? (for lack of a better solution)
<img width="970" alt="Capture d’écran 2019-10-25 à 16 20 23" src="https://user-images.githubusercontent.com/1875998/67578798-7dfb4700-f743-11e9-9bb9-e900a72305a3.png">
<img width="964" alt="Capture d’écran 2019-10-25 à 16 20 09" src="https://user-images.githubusercontent.com/1875998/67578799-7dfb4700-f743-11e9-918a-cb07f3030035.png">

**Comment by LukeTowers** [comment]
@aurelien-roy what are we looking at exactly?

**Comment by aurelien-roy** [comment]
@LukeTowers Sorry ^^ I should have explain my thought:

So, I enabled localization for mail templates. Problem is after that, the mail template editor in the backend do not look really clean anymore (for instance, on the first screenshot, the subject column is barely readable because of the Twig markup introduced by localization).
My question was : is it okay to keep it "as is". As I don't see any other solution that wouldn't require some edits in october core, my question is: it is okay to keep it as is?

**Comment by LukeTowers** [comment]
@aurelien-roy I don't think it makes sense to provide translations to the mail templates out of the box. I believe the translate plugin provides support for translating mail messages, so if a developer needs that they can just use the translate plugin instead.

**Comment by aurelien-roy** [comment]
Well technically the Translate plugin could also be used with "standard" partials. I'm not sure to get what is different with mail templates^^ (Though, I agree, mail templates are more likely to be changed anyway that other templates from the user plugin. Maybe is it your point?)

My point is that once the translation for one language has been made, it could be re-used with 0-cost for every other developper that need to support that language.

**Comment by LukeTowers** [comment]
My main issue with the translating of the mail templates in this manner is that it over complicates the user interface for seemingly little benefit.

**Comment by daftspunk** [comment]
This is by design, we want the source templates to be in English without complex translation keys getting in the way of learning the system itself.

Translation of emails should be similar to how content files are translated. You should have a single template for each language, detect the users language and send them a template in that language. Rather than trying to translate the template itself.

Ultimately the system has no opinion on how you approach this and we want to keep it that way.

**Comment by daftspunk** [comment]
As a heads up, a ticket has been created for this proposed mail approach: https://github.com/rainlab/translate-plugin/issues/533

Translating mail template content itself will create problems when queuing the mail message. The server that processes the queue will lose the context of the user's locale preference. Sending a different, specific template for that language resolves this problem
