### ISSUE TITLE
Password length requirements

### ISSUE THREAD

**Issue by Dreanad** [rainlab/user-plugin#407]
Hello there,  

i have a problem with password length requirements, i have set it for test " 2 " in backend, and the system not working as expected, continue to ask for 8 characters .

its a fresh install of octobercms with the user plugin
![octoberuser2](https://user-images.githubusercontent.com/12476942/65955661-edce2880-e448-11e9-9fa8-96484c809635.jpg)

![octoberuser1](https://user-images.githubusercontent.com/12476942/65955629-dabb5880-e448-11e9-97ab-42a237c03a52.jpg)

i have miss something ? 
Thank you

**Comment by bennothommo** [comment]
@Dreanad what was it that you had missed? It might be worthwhile info for people who have the same issue in the future. :)

**Comment by Dreanad** [comment]
oh ... its idiot, i'm on localhost and on distant, with automatic upload, but this data is stored locally ! so automatic upload is useless ..

**Comment by bennothommo** [comment]
@Dreanad fair enough :)
