### ISSUE TITLE
Validation error: "The password confirmation does not match."

### ISSUE THREAD

**Issue by alessiovietri** [rainlab/user-plugin#409]
OctoberCMS Build: 458
PHP Version: 7.2.11-x64
Database Engine: MySQL
Plugins Installed: RainLab.User

Hi everyone,
I just updated my instance, and now, when I try to seed users (as I always managed to do before today), I get this error:

    [October\Rain\Database\ModelException]
    The password confirmation does not match.

I'm reading rows from a CSV to import the users, this is the way I seed them:

    $newUser = new User;
    $newUser->name = $data[1];  
    $newUser->email = $data[3];  
    $password = 'password';  
    $newUser->password = $password;  
    $newUser->password_confirmation = $password;  
    $newUser->is_activated = true;  
    $newUser->is_guest = false;  
    $newUser->is_superuser = false;  
    $newUser->save();

Do you know how to solve this problem?
Thanks in advance!

**Comment by bennothommo** [comment]
@al3xtig3r I'm able to use the same code you have provided above without issue - the new user is saved successfully. Is that the exact code you are using, or are you applying some different functionality in your case, ie. changing the password for each user?

Would you be able to investigate whether you have any other plugins relating to users? Would you also be able to provide us with your configuration in the "User Settings" section of the Settings area in the backend?

**Comment by al3xtig3r** [comment]
This is the exact code I'm using, but probably this error depends on another block of code: I extended the User plugin to add some info and now, whenever I add a user, the system creates an instance of another model called Profile. The code for doing this is the following:

    Event::listen('eloquent.created: RainLab\User\Models\User', function($user){
        $slugLimit = 64;
        
        $user->name = substr($user->name, 0, $slugLimit);
        $user->save();
        
        // *** Other operations ***
    });

Could this be the problem? I executed this block many times before getting the error, I don't know what changed. Anyway, this block should be executed after inserting the user into the DB, shouldn't it? So, the password should already be stored into the DB.

Thanks in advance for your reply!

**Comment by LukeTowers** [comment]
@al3xtig3r try listing to the October event instead:
```php
\RainLab\User\Models\User::extend(function ($model) {
    $model->bindEvent('model.afterCreate', function () use ($model) {
        $model->name = substr($user->name, 0, 64);
        $model->save();
    });
});
```

**Comment by al3xtig3r** [comment]
@LukeTowers I tried this way, but nothing changed. Anyway, now I'm sure that the problem is this block, because I executed the seeder again, changing the `forceSave()` calls back to `save()` inside it and it worked, but inside the event binding I have to use `forceSave()`, or it throws the exception.

In addition to this test, I tried to sign in and everything worked as usually, the password is correctly stored into the DB as before. The only problem is this check when I save the user again inside the event binding block

**Comment by LukeTowers** [comment]
@al3xtig3r random guess here, but did you try to set `$model->exists = true` at the start of the `afterCreate` listener?

**Comment by al3xtig3r** [comment]
@LukeTowers no, I didn't, but I tried now and it didn't work (even if I thought it would have done it). Anyway, `$model->forceSave()` makes it work, but I thought it would have been better to post my problem here, since it used to work before the last update.

Thanks a lot for your help, in any case, I'll keep trying by myself to find the reason why this doesn't work. If any other solutions comes to your mind, I'll appreciate, but I "forced" it to work easily.

**Comment by bennothommo** [comment]
@al3xtig3r If you can provide a complete working copy of (I presume) the plugin you are using to seed the users and manipulate them post-save, and post the steps you are taking as well, we can also do some more investigating for you.

**Comment by al3xtig3r** [comment]
@bennothommo yes, of course. This is the seeder:

    use Seeder;
    
    use DB;
    use Faker;
    use Log;
    
    use RainLab\User\Models\User;
    
    class SeedUsers extends Seeder
    {
        public function run()
        {
            DB::table('users')->where('id', '<>', null)->delete();
    
            $usersNumber = 8;
            $faker = Faker\Factory::create();
    
            for($i = 0; $i < $usersNumber; $i++){
                $newUser = new User;
                $newUser->name = $faker->name();
                $newUser->email = $faker->email();
                $password = $faker->realText(255, 1);
                $newUser->password = $newUser->password_confirmation = $password;
                $newUser->is_activated = true;
                $newUser->is_guest = false;
                $newUser->is_superuser = false;
                $newUser->save();
    
                $newUser->profile->type = 'user';
                $newUser->profile->save();
                $newUser->save();
            }
        }
    }

And this is Plugin's boot function:

    public function boot()
    {
        // Extending RainLab\User plugin
        UserModel::extend(function ($model) {
            $model->hasOne['profile'] = Profile::class;
            $model->hasMany['ads'] = Ad::class;

            $model->bindEvent('model.afterCreate', function () use ($model) {
                $slugLimit = 64;

                $model->exists = true;
                $model->name = substr($model->name, 0, $slugLimit);
                $model->save();             // This is the line that throws the error

                $profile = new Profile;
                $profile->user = $model;
                $newSlug = substr(str_slug($model->name), 0, $slugLimit);
                $existingProfile = Profile::where('slug', $newSlug)->first();
                $add = 0;
                while($existingProfile){
                    $add++;
                    $complete = $newSlug.'.'.strval($add);
                    if(strlen($complete) <= $slugLimit)
                        $newSlug = $complete;
                    else
                        $newSlug = substr($newSlug, 0, strlen($newSlug) - (strlen($complete) - $slugLimit)).'.'.$add;
                    $existingProfile = Profile::where('slug', $newSlug)->first();
                }
                $profile->slug = $newSlug;
                $profile->save();
            });
        });

        UsersController::extendFormFields(function($form, $model, $context){
            if(!$model instanceof UserModel || !$model->exists)
                return;

            $form->addTabFields([
                'profile[slug]' => [
                    'label' => 'Slug',
                    'tab' => 'Profile'
                ],
                'profile[phone]' => [
                    'label' => 'Phone',
                    'tab' => 'Profile'
                ]
            ]);
        });
    }

**Comment by al3xtig3r** [comment]
Any news?

**Comment by mjauvin** [comment]
Why not use the model.beforeCreate instead?

**Comment by LukeTowers** [comment]
@mjauvin to ensure that the model was successfully created before creating related records for it.

**Comment by tschortsch** [comment]
It seems I run into the exact same problem since I updated my page from `458` to `469`. I seed some demo users by running the following command:

```
User::create([
    'login' => 'demouser',
    'email' => 'demo@user.com',
    'first_name' => 'Demo',
    'last_name' => 'User',
    'password' => 'demouser',
    'password_confirmation' => 'demouser',
    'is_superuser' => false,
    'role' => $userrole // This role gets created above with UserRole::create()
]);
```

I also extended the User model in my plugin but the user creation also fails when I completely remove this code.

**Comment by LukeTowers** [comment]
@bennothommo this may be related to https://github.com/octobercms/october/issues/5313

**Comment by bhargavy** [comment]
Any update on this. I'm getting the same error on a live site.
Users are unable to change their password.

**Comment by LukeTowers** [comment]
@bhargavy what version of October are you using? What plugins and their versions do you have installed? How did you install october (web installer or composer)?
