### ISSUE TITLE
Avatar change onUpdate isn't working.

### ISSUE THREAD

**Issue by naaidu** [rainlab/user-plugin#410]
public function onUpdate()
    {
        if (!$user = $this->user()) {
            return;
        }

        if (Input::hasFile('avatar')) {
            $user->avatar = Input::file('avatar');
        }

        $user->fill(post());
        $user->save();
.....

this is part of the plugins>rainlab>user>components>Account.php

As per my understanding, we can add image and change the current user avatar.

Thus, I added this code in my update form
`    <div class="form-group">
      <input type="file" class="form-control-file" name="avatar" id="avatar" aria-describedby="fileHelp">
      <small id="fileHelp" class="form-text text-muted">Please upload a valid image file. Size of image should not be more than 2MB.</small>
    </div>`

However, instead of changing the avatar. I'm updating the user name with doubling their last name. Something is wrong....any help is much appreciated .

**Comment by daftspunk** [comment]
The code presented looks fine. If you still need help with this, feel free to send us an email via the appropriate support channels: https://octobercms.com/support
