### ISSUE TITLE
Conflict with Guest group and "is_guest" column

### ISSUE THREAD

**Issue by drmzio** [rainlab/user-plugin#411]
I spent a few hours trying to figure out why my backend was displaying a user as "Guest" even when I had already "Registered" that user. Here's what went down:

**Problem 1**: Creating a guest user sets both `is_guest` to `true` and assigns the user to the "Guest" user group. By having both, this will inevitably cause problems down the road. See problem 2.

https://github.com/rainlab/user-plugin/blob/bed2661ca4164fa21500d491b5ac0f9ebfed4b6f/classes/AuthManager.php#L69-L99

**Problem 2**: The `findGuestUser()` only checks for the `is_guest` column but not the "Guest" user group.

https://github.com/rainlab/user-plugin/blob/bed2661ca4164fa21500d491b5ac0f9ebfed4b6f/classes/AuthManager.php#L59-L67

**Problem 3**: When it comes time to converting a "Guest" user to a "Registered" user, the `convertToRegistered()` only checks the `is_guest` column and completely ignores the "Guest" user group. Thus, keeping that user a "Guest" even though the `is_guest` was set to `false`. (Already out of sync) The backend continues to show the user as "Guest"

https://github.com/rainlab/user-plugin/blob/bed2661ca4164fa21500d491b5ac0f9ebfed4b6f/models/User.php#L101-L122

**Problem 4**: The `convertGuestToUser()` isn't documented and is confusing at first. Isn't this method basically the same as the `convertToRegistered()` method? Except this method actually removes the user from the "Guest" user group. Also, what exactly should we pass to the `credentials` argument?? Email and password? Only email? I'm already passing the `User` model as the first argument... I just want to convert the "Guest" user to a "Registered" user. Why is this so hard?

https://github.com/rainlab/user-plugin/blob/bed2661ca4164fa21500d491b5ac0f9ebfed4b6f/classes/AuthManager.php#L101-L129

**Question:** Why is there both a "Guest" user group and `is_guest` column? Wouldn't it be more convenient if we left one or the other? Personally, I like the user_group side of things rather than the `is_guest` column. I suspect that this has something to do with backwards compatibility?

**Comment by bennothommo** [comment]
@drmzio Thanks for the detailed notes, and I believe you're right, `is_guest` is there for backwards compatibility, but the Guest group is more important for tracking users. It's possible though that people may remove the Guest group, or rename it to another group, so it's not always available.

Would you mind providing a PR that adds the removal of the users from the guest group to the `convertToRegistered` method, so that is at least maintains parity with the functionality of the `convertGuestToUser` method?

**Comment by drmzio** [comment]
@bennothommo Yes I'll create a PR for this. 👍

**Comment by bennothommo** [comment]
@drmzio Hold up, it looks like `convertGuestToUser` actually calls `convertToRegistered` anyway, so you may not need to do this. Are you using `convertToRegistered` directly?

**Comment by drmzio** [comment]
@bennothommo Yes I'm using `convertToRegistered` directly on the User model.

**Comment by drmzio** [comment]
Ok so I guess I could live by using `Auth::convertGuestToUser` but that still leaves out the fact that `convertToRegistered` only modifies the `is_guest` column on the User, but not the "Guest" user group.

![](https://cl.ly/c19c4c4cae77/Image%2525202019-10-31%252520at%2525201.41.46%252520PM.png)

I think it would make more sense to move this:
```php
// Remove user from guest group 
if ($group = UserGroupModel::getGuestGroup()) { 
    $user->groups()->remove($group); 
} 
```
...to the `convertToRegistered` method. What do you think?

**Comment by LukeTowers** [comment]
What is convertGuestToUser doing that convertToRegistered isn't?

**Comment by bennothommo** [comment]
@drmzio @LukeTowers I can see why @daftspunk set it up that way. The `convertToRegistered` method is basically a setter for the `User` model, and only makes changes to the `User` model data itself. By convention, models shouldn't really be affecting other model data, so he's instead made the method `convertGuestToUser` in the `AuthManager` to run this setter and also manipulate the user group linking.

I think his intention is that you should really be using the `Auth::convertGuestToUser()` method exclusively.

**Comment by drmzio** [comment]
@bennothommo Oh I see. This makes perfect sense. Maybe we should add `Auth::convertGuestToUser()` to the documentation in place of `$user->convertToRegistered()`?

![](https://cl.ly/cbaf08894184/Image%2525202019-11-01%252520at%25252012.43.34%252520PM.png)

**Comment by LukeTowers** [comment]
@drmzio I'm fine with that. Does the parameter to disable notification & password reset still work with the `Auth::convertToRegistered()`?

**Comment by drmzio** [comment]
@LukeTowers It seems like it is disabled
