### ISSUE TITLE
Unreachable code authenticating banned users

### ISSUE THREAD

**Issue by scottbedard** [rainlab/user-plugin#413]
Hi, I'm working on a new HTTP API for this plugin, and I think I've found some unreachable code.

https://github.com/rainlab/user-plugin/blob/master/components/Account.php#L240-L244

The `authenticate` method will throw the following exception if the user is banned.

https://github.com/octobercms/library/blob/master/src/Auth/Models/Throttle.php#L188-L192

With regard to this plugin (and mine), would it be better for us to check if the user is banned before trying to authenticate them? If not, I think we can remove this code.

**Comment by bennothommo** [comment]
@scottbedard I don't believe it's always unreachable - the throttle can be disabled per the settings in the User Settings area.

**Comment by scottbedard** [comment]
@bennothommo Yup, you are correct! Sorry for wasting your time, [setting this value to `false`](https://github.com/scottbedard/rainlab-user-api/commit/28be3251ae78abc8638fd0c9ae024025efd15de6#diff-cbb28e277e303984b4f442e3a21249f4R70) was all I needed.
