### ISSUE TITLE
Automatic logout function doesn't works

### ISSUE THREAD

**Issue by faselunare** [rainlab/user-plugin#415]
When login in my website leaving the 'Stay logged in' checkbox unchecked,
I expect the session to close when I close the browser and ask me to login again to the next visit. instead, the user is always logged.

**Comment by LukeTowers** [comment]
@faselunare check your settings for the plugin, by default the remember mode is Always remember, but you can change it to "Ask" and then it should do what you're wanting.

Additionally, if you want sessions to expire on browser close, then you need to set `session.expire_on_close` to true, and even then some browsers may not respect that under some conditions. See https://stackoverflow.com/questions/25114267/laravel-auth-session-not-expiring-after-browser-close
