### ISSUE TITLE
Echo list of users on webpage - Rainlab User Plugin

### ISSUE THREAD

**Issue by Evelienrip** [rainlab/user-plugin#417]
Hello, 

I am new to October CMS. I am using the Rainlab User Plugin on my website.  I have succeeded to activate the plugin and made a  list of users in the database. 

Now I like to make a loop. When there is a user I want to echo the name of this user.

I have written the following php code. But the name of the user does not load. What am I doing wrong? 

<?php
use October\Rain\Auth\Models\User;

$row =['user'];
$name = ['name'];

while ($row) {    // Keep driving ...   
     echo $name; 
    
} 

?>

**Comment by nizzac** [comment]
You didn't show us your code @Evelienrip

**Comment by nizzac** [comment]
// First of all get the users
$users = \Rainlab\User\Models\User::all();

// You can loop them with good ol' PHP foreach loop
// https://www.php.net/manual/en/control-structures.foreach.php

foreach ($user as $user) {
    echo $user->name . ' ' . $user->surname;
}

// Or using the Collections each() method 
// https://laravel.com/docs/5.5/collections#method-each

$users->each(function($user, $key) {
    echo $user->name . ' ' . $user->surname;
});

**Comment by mjauvin** [comment]
// foreach ($users as $user) {

**Comment by ninobang** [comment]
@Evelinerip
I am doing the same thing at the moment like this:
on the page I add a little php code,

`==
<?php
use October\Rain\Auth\Models\User;

function onInit() {
    $this['activatedUsers'] = User::whereIsActivated(true)->get();

}
==
{% for user in activatedUsers %}
          {{ user.name }} {{ user.surname}}<br/>
{% endfor %}`
