### ISSUE TITLE
Avatar in public User list

### ISSUE THREAD

**Issue by ninobang** [rainlab/user-plugin#419]
hello october community,
so i installed october cms with the user plugin.
i followed watch an learn and managed to extend the userplugin
(https://www.youtube.com/watch?v=AomK1eYAq78)

i even managed to do a frontend image upload for the avatar when a user registers
and the user can change it once the user has been activated.  
so now i have a few users and i want to have a page where i can list them.

so i am doing this in the code section of the actual page:

```
use October\Rain\Auth\Models\User;

function onInit() {
    $this['activatedUsers'] = User::whereIsActivated(true)->get();
}
```

this gives me all the activated users. works like a charm. but how do i get the avatar?
in my template i can do this now:

```
{% for user in activatedUsers %}
    {{ user.name }} {{ user.surname}}
{% endfor %}
```

all of this workes like a charm, but when i try to get the avatar with:
`{{ user.avatar }}`

it returnes null. the images are ale in the system_files table where they are supposed to be.
but i can't reach them? can anybody help?

**Comment by bennothommo** [comment]
@ninobang I think you are using the wrong class at the top. Instead of `October\Rain\Auth\Models\User`, you would likely want to use `RainLab\User\Models\User`.

**Comment by ninobang** [comment]
@bennothommo 
thanks man, it works like a charm! i knew i was missing something really basic! :)
