### ISSUE TITLE
Error "Undefined index: password" when updating the profile.

### ISSUE THREAD

**Issue by triasrahman** [rainlab/user-plugin#421]
On `Account` component, there is a new logic to get `password` index. It causes a problem when my page is only a feature to update the profile details (name, phone, etc.)

![image](https://user-images.githubusercontent.com/7110859/72136031-72223700-33ba-11ea-9441-37157ae377b2.png)

To prevent this, the logic should check the `password` index first before getting it or using `array_get()` function.

**Comment by bennothommo** [comment]
This is fixed by #420 and will be available in version 1.5.3 of the User plugin.
