### ISSUE TITLE
is_activated doesn't necessarily mean that the email is verified

### ISSUE THREAD

**Issue by aurelien-roy** [rainlab/user-plugin#426]
### Problem
Users can change their e-mail and have their account is still marked "activated" Here is how:

1. User creates an account with a first mail address
2. User activates its account, via the link sent to its e-mail. The account is now activated.
3. User then changes its e-mail address (note that it is possible even if the website do not allow e-mail change via its account update form, because the onUpdate AJAX endpoint is exposed and allows the user change almost every property from a POST request)
4. The user now has a new e-mail, but the account is still marked as activated.

### Why this is an issue

This is harmless for most websites, where the main purpose of activation is just to make sure that user didn't made a typo in its address. But a secondary usage of activation is to have a guarantee (from a security perspective) that user is the owner of the e-mail address he gave.

I myself got tricked while developing a authentification plugin on top of RainLab User, because I assumed that every activated account are associated with a verified e-mail (which I think is a reasonable assumption). I find it's counterintuitive that it's not, and could both mislead website owners and create potential security flaws.

### Possible solutions

Now, I am willing to make a PR that solves this issue. But I see 3 possible solutions, and wanted to discuss what would be the best:

**Solution 1:** De-activate the account when e-mail is changed by setting NULL the "activated_at" and "is_activated" fields when e-mail is changed. If activation is required to log in into the website, user is logged out until they activate their account again. A new activation mail will be sent to the user to the new e-mail he has provided.

**Solution 2:** Have two fields in the user model: email and unverifiedEmail. When the user changes its e-mail via the onUpdate field, only the "unverifiedEmail" field is changed and a new activation link will be sent. Clicking on this link will set the email field equals to unverifiedEmail. In this solution, user account is never de-activated, however, this solution will guarantee that "email" field always contain a verified e-mail address.

**Solution 3:** Secure the onUpdate endpoint to deny e-mail change by default. The way that could be used is to add a property to the Account component listing every overridable fields. Let say something like "name,email,phone". When the onUpdate endpoint is called, only those fields will be overwritable. Now this doesn't totally solve the activation issue, but it will secures website that do not expect users to change their e-mail, forcing developers to knowledgly enable e-mail change and then deal with activation handling however they want. Note that solution 3 is a breaking change.

My opinion: I would go for 1 or 2. But I think 3 should be considered as well (in addition to 1 or 2), because it gives control on the field that can and cannot be edited.

**Comment by LukeTowers** [comment]
@aurelien-roy it's worth pointing out that activated != verified for all uses of this plugin. What I would recommend is that you dynamically extend the User model to unset the activated flag when the email changes.

```php
User::extend(function ($model) {
    $model->bindEvent('model.afterSave', function () use ($model) {
        if ($model->getOriginal('email') !== $model->email) {
            $model->is_activated = false;
            $code = implode('!', [$model->id, $model->getActivationCode()]);
            $link = Url::to('path/to/account/component?activate=' . $code);

            $data = [
                'name' => $user->name,
                'link' => $link,
                'code' => $code
            ];

            Mail::send('rainlab.user::mail.activate', $data, function($message) use ($model) {
                $message->to($model->email, $model->name);
            });
        }
    });
});
```

Really the only change I would make to this plugin then would be to the documentation adding a note to developers so that they don't misinterpret the usage of the is_activated parameter and perhaps adding that code block as an example of how to use it in that way (as a verification of their email address)

**Comment by mjauvin** [comment]
@LukeTowers did you forget to save the model in your example, or should the event be "model.beforeSave" ?

**Comment by LukeTowers** [comment]
@mjauvin good catch, forgot to save it.

**Comment by LukeTowers** [comment]
Updated it

**Comment by aurelien-roy** [comment]
I am quite surprised you don't seem to want this addressed, it seems quite important to me, but I may be wrong.
You wouldn't want even this added as an optional feature?

Also what about the onUpdate handler which is very permissive and allow almost every field in the model to be changed by the user (including created_ip_address and last_ip_address !) ?

**Comment by mjauvin** [comment]
Can you show an example of how the onUpdate handler can be abused and how you think this should be addressed?

**Comment by LukeTowers** [comment]
@aurelien-roy while I agree this is a bit of a potential foot-gun for some developers, and would be worthy of a mention in the documentation, it's also part of the overall flexibility of the plugin by default in that developers are free to add in whatever fields they want in the DB and then manage them from a customized account update partial.

What would this look like in terms of an optional feature?

**Comment by bennothommo** [comment]
@aurelien-roy From a security standpoint, this is not really a concern. The only user that can be edited via the `onUpdate` endpoint is the currently logged in user, and if they change their email address to one they cannot access, the only person who will be inconvenienced will be themselves.

If you could update *another* user from the endpoint, then that would be a whole another story.

**Comment by aurelien-roy** [comment]
> What would this look like in terms of an optional feature?

For the activation, I would just see a toggle setting: "Require user to re-activate account on e-mail change", with an implementation similar to what you described earlier.

> Can you show an example of how the onUpdate handler can be abused and how you think this should be addressed?

While I understand the onUpdate handler is mostly harmless and case of abuse are rare and depend from project to project, I would add a property to Account component to easily restrict fields that could be edited (just for developers to have this flexibility without the need to make a plugin on top of this). But keeping it optional and non-breaking so that if the property is not set, the handler works the same way it works today.

Something like this:

**Example 1: Field not set = Every change is allowed, like it always has been**

```
[account]
restrict-fields=""
==

<!-- account edit form here -->
```

**Example 2: Field set = Filter the input for only the specified fields in the onUpdate handler**
```
[account]
restrict-fields="name,email,password"
==

<!-- account edit form here -->
```

**Comment by bennothommo** [comment]
@aurelien-roy That makes sense - as long as it is easy for developers to define the restricted fields in the component. Feel free to submit a PR with the changes and we'll review.

**Comment by alexandra-toder** [comment]
Hello, I want to send the email to the new user with credentials after his account is activated, but the password field is empty=>
i get this " $this->getOriginalHashValue('password')->null" It posible to get the password?

**Comment by LukeTowers** [comment]
@alexandra-toder that's not how hashes work, and sending passwords over email in general is a bad practice. The original hashed value is only available in the request where the password is first provided, after that the value is hashed and unrecoverable from the hash.

**Comment by daftspunk** [comment]
Thanks @aurelien-roy 

We have added this to our internal list of improvements
