### ISSUE TITLE
Plugin updates pending since 7 months

### ISSUE THREAD

**Issue by aurelien-roy** [rainlab/user-plugin#432]
Versions since 1.5.1 released in september are still pending on the marketplace. Is this intended or an oversight?

<img width="783" alt="" src="https://user-images.githubusercontent.com/1875998/78715190-511ba480-791d-11ea-8652-a45cb497b78c.png">

**Comment by bennothommo** [comment]
@aurelien-roy It's an oversight - I was under the impression they were already out. We'll get that sorted shortly.

**Comment by LukeTowers** [comment]
Pushed.
