### ISSUE TITLE
Activation email can only send if User is logged in

### ISSUE THREAD

**Issue by arustler** [rainlab/user-plugin#433]
If the setting in Backend is set to 'Login requires active account' and the User has _accidentally_ deleted the Activation mail, how can I provide him a new activation link?

I thought I could just let him enter his email and send him a new one but I stumbled across this code line

https://github.com/rainlab/user-plugin/blob/c27f4945e9be556e5fd84bef1c54d2f5a28903d5/components/Account.php#L464-L494

He can't login so I can't use the onSendActivationEmail method
Couldn't it be changed to take a optional parameter user or email?

I thought of something like this in my CMS Page PHP Code section
```
function onSendActivationEmail() {
    $user = UserModel::findByEmail(post('email'));
    if ($user) {
        return $this->account->onSendActivationEmail($user);
    } else {
        throw new ApplicationException('Could not find user'));
    }
}
```

**Comment by LukeTowers** [comment]
@arustler you should be able to activate a user manually from the backend, just click on the user's record and click the "Activate" button.

**Comment by arustler** [comment]
> @arustler you should be able to activate a user manually from the backend, just click on the user's record and click the "Activate" button.

I know of that option and I know that this is a very rare case. I was just thinking it might be more convenient for the user to have the option to resend the activation code by himself instead of waiting for an respond from the admin. Similar to `resetPassword` component.

I don't mind create a PR to implement it?!
After reading the code a little more I couldn't see a reason why this couldn't be optional. The user model is only needed to create the activation code and get the email in order to send the mail.

**Comment by LukeTowers** [comment]
@arustler because then literally anyone could force your application to send out potentially useless activation emails or flood the inbox of a user that hasn't activated yet. Imagine someone signing up with someone else's email address, and then hitting that endpoint repeatedly. Now someone somewhere is receiving a bunch of unsolicited emails that they have no way to stop. 

If you aren't logged in, then you don't get to activate what you claim to be your account yourself without talking to a site admin.

**Comment by arustler** [comment]
> @arustler because then literally anyone could force your application to send out potentially useless activation emails or flood the inbox of a user that hasn't activated yet. Imagine someone signing up with someone else's email address, and then hitting that endpoint repeatedly. Now someone somewhere is receiving a bunch of unsolicited emails that they have no way to stop.
> 
> If you aren't logged in, then you don't get to activate what you claim to be your account yourself without talking to a site admin.

Yes @LukeTowers, I agree with you that this could potentially spam somebody's mailbox but isn't this already theoretically possible with the resetPassword form? 

<details>
  <summary>Code from onRestorePassword</summary>

```
    **
     * Trigger the password reset email
     */
    public function onRestorePassword()
    {
        $rules = [
            'email' => 'required|email|between:6,255'
        ];

        $validation = Validator::make(post(), $rules);
        if ($validation->fails()) {
            throw new ValidationException($validation);
        }

        $user = UserModel::findByEmail(post('email'));
        if (!$user || $user->is_guest) {
            throw new ApplicationException(Lang::get(/*A user was not found with the given credentials.*/'rainlab.user::lang.account.invalid_user'));
        }

        $code = implode('!', [$user->id, $user->getResetPasswordCode()]);

        $link = $this->makeResetUrl($code);

        $data = [
            'name' => $user->name,
            'username' => $user->username,
            'link' => $link,
            'code' => $code
        ];

        Mail::send('rainlab.user::mail.restore', $data, function($message) use ($user) {
            $message->to($user->email, $user->full_name);
        });
    }
```

</details>

**Comment by LukeTowers** [comment]
I suppose it is. You could always just override this on your page code level like you suggested of course.

**Comment by arustler** [comment]
I used now the page override functionality to make it possible for non logged in Users to resend themself a new activation Code. Thanks @LukeTowers for the suggestion

Here is the code for documentation purpose
```
use RainLab\User\Models\User as UserModel;

// Any other code
// Components alias is account in this case

function onSendActivationEmail()
    {
        try {
            $user = UserModel::findByEmail(post('email'));
            if (!$user || $user->is_guest) {
                throw new ApplicationException(Lang::get(/*A user was not found with the given credentials.*/'rainlab.user::lang.account.invalid_user'));
            }
            if ($user->is_activated) {
                throw new ApplicationException(Lang::get(/*Your account is already activated!*/'rainlab.user::lang.account.already_active'));
            }

            Flash::success(Lang::get(/*An activation email has been sent to your email address.*/'rainlab.user::lang.account.activation_email_sent'));

            $code = implode('!', [$user->id, $user->getActivationCode()]);

            $params = [
                $this->account->property('paramCode') => $code
            ];

            if ($pageName = $this->account->property('activationPage')) {
                $url = $this->pageUrl($pageName, $params);
            }
            else {
                $url = $this->currentPageUrl($params);
            }

            if (strpos($url, $code) === false) {
                $url .= '?activate=' . $code;
            }

            $data = [
                'name' => $user->name,
                'link' => $url,
                'code' => $code
            ];

            Mail::send('rainlab.user::mail.activate', $data, function($message) use ($user) {
                $message->to($user->email, $user->name);
            });

        }
        catch (Exception $ex) {
            if (Request::ajax()) throw $ex;
            else Flash::error($ex->getMessage());
        }

        return Redirect::refresh();
    }
```

**Comment by bennothommo** [comment]
In my experience, I've seen a lot of SaaS services offer re-sending the activation email from the user side if they try to log in without activating. I wouldn't mind seeing it implemented in the plugin, with some form of rate limiting (ie. 1 email per 24 hours) to prevent the spam issue @LukeTowers mentioned.

**Comment by LukeTowers** [comment]
Fair enough, I'd agree with @bennothommo
