### ISSUE TITLE
Record finder user widget don't work properly inside a reapeter

### ISSUE THREAD

**Issue by CitrinoDeveloper** [rainlab/user-plugin#435]
Hi to all,

we noticed a bug during testing the record user finder widget (a function for the end user to select an author), when yuo inserti it inside a rainlab.pages {{ variable  }} of a reapeter.

The Case:
We inserted it in our layout page:

`{repeater name="page_authors" label="autori" prompt="add authors" tab="Page" span="storm" cssClass="col-xs-8" placement="secondary"}
{variable name="author" title="Seacrch for author" keyFrom="id" nameFrom="surname" tab="page"  type="recordfinder" group="header" label="research authors" list="~/themes/mytheme/meta/user_columns.yaml" prompt="add authors" searchMode="all" modelClass="RainLab\User\Models\User" searchScope="FilterByGroup" scope="IsActivated" useRelation="false" recordsPerPage="10"}{/variable}
{/repeater}`

We passed record finder parameters directly inside a repeater.

So we have  a secondary tab called page inside a `rainlab page` when userlayout is the the layout for page.

Now 
We have this widget
![record_finder_widget_icon](https://user-images.githubusercontent.com/53047879/81447582-2ff8de80-917d-11ea-862d-ff93eb5fc0d7.png)
![record_finder_widget](https://user-images.githubusercontent.com/53047879/81447862-b01f4400-917d-11ea-8ca8-533043d0ac5b.png)

We can add authors from users ok?

But if we open the widget with hamburger icon on right and use the search
![record_finder_search_error](https://user-images.githubusercontent.com/53047879/81447599-3e46fa80-917d-11ea-9f9d-a187bcf5722f.png)
we encouter this error when using the search

or this error when using the pagination to view the next 10 records
![record_finder_author_list_error](https://user-images.githubusercontent.com/53047879/81447620-47d06280-917d-11ea-8825-eaa9a44536ea.png)

Now i think this is the same bug @bennothommo find in this pull request: https://github.com/octobercms/october/issues/4344

I don't how to fix bug but i think something missing in the `reapeater.php` file or `recordfinder.php`
in this directory: `modules/backend/formwidgets` or something about the use of repaters inside the viewbag of rainlab pages?

Can you check it, please? It could be usefull.

Bye!

**Comment by daftspunk** [comment]
This is a platform issue and should have been fixed a while ago. If you are still encountering this issue, feel free to send us an email

**Comment by super0leg** [comment]
The same problem. Last build
<img width="1363" alt="Снимок экрана 2022-08-19 в 14 03 11" src="https://user-images.githubusercontent.com/10426797/185605188-c8a804b6-61da-4516-95f5-aec2841d1dfd.png">
.
