### ISSUE TITLE
Disable updating last_seen and last_login when impersonating user

### ISSUE THREAD

**Issue by rubenvanerk** [rainlab/user-plugin#442]
I'm trying to disable the updates for the `last_login` and `last_seen` attributes when someone impersonates the user. I succeeded for `last_login` by doing this:
```$model->addDynamicMethod('setLastSeenAttribute', function () use ($model) {});```

Sadly this doesn't work for `last_seen`. I think it's because of this: 
https://github.com/rainlab/user-plugin/blob/master/models/User.php#L440

Is there a reason the update is done this way?  
Is there another way to disable the update of `last_seen` when impersonating?  

Thanks!

**Comment by LukeTowers** [comment]
@rubenvanerk just submit a PR to check if the user is being impersonated, disabling setting those values when the user is impersonated is an acceptable change in behavior that we would be fine with having in the plugin natively.

**Comment by rubenvanerk** [comment]
I took a quick look and found out there's already a check to prevent updating `last_seen` when impersonating here:
https://github.com/rainlab/user-plugin/blob/master/components/Session.php#L113

However, this doesn't work. Probably because of the issue described here: https://github.com/rainlab/user-plugin/issues/298

**Comment by daftspunk** [comment]
This is a platform bug and is fixed in v2.1.5
