### ISSUE TITLE
Users cannot log in after restoring a password

### ISSUE THREAD

**Issue by EndiHariadi43** [rainlab/user-plugin#448]
I'm trying out a case if the user forgets the password. I entered the email address in the password restor field and received an email notification: 
Use this activation code to restore your password:
9!PFR12gX76vE4b4pGLktDIWzWgRjmzM1dQJ0gNn5tP7

After entering the code and changing the password I cannot log in again. Please the solution.

**Comment by bennothommo** [comment]
@EndiHariadi43 Please provide more information - are you receiving any error messages?

**Comment by EndiHariadi43** [comment]
Everything from the user plugin is fine for me, except the password restor section. The flow is like this: 

1. The activation code is received in the user's e-mail, 
2. Then the code must be entered in the confirmation code / activation page and replaces the password with a new one. 
3. The new password has been changed, 
4. And then I go to the login page 
5. Then the user logs in with the new password that was changed earlier in step 2 of this flow. 
6. At this stage the user receives a notification that the password has been entered incorrectly (this is the message [http://prntscr.com/ttcbqx](http://prntscr.com/ttcbqx)). 
7. Now the user cannot log in at all. 

On the password reset page I enter /: code? (http://prntscr.com/ttce33). And this is the settings section on the login page http://prntscr.com/ttcezg. Where are the mistakes I've missed?

**Comment by LukeTowers** [comment]
Please post the full code of the reset password page (from the filesystem, not from the CMS section)

**Comment by EndiHariadi43** [comment]
<div class="col-md-6">
          
        <div class="ml-auto mr-auto offset-md-1 col-md-10">
            <div id="partialUserResetForm">
                {% if __SELF__.code == null %}
                    {% partial __SELF__ ~ '::restore' %}
                {% else %}
                    {% partial __SELF__ ~ '::reset' %}
                {% endif %}
            </div>
          </div>
          
        </div>
