### ISSUE TITLE
Make dates property public on the User Model

### ISSUE THREAD

**Issue by 4nik3t** [rainlab/user-plugin#451]
I am extending the User plugin and I have a field called date_of_birth. I am trying to push the date_of_birth field to the dates property in the user model.
```PHP

User::extend(function ($user) {
    array_push($user->dates, 'date_of_birth'); 
});
```
As the dates property is protected in the model I am getting an error as follows. `"Indirect modification of overloaded property RainLab\User\Models\User::$dates has no effect" `. Could we change this property to public or we have any other option to work around this?

https://github.com/rainlab/user-plugin/blob/1e6623fb6ea94f0587526a3c5c090005a2a8497f/models/User.php#L71

**Comment by mjauvin** [comment]
You can use the public $model->addDateAttribute() method to add dates to this array.

ref. https://github.com/octobercms/library/blob/develop/src/Database/Model.php#L926

**Comment by 4nik3t** [comment]
@mjauvin Thanks for letting me know.
