### ISSUE TITLE
how to get last guest session_id()

### ISSUE THREAD

**Issue by LucasZdv** [rainlab/user-plugin#456]
Hi, I need help.
Rainlab.User on login destroys the previous guest session. I have a session_id which I use to identify Orders from my shopping cart, and then I want to attach the user after login, however this session_id is destroyed when logging in and I can't persist it.

```
public function getGuestId()
    {
        if (!Session::has('guest_id')) {
            $guest_id = str_shuffle(time().bin2hex(random_bytes(32)));
            Session::put('guest_id', $guest_id);
        }

        return Session::get('guest_id');
    }
```
Before logging in, I have an id, for example: fff22916b27b137f45272f117b710760319882694f9dc1d4a93674267542d1df61dbc3535a

logging in destroys the previous session and obtaining a different id, for example:
8104252d7357f781dd6f61394e2b564ac02153469101e5c8999e3d830227db7d942a98661c

How can I persist the session from guest to login.

**Comment by SaifurRahmanMohsin** [comment]
There should be a beforeLogin event that gets fired when user signin occurs. Listen to it, and use session flash to create a temp old_session field. Then listen to the after login event and inside that code block check for the existence of an old_session flash data. If so, then find the cart with session_id equals old session and update it with the current one.

**Comment by LucasZdv** [comment]
I have solved it by cutting off the old session_id in beforeAuthenticate.
