### ISSUE TITLE
InvalidArgumentException: View [welcome] not found

### ISSUE THREAD

**Issue by XIOLog** [rainlab/user-plugin#457]
Hi.

Can't figure it out on my own. Please, help.

After user registration the "welcome" template is not sent to user's mail.

Receiving errors:

`Error with RainLab\Notify\NotifyRules\SendMailTemplateAction`
and
`InvalidArgumentException: View [welcome] not found. in D:\Sites\xxx\laravel\framework\src\Illuminate\View\FileViewFinder.php:137`

I use Valet.

What can be the problem?

**Comment by XIOLog** [comment]
I just needed to select a template in the Notifications.By default, the template is "rainlab.user::welcome" instead of "rainlab.user::mail.welcome".  I don't know if it is a bug or not.

**Comment by LukeTowers** [comment]
@XIOLog could you submit a PR to fix that?

**Comment by XIOLog** [comment]
To the develop branch?
