### ISSUE TITLE
Events fired multiple times when extending model?

### ISSUE THREAD

**Issue by snipiba** [rainlab/user-plugin#463]
Hi Guys,

i faced some issues with getting some events fired multiple times. When i tried to listen on rainlab.user.register / or activate and included only Log::info to check how many times is fired, i got 3x times of register and 3x times of activate.

Questionable is locating event listeners under Behaviours or Plugin boot()...
But when is located under behaviours constructor, it may cause that issue.
---

when moved event::listen to plugin boot, looks everything ok.

---

Question is, if using event::listen on constructor in behaviours that extending user model with implementations, etc. is ok, when its called multiple times in one lifecycle.

**Comment by LukeTowers** [comment]
@snipiba sounds like you're not having a problem with the event being fired multiple times but with your listener being attached multiple times.

**Comment by snipiba** [comment]
> @snipiba sounds like you're not having a problem with the event being fired multiple times but with your listener being attached multiple times.

yup, you're right...
