### ISSUE TITLE
How to upload an User avatar pic from a route API ?

### ISSUE THREAD

**Issue by Incremental92** [rainlab/user-plugin#467]
Hi, I'm using October and developping a frontend app in Vue.js (Quasar framework) with JWT Auth.
From my app, could you please put me on the way to set an avatar picture for an existing user ?
I have an axios request to a plugin API with the following code in my route.php

    $user = User::findByEmail( $user_email );
    // change user profile infos...
    $user->save();
     
    $file = new System\Models\File;
    $file->data = Input::file( $request->avatar_pic );
    $file->is_public = false;
    $file->save();
     
    $user->avatar()->add($file);

Is it the right way ?
Thanks

**Comment by bennothommo** [comment]
@Incremental92 looks fine to me - does this work?

**Comment by Incremental92** [comment]
Thanks, I'll tell you later, because I'm stuck with bugs in JWT and CORS plugin.
There's one bug reported to October by the author...

**Comment by pavelmoshik** [comment]
> @Incremental92 looks fine to me - does this work?

Hi... Hello.  I can not apply the css style to the log and password fields in the login form .. They are ignored, and the standard browser style is set .. Tell me, please, how can I change (apply) the css style for the login form?

**Comment by bennothommo** [comment]
@pavelmoshik Please don't spam other issues with your issue. You've already added an issue asking your question.

**Comment by pavelmoshik** [comment]
> @pavelmoshik Please don't spam other issues with your issue. You've already added an issue asking your question.

i'm confused :( sorry

**Comment by Incremental92** [comment]
Well it doesn't work, with :

     $file->is_public = false;            or true
I get October error :
   
    The file "C:\Dev\WinNMP\WWW\Oct_Test\storage\app/uploads/public//" does not exist
    C:\Dev\WinNMP\WWW\Oct_Test\vendor\symfony\http-foundation\File\File.php line 36

**Comment by Incremental92** [comment]
Just a precision, I uploaded the file in my frontend app and send a blob with axios.
Could it be the way to retrieve the file in October ?

**Comment by Incremental92** [comment]
Well, it was as simple as :
    $user->avatar = Input::file('avatar');
    $user->save();

But why avatars are by default in public folders ? They should be protected !
But I don't know how to do with the previous code ?

**Comment by LukeTowers** [comment]
@Incremental92 because protected files are only viewable in the backend and RainLab.User is for frontend users, so there's no point.
