### ISSUE TITLE
Help! Apply Login form style)

### ISSUE THREAD

**Issue by pavelmoshik** [rainlab/user-plugin#469]
Hello.  I can not apply the css style to the login and password fields in the login form .. They are ignored, and the standard browser style is set .. Tell me, please, how can I change (apply) the css style for the login form? Thanks

**Comment by daftspunk** [comment]
You should fork the component markup. To do this, add the component to your page and then right click on the `{% component %}` tag and select **Expand Component Markup**.

Hope this helps!
