### ISSUE TITLE
Admin activation (multi language)

### ISSUE THREAD

**Issue by yulisweet** [rainlab/user-plugin#471]
I have a admin activation, but email activation needs to send with a selected language. How can I choose into two email templates. How can I extend the plugin in backend ?

**Comment by LukeTowers** [comment]
@mjauvin?

**Comment by yulisweet** [comment]
I activate frontend users manually but I have two frontend languages (EN/FR). 

When user create an account, mail confirmation is sending in French, if user chose FR and English if user chose EN. But, when I active a user on backend the email is in EN (default language).

I need to save selected language to send the good email template for notifications.

I have Mail Templates Translations plugin.

I was thinking of creating two users groups (EN/FR) ... not sure about it !

**Comment by mjauvin** [comment]
@yulisweet can you elaborate on that `Mail Templates Translations plugin` ?

**Comment by yulisweet** [comment]
> @yulisweet can you elaborate on that `Mail Templates Translations plugin` ?

No, I can't !
The problem is in backend. I thought to do a single frontend page, listing users and make the activation in frontend.

All templates are done on Mail Templates Translations. I have a custom field to save selected language...

**Comment by mjauvin** [comment]
I am not following you.

**Comment by yulisweet** [comment]
> @yulisweet can you elaborate on that `Mail Templates Translations plugin` ?

I don't have any configuration on Templates translations.  Do you mean to extend the plugin ?
