### ISSUE TITLE
Account component - missing property 'activationPage'

### ISSUE THREAD

**Issue by cjkpl** [rainlab/user-plugin#472]
In the Account component code, there is a working reference to a property 'activationPage' - yet there is no such property.

Can you consider fixing by adding a new property:
```php
            'activationPage' => [
                'title'       => /*Redirect to during mailb-ased activation */'Activation Page',
                'description' => /*Page name to redirect to after activation.*/'Select a page name that has  Account component',
                'type'        => 'dropdown',
                'default'     => ''
            ],
```
... and a respective function to set it's values? The simplest implementation of that function (without checking if the page has 'Account' component can be e.g.:
```php
    public function getActivationPageOptions()
    {
        return [''=>'- refresh page -', '0' => '- no redirect -'] + Page::sortBy('baseFileName')->lists('baseFileName', 'baseFileName');
    }
```

Lack of this property makes using the component a bit painful, please consider introducing this missing element.

I think that @Artful-dodger may have had this in mind when he reported his issue #452 [here](https://github.com/rainlab/user-plugin/issues/452)

**Comment by bennothommo** [comment]
@cjkpl Please provide a PR with your intended implementation.

**Comment by cjkpl** [comment]
@bennothommo Sure, will do - please allow a couple of days for it
