### ISSUE TITLE
GDPR : why avatar image is public and not protected ?

### ISSUE THREAD

**Issue by Incremental92** [rainlab/user-plugin#473]
Hello, attached avatar image is stored in public storage.
To be GDPR compliant, could it be stored in protected directory ?
When storing a blob image with :
`$user->avatar = Input::file('avatar');`
I can't change attribute `is_public`. Thanks

**Comment by LukeTowers** [comment]
The RainLab.User plugin is for frontend users, and protected files are locked to being viewed by backend users only. Thus this request makes no sense, and saying that it would need to be protected files "for GDPR compliance" also makes no sense.

**Comment by Incremental92** [comment]
Luke I missed that protected files can only being viewed by backend users.
But when I connect to /storage/app/uploads/public/ I can browse all avatars

**Comment by LukeTowers** [comment]
@Incremental92 that's the fault of your server configuration then, you shouldn't be allowing automatic directory listings.

**Comment by Incremental92** [comment]
You're right. I'm developing on local and the Nginx default conf was set to `autoindex on;`
Thanks, you can delete or close this post.
