### ISSUE TITLE
Experiencing Error: Base table or view not found. Possible issue with User plugin throttle table not setting properly?

### ISSUE THREAD

**Issue by resdd** [rainlab/user-plugin#482]
I'm running October build 471 with the RainLab User plugin v1.5.4 on an AWS instance (PHP v7.4.13 and MySQL v8.0.23-0ubuntu0.20.04.1).

The User plugin installed fine but after I create a user account I get the following Exception error when I attempt to access the Users page in the backend:

    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scg_webapp.throttle' doesn't exist (SQL: select * from `throttle` where `user_id` = 1 limit 1)

From stepping through the stack trace displayed with that error, it seems that the source of the problem is that the table defined in line 10 of rainlab/user/models/Throttle.php isn't overriding the default table set in /vendor/october/rain/src/Auth/Models/Throttle.php though I'm not sure why that wouldn't be working.

Any suggestions on how to approach this would be most appreciated.

**Comment by daftspunk** [comment]
I can't say that we've ever seen this issue before. Seems unusual and would need further investigation

The table property should override in the base class, this is how PHP class extension works. Do you have any other plugins installed? Is it a fresh installation?

**Comment by resdd** [comment]
Hi, thanks for your response. I've been meaning to reply for some time and have been sidetracked by several things.

After you asked about other plugins being installed, I went through and disabled the other plugins one by one. Turns out the custom plugin I'm working on is the source of the issue. Sorry for the false alarm, looks like this is something I caused and will be able to fix myself.

**Comment by daftspunk** [comment]
No problem, thanks for following up!
