### ISSUE TITLE
E-mail verification prompts garbled codes when resetting the password

### ISSUE THREAD

**Issue by FujiangSun** [rainlab/user-plugin#483]
When I use rainlab plug-in resetpassword components, when I submit directly without filling in my email address, a garbled verification error pop-up window pops up on the page.

I dont't know how to fix this bug

return fields X_OCTOBER_ERROR_MESSAGE: emailは、必ず指定してください。
the file rainlab/user/components/ressetpassword/restore.htm content  is 

`<script src="//cdn.bootcss.com/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript">
$(function(){
	setTimeout(function(){$("#userRestoreEmail").val("");},100);
})	
</script>
<p class="lead">
    パスワードをお忘れの場合
</p>
<p>登録いただいたメールアドレスを入力し、パスワード変更ページのURLをメールで送信いたします。</p>

<form
    data-request="{{ __SELF__ }}::onRestorePassword"
    data-request-update="'{{ __SELF__ }}::reset': '#partialUserResetForm'"
    data-request-validate
    data-request-flash
    >
    <div class="form-group">
        <label for="userRestoreEmail" style="font-size:15px;">メールアドレス</label>
        <input name="email" type="email" class="form-control" id="userRestoreEmail" placeholder="メールアドレスをご入力下さい">
         <span data-validate-for="email"></span>
    </div>

    <button type="submit" class="btn btn-default">パスワードを再設定</button>

  <div class="alert alert-danger" data-validate-error>
        <p data-message></p>
    </div>
</form>
`

![0F2609D6-962B-4de0-A3EC-12173F863084](https://user-images.githubusercontent.com/42992581/118425398-b7b3ea00-b6fb-11eb-8849-c34a152fcdd0.png)
![C0C2F0BC-D09E-4ace-B8CA-B0ECA5A57407](https://user-images.githubusercontent.com/42992581/118425425-c6020600-b6fb-11eb-9c9b-79155e45f5fa.png)

![0F2609D6-962B-4de0-A3EC-12173F863084](https://user-images.githubusercontent.com/42992581/118425834-98698c80-b6fc-11eb-9fdf-9756cb3ee93d.jpg)
![C0C2F0BC-D09E-4ace-B8CA-B0ECA5A57407](https://user-images.githubusercontent.com/42992581/118425836-999ab980-b6fc-11eb-9c9d-70860382d920.jpg)
![E2D12F8C-8DEC-44c9-B7CB-DFF9B613127A](https://user-images.githubusercontent.com/42992581/118425839-9acbe680-b6fc-11eb-8a7a-73782f5d1cc3.jpg)

**Comment by daftspunk** [comment]
It looks like there is some interaction happening somewhere in your code that is preventing the validation error from triggering. Instead, the validation error appears to be getting converted to a JSON response as a traditional error.

Since this is an issue with your implementation, we can provide technical support via this service: https://octobercms.com/premium-support

Thanks!
