### ISSUE TITLE
User component not perform login or registration

### ISSUE THREAD

**Issue by raloeasy** [rainlab/user-plugin#484]
I have the 1.5.4 Plugin installed on my October Site ( 2.0.11 October version), i have an issue when try to login or to register a new user from component Account. In both case the component redirect me to login page without display any error. If i impersonate user the session works fine. I have noticed that the plugin doesn't call the ajax function onSignin. The other plugins work fine with Ajax. 

Thanks
Romano

**Comment by raloeasy** [comment]
Solved, i forgot to import Ajax in login page.

**Comment by daftspunk** [comment]
Glad you got it solved!

For anyone finding this, this was likely caused by a known [lifecycle limitation when using partials](https://octobercms.com/docs/cms/partials#life-cycle-limitations)
