### ISSUE TITLE
Translation of validation messages in the frontend

### ISSUE THREAD

**Issue by osvaldo3r** [rainlab/user-plugin#485]
Hello,

It would be interesting to have the possibility to override the validation messages at the frontend level.

I suggest this change in the controller Account (onRegister): 

    $messages = (new UserModel)->customMessages;
    
    $validation = Validator::make($data, $rules, $messages);
    if ($validation->fails()) {
        throw new ValidationException($validation);
    }

With this change it would be possible to do something like this:

    public function boot()
    {
        UserModel::extend(function ($model){
            $model->customMessages = Lang::get('acme.myplugin::validation');
        });
    }
	
Thank you!

**Comment by daftspunk** [comment]
LGTM. Done in 8cf71759744b608bc4d78e8f774dda9e223e5455
