### ISSUE TITLE
Issue with HashManager and the config

### ISSUE THREAD

**Issue by flyingbaba** [rainlab/user-plugin#491]
After installation plugin seems to be working but I'm not able to create a new user. Backend or Frontend throwing the same error: 

"Undefined property: Illuminate\Hashing\HashManager::$config" on line 95 of C:\xampp\apps\xxxx\yyyyy\vendor\laravel\framework\src\Illuminate\Hashing\HashManager.php

October v2, Plugins were installed from project. 

Any thoughts ?

**Comment by flyingbaba** [comment]
Found the issue with different plugin and the third party Laravel package gloudemans/shoppingcart. I'm still in development of one small private plugin and I've tried to install gloudemans/shoppingcart from the root folder of the project, it has these issues: 

 Problem 1
    - Root composer.json requires gloudemans/shoppingcart ^2.6 -> satisfiable by gloudemans/shoppingcart[2.6.0].
    - gloudemans/shoppingcart 2.6.0 requires illuminate/support 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.*|| 5.6.* || 5.7.* -> found illuminate/support[v5.1.1, ..., 5.7.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by daftspunk** [comment]
Hey @flyingbaba,

Indeed October v2 uses Laravel 6 and this is likely why the package won't install or has introduced an incompatible interface. You may need to contact this package author to ask if they are planning on supporting newer Laravel versions.

I hope this helps!
