### ISSUE TITLE
Add property for resetPage

### ISSUE THREAD

**Issue by PubliAlex** [rainlab/user-plugin#492]
Hello,

I noticed that the makeResetUrl of the ResetPassword component look for a "resetPage" property before building the URL that will be sent to the email button.

As I separated the reset and restore function in 2 separates pages, I could define that "resetPage" property in an onInit() method in the php code Tab of my reset page.

But it would be even more convenient to have it available as component property, I wonder why you didn't define it in the defineProperty method, it would be a nice improvement.

Best regards,

**Comment by daftspunk** [comment]
Hi @PubliAlex

This must have been an oversight. We've added the `resetPage` property to the component in v1.6.1 of this plugin.

Thanks!

**Comment by PubliAlex** [comment]
Hello @daftspunk 

Ah nice, that was fast, thank you !
