### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by codeskullz** [rainlab/user-plugin#500]
Dear developers,

I try to use the logout function (button) but when I implement it it doesn't work unfortunately.
Do i miss something?
----
Octobercms version 2.2.34
User plugin version 1.6.2

**Comment by daftspunk** [comment]
Hi @codeskullz 

It should work. Can you share more details?

**Comment by codeskullz** [comment]
first i placed the session component in the account page.
Then i placed: `<a data-request="onLogout" data-request-data="redirect: '/good-bye'">Sign out</a>` n a partial and placed the partial in my account page.

In my template is set:
```
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{{ 'assets/js/manifest.js'|theme }}"></script>
        <script type="text/javascript" src="{{ 'assets/js/vendor.js'|theme }}"></script>
        <script type="text/javascript" src="{{ 'assets/js/app.js'|theme }}"></script>
```


What do you need more from me?

**Comment by daftspunk** [comment]
Looks fine.

Any errors?

**Comment by codeskullz** [comment]
@daftspunk 
Not that I can find it, if you want I have a login for you so you could take a look.

**Comment by daftspunk** [comment]
No problem. Here is a link to contact us: https://octobercms.com/contact
