### ISSUE TITLE
The website URL isn't prepended in the password reset mail

### ISSUE THREAD

**Issue by johrclaessens** [rainlab/user-plugin#502]
It's looks like the website URL isn't prepended in the password reset anymore.
When receiving an mail, the link only contains a string like `?reset=2!XeZ6LKPi4p7KxnN1HCC9HSXXGpLYlglSC35Y6iaT1d`, but without a domain name like `domain.com/`.

- OctoberCMS version:  3.1.20
- User Plugin version: 1.6.3
- The `APP_URL` is set in the .env file

**Comment by daftspunk** [comment]
Hello @johrclaessens 

May I confirm that you have enabled the `system.relative_links` setting found in **config/system.php**?

**Comment by johrclaessens** [comment]
Hey @daftspunk,

The `system.relative_links` setting is set to `false` in the current project.

**Comment by daftspunk** [comment]
Hi @johrclaessens 

You may have a non-existent page defined in the `resetPage` property of the `resetPassword` component. Check this value points to an existing page.

We've added some logic to fallback to the current page when this happens: aee7c0f8dd7b497dac921a20d4c5051d0a0871aa

The original advice should still fix the problem. I hope this helps.
