### ISSUE TITLE
Feature request: Redirect setting

### ISSUE THREAD

**Issue by NielsvandenDries** [rainlab/user-plugin#504]
Hi Team,

Wouldn't it be great if you could set in the user group to which page the person who logged in is routed
;-)

**Comment by daftspunk** [comment]
Hi @NielsvandenDries 

I have added this feature to the internal tracker.

As a workaround, this is possible by using a CMS component that checks the user group and redirects them. You could attach this component to the login screen or even on the page shown after the user signs in.

- Login → Redirector Page (Place component here) → Final Location

I hope this helps.
