### ISSUE TITLE
Add "Confirm password on register" to Account component

### ISSUE THREAD

**Issue by LordRazen** [rainlab/user-plugin#516]
I wonder why The Rainlab Users only have to type the password once on registration. 
So I suggest to add the feature "Confirm password on register" to the Rainlab User Account Component:

![grafik](https://github.com/rainlab/user-plugin/assets/9381368/82083c64-9afa-4b02-84f8-be96377765eb)

**Reasons:** 
- It's common to ask the user to repeat the password for registration. In case he makes a typo, he has to reset his password before he could even login the first time. This way that problem can be avoided. 
- Consistency: If you should confirm the password on a password change it should also be confirmed on registration. 

**Addition:** 
I just recognized the password restore form also just have one field. I recommend to adjust it here, too.

**Comment by daftspunk** [comment]
Hi @LordRazen 

Be sure to check the code. The password confirmation is optional and occurs if the input is found on the page:

https://github.com/rainlab/user-plugin/blob/master/components/Account.php#L307-L309

We could include similar logic in the password reset form.

**Comment by LordRazen** [comment]
Wait what :D 

I can do this here in a copy of the register.htm partial in my theme and the Account component checks the confirmation? :D (rethoric question, I checked it, it worked)

´´´
            <input name="password" type="password" placeholder="Choose a password" />
            <input name="password_confirmation" type="password" placeholder="Repeat password" />
```

This should definitly be documented in the Rainlab doku as an own point. I'm quite sure many people would like to use this feature and if it's in the doku, we all dont have to search the Account component. 

Since I dont modify the authentification / didnt play around with the Auth Facade, I overlooked that you mentioned the password_confirmation there.

**Comment by LordRazen** [comment]
...but it looks like this does not work on the ResetPassword Form. 

Neither in the partial nor in the component I found anything about password confirmation - and it should definitly be here, too, right?

**Comment by mkinternet** [comment]
Why don't you just add this field in the account component? This is "must have" field in registration form.
