### ISSUE TITLE
TransportException not catched

### ISSUE THREAD

**Issue by LordRazen** [rainlab/user-plugin#522]
In case the SMTP connection is not configured correctly or somehow the email server is not reacheable, a TransportException is thrown which is not caught. 

Here's a solution for an fix:

**Account.php, onRegister(), around line 350:**
```
            Event::fire('rainlab.user.register', [$user, $data]);

            // Activation is by the user, send the email
            if ($userActivation) {
                // THIS IS THE NEW CODE
                try {
                    $this->sendActivationEmail($user);

                    Flash::success(Lang::get('rainlab.user::lang.account.activation_email_sent'));
                } catch (TransportException) {
                    Flash::error('Your account was created but for some reasons, the activation email could not be send. Please contact an administrator!');
                }
            }
```

The sendActivationEmail() function is called multiple times, so this have to be fixed a few times.

**Comment by daftspunk** [comment]
Try adding this config to your cms.php config file

```
    /*
    |--------------------------------------------------------------------------
    | V1 Exception Policy
    |--------------------------------------------------------------------------
    |
    | When debug mode is off, throwing exceptions in AJAX will display a generic
    | message, except for specific exception types such as ApplicationException
    | and ValidationException (allow-list). Instead, you may use V1, which is
    | a more relaxed policy that allows all messages and blocks common exception
    | types (block-list) but may still leak information in rare cases.
    |
    */

    'exception_policy_v1' => env('CMS_EXCEPTION_POLICY_V1', false),
```

When debug mode is off, it will change the error to a generic one `We're sorry, but something went wrong and the page cannot be displayed.`.

The proposed code would suppress the error in the error logs which is useful to see when the mailer is failing.

**Comment by daftspunk** [comment]
BTW - If you want to modify this behavior, you can add an AJAX handler to your page like this

```
public function onRegister()
{
   // custom code here
    $this->account->onRegister();
   // custom code here
}
```

**Comment by LordRazen** [comment]
Hm, but isnt that exactly the problem?

If I'm a user, I dont wanna see such an Page Error. It shows me an obviously unhandled error and would repeat my action. But that's where the problem comes in: 

The Rainlab user was created, but the visitor does not know about that. So he'll try to recreate the account and get the info that it already exists. 

So wouldnt it be better to combine this? Add it to the log AND send a reasonable message to the visitor?

This here would send the code to the log AND send a reasonable message to the user, so a combination of both ideas:
```
            if ($userActivation) {
                // THIS IS THE NEW CODE
                try {
                    $this->sendActivationEmail($user);

                    Flash::success(Lang::get('rainlab.user::lang.account.activation_email_sent'));
                } catch (TransportException $e) {
                    trace_log($e->getTraceAsString());
                    Flash::error('Your account was created but for some reasons, the activation email could not be send. Please contact an administrator!');
                }
            }
```

**Comment by daftspunk** [comment]
In the bigger picture, sending mail should always succeed. It would be considered a critical system error. This is why `fallback` drivers are in the mail.php config file. Optimally, this message should be queued and re-attempts made if it fails. Queued mail should never block the user; likewise, if the queue fails, this is also a critical system error.

So, for context and this particular issue, I suggest making it configurable to queue mail in the user plugin.
