### ISSUE TITLE
Add an event for password reset

### ISSUE THREAD

**Issue by chocolata** [rainlab/user-plugin#524]
Hi, 

Could I kindly request to have a password reset event?

I'd like to be able to follow-up on when a user resets their password. After the reset would be great.

In my specific use-case I need to make changes to a specific connected model after the user resets their password.
I've reviewed the source code of the user plugin, but I don't think it's present yet.

I guess we would need to add 

`\Event::fire('rainlab.user.activate', [$user]);`

at the end of the onResetPassword() method inside the ResetPassword.php component.

Do you see any problems with this?

Thanks in advance and regards.

**Comment by daftspunk** [comment]
One way to approach this is to override the handler using your page's PHP code

```php
function onResetPassword()
{
    $result = $this->resetPassword->onResetPassword();

    // Custom logic here

    return $result;
}
```

I hope this helps, otherwise we can look at including an event.
