### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by plebward** [rainlab/user-plugin#531]
When coming through the reset flow with a token, the confirmation validation fails even if both fields are the same.

Removing the 'confirmed' validation rule from the model itself gets around the issue, and still validates mismatched fields properly.

![Screenshot 2024-05-07 112848](https://github.com/rainlab/user-plugin/assets/106153950/bb7361d8-901d-4270-98e6-5e3537d0496f)

**Comment by daftspunk** [comment]
Fix included in v3.0.3

Thanks!
