### ISSUE TITLE
Register Service Not found

### ISSUE THREAD

**Issue by Thulaa123** [rainlab/user-plugin#536]
There is no Register Service found As Auth::register and SessionGuard doesn't detect the register service
![Screenshot 2024-05-13 at 2 10 13 AM](https://github.com/rainlab/user-plugin/assets/76616997/eca4cc1a-de9f-4632-a97d-e4248f55f731)
Please check this !!!

**Comment by daftspunk** [comment]
Thanks @Thulaa123 

We've added Auth::register in v3.0.4
