### ISSUE TITLE
User token authentication not working?

### ISSUE THREAD

**Issue by jester6san** [rainlab/user-plugin#542]
Maybe I'm doing it wrong, but I can't get the token authentication to work.
I'm using the latest versions of OctoberCMS (3.6.22) and Rainlab.User (3.0.4)
Account creation and login work fine, the only difference is that I had to change the "onSignin" method, as specified in the documentation, to "onLogin" like so:
```
ajaxHandler('onLogin').withVars({
    token: session.token()
})
```

Now, I'm sending the token with axios like this:
```
axios.get('/api/account/user', {
    headers: {
        "Authorization": "Bearer " + store.user.token
    }
}).then(response => {
    console.log(response.data);
});
```

Layout auth.htm:
```
description = "Auth API Layout"
is_priority = 1

[session]
checkToken = 1

[account]
==
{% if session %}
    {% page %}
{% else %}
    {% do response({error: 'Access Denied'}, 403) %}
{% endif %}
```

Page user.htm:
```
url = "/account/user"
layout = "auth"
title = "user"

[account]
==
{% do response({
    token: session.token,
    sessionUser: session.user,
    accountUser: account.user,
    user: user
}) %}
```

And the response I'm getting is:
```
{
    token: ANOTHER TOKEN,
    sessionUser: null,
    accountUser: null,
    user: null
}
```

I tried various settings and combinations, the result is the same. Authentication is not happening.
What am I doing wrong?

**Comment by daftspunk** [comment]
Hey @jester6san 

It looks like this is a bug. We will publish a fix for this today.

**Comment by jester6san** [comment]
That was so fast!
Thank you very much @daftspunk I confirm that it works!
