### ISSUE TITLE
User unable to register

### ISSUE THREAD

**Issue by TrueAlphaAI** [rainlab/user-plugin#546]
Hello,

Since updating to version 3.0 I have been encountering issue after issue with user registration, signin, etc.

Currently I keep running into an issue where it says 'First Name Field Required' whenever I try registering a user.

For forms I've tried both the default component, making a custom html form, and using a ajax form with (onRegister) all of which end up giving the error First Name Field Required or sometimes Access Denied.

Someone please help.

**Comment by daftspunk** [comment]
Hi @TrueAlphaAI 

The attribute names have changed in v3 to be more descriptive.

## Attribute Changes

Old Attribute | New Attribute
------------- | -------------
`name`        | `first_name`
`surname`     | `last_name`


The first name field is also required now, you may need to change the attribute name or set the attribute to a default value.

I hope this helps.

**Comment by TrueAlphaAI** [comment]
> Hi @TrueAlphaAI
> 
> The attribute names have changed in v3 to be more descriptive.
> 
> ## Attribute Changes
> Old Attribute	New Attribute
> `name`	`first_name`
> `surname`	`last_name`
> The first name field is also required now, you may need to change the attribute name or set the attribute to a default value.
> 
> I hope this helps.


Hello daftspunk,

I tried using the default registration component by calling it {% component 'registration' %} but it doesn't work.  It gives the error "First Name Is Required".  I have also tried overriding the component with a custom ajax form and still the same error.

Note: on the page I have the Account and Registration component like in the image below along with the session component on the theme layout.
![image](https://github.com/rainlab/user-plugin/assets/68808415/d3cdd718-859b-446a-980a-595dab5b7505)

Here is a example of the error in action and the code for the form below it.
![image](https://github.com/rainlab/user-plugin/assets/68808415/914d2f6d-f143-4027-946b-a744a8d6fb26)

```
{{ form_ajax('onRegister') }}

<input
type="hidden"
name="redirect"
value="true"
/>
    <!-- Description -->
    <div class="text-center pb-3">
        <h1 class="h2 mb-3">Sign up for a account</h1>
        <h2 class="h5 fw-normal">Enter details below</h2>
    </div>
    <!-- First Name field -->
    <div class="form-floating my-3">
        <input
        name="first_name"
        type="text"
        class="form-control"
        id="inputFirstName"
        placeholder="First name"
        autocomplete="given-name"
        />
        <label for="inputFirstName">First name</label>
    </div>
    <!-- Last Name field -->
    <div class="form-floating my-3">
        <input
        name="last_name"
        type="text"
        class="form-control"
        id="inputLastName"
        placeholder="Last name"
        autocomplete="family-name"
        />
        <label for="inputLastName">Last name</label>
    </div>
    <!-- Email field -->
    <div class="form-floating">
        <input
        name="email"
        type="email"
        class="form-control"
        id="inputEmail"
        placeholder="Email address"
        autocomplete="email"
        />
        <label for="inputEmail">Email address</label>
    </div>
    <!-- Password field -->
    <div class="form-floating my-3">
        <input
        name="password"
        type="password"
        class="form-control"
        id="inputPassword"
        placeholder="Password"
        autocomplete="new-password"
        />
        <label for="inputPassword">Password</label>
    </div>
    <!-- Submit button -->
    <button
    class="btn btn-primary btn-lg w-100 py-2"
    data-attach-loading
    type="submit">
    Register
    </button>
    <!-- Sign in form -->
    <div class="text-center">
        <p class="mt-5 mb-1 text-body-secondary">
        Already have an account? <a href="{{ 'account/login'|page }}">Sign in here</a>
        </p>
    </div>
{{ form_close() }}
```

Please help and thank you in advance,
- Jack

**Comment by TrueAlphaAI** [comment]
Issue solved.

**Comment by daftspunk** [comment]
@TrueAlphaAI 

Thank you for closing the issue after finding the solution. May I ask, what was the solution?
