### ISSUE TITLE
Method RainLab\User\Classes\SessionGuard::retrieveByCredentials does not exist.

### ISSUE THREAD

**Issue by mplodowski** [rainlab/user-plugin#552]
Calling this code:

`Auth::retrieveByCredentials(['email' => 'some@email.tld']);`

throws following error:

Method RainLab\User\Classes\SessionGuard::retrieveByCredentials does not exist.

**Comment by artistro08** [comment]
Got the same thing, had to use `User::where('email', $email)->first()` to get the user.

**Comment by daftspunk** [comment]
Ah, thanks for finding this. Looks like it should be:

```
Auth::getProvider()->retrieveByCredentials(...)
```

Fixed in 4ec0ce527a01c4251242d864f717a7e483054125
