### ISSUE TITLE
Missing Sign in requires activation

### ISSUE THREAD

**Issue by envas** [rainlab/user-plugin#555]
On October 2, we had the option `Sign in requires activation` with three options for activating the new account. However, in version 3, I am missing the Activation tab with options. What's the best way to implement this functionality?

**Comment by daftspunk** [comment]
Hey @envas 

This is mentioned here: https://github.com/rainlab/user-plugin/blob/master/UPGRADE.md#require-activation-is-removed

I hope this helps, let me know if you need help with this.

**Comment by envas** [comment]
OK, it is not as good as the old version (for me), but I accept it. Thank you.

**Comment by daftspunk** [comment]
This feature has been restored in v3.7.0
