### ISSUE TITLE
Some  flash messages not translated

### ISSUE THREAD

**Issue by envas** [rainlab/user-plugin#556]
When I call the logout, `onLogout` fires a Flash message, `You have been successfully logged out!`, which is not translated. How should I correctly translate this message in my page code?

```
<a data-request="onLogout" data-request-data="{ redirect: '/good-bye' }">Sign out</a>
```

**Comment by daftspunk** [comment]
Hey @envas 

Here are some options:

```html
<!-- Standard Messsage -->
<a data-request="onLogout" data-request-data="{ redirect: '/good-bye' }">Sign out</a>

<!-- No Flash Message -->
<a data-request="onLogout" data-request-data="{ redirect: '/good-bye', flash: false }">Sign out</a>'

<!-- Custom Message -->
<a data-request="onLogout" data-request-data="{ redirect: '/good-bye', flash: "You did it!" }">Sign out</a>'
```

Or translate the message in the lang directory: https://github.com/rainlab/user-plugin/commit/22510a1ea149b17a617c390c2e1f9a480a7cce8d

I hope this helps

**Comment by envas** [comment]
OK, it works for me, but with a different post-parameter, `message` instead of `flash`.

```
<a data-request="onLogout" data-request-data="{ redirect: '/good-bye', message: 'You did it!' }">Sign out</a>'
```

**Comment by daftspunk** [comment]
Great, thanks! I have updated the example.
