### ISSUE TITLE
Login error message translation

### ISSUE THREAD

**Issue by envas** [rainlab/user-plugin#557]
Any idea how to translate the login credentials error message? This does not work for me:

```
<form method="post"
    data-request="onLogin"
    data-request-data="{
        redirect: '/some_page',
        message: 'Wrong login ...'
    }"
    ...
```

![CleanShot 2024-08-01 at 10 23 18@2x](https://github.com/user-attachments/assets/3178ede6-4ab9-4e15-a0d0-6d019a61fbd0)

In general, I found the User plugin translation very bad. Many strings are hardcoded. We can translate these messages using the `data-request-data` API, but it does not make the localization much easier.

**Comment by daftspunk** [comment]
Hi @envas 

This string isn't hardcoded, it is currently an untranslated string: https://github.com/rainlab/user-plugin/blob/0f932170b73cb518a3afd1a604cc6b9227d9dbd8/components/authentication/ActionLogin.php#L150

The documentation on translation can be found here: 
https://docs.octobercms.com/3.x/extend/system/localization.html

I have auto translated the key here: https://github.com/rainlab/user-plugin/commit/a7a1985ccdbb10c237e1f4c9cf8001137dcb0101

On prior occasions, the community requested to perform these translations by hand. You are welcome to submit any contributions or adjustments via a pull request and we will merge them promptly.

Thanks

**Comment by envas** [comment]
That's what I tried first, and it did not work for me. Now I see I did not understand how the localization works. I assumed the translation of a plugin works out of the box. Now I see that the translation works only after I copied the file `plugins/rainlab/user/lang/<lang>.php` to my theme `themes/mytheme/lang`. In my opinion, the need to copy files should be highlighted in the documentation (or maybe I overlooked it). Now the texts are translated. Thank you.

**Comment by daftspunk** [comment]
That's the goal: it should work out of the box. Using auto translations again may make this process clearer, perhaps. The theme and app lang directories can work also, since they are additional layers to the translator, but they are more like personalised translation keys.

Let me know if you need more assistance with the translations.
