### ISSUE TITLE
Impersonating a User causes the last_seen field to update

### ISSUE THREAD

**Issue by apinard** [rainlab/user-plugin#560]
Since the release of V3, I've noticed that using `Auth::impersonate($model);`, where `$model` is an instance of RainLab\User\Models\User, now updates the `last_seen` field of that user.

It seems that `!$this->impersonator()` in the RainLab\User\Components\Session class isn't functioning as expected.

  ```
  /**
     * user returns the logged in user
     */
    public function user(): ?User
    {
        $user = Auth::user();
        $test = $this->impersonator();

        if ($user && !$this->impersonator()) {
            $user->touchLastSeen();
        }

        return $user;
    }
```

**Comment by daftspunk** [comment]
Thanks for finding this, @apinard !
