### ISSUE TITLE
Logout logs out of backend too

### ISSUE THREAD

**Issue by dathwa** [rainlab/user-plugin#561]
Hello.
OCMS 3.6.29
Rainlab/User 3.1.3.

Logging out as a frontend user logs me out of backend too.
Is this a bug?
Thanks

**Comment by daftspunk** [comment]
Hey @dathwa

This could be a byproduct of the Laravel auth trashing the entire session. We'll check it out and report back.

**Comment by daftspunk** [comment]
I can't seem to reproduce this. While the following code does run, it shouldn't destroy the backend auth session.

```php
Auth::logout();
Request::session()->invalidate();
Request::session()->regenerateToken();
```

Can you give some step by step instructions how to reproduce this? Ideally using a clean install with the [RainLab.Vanilla theme](https://github.com/rainlab/vanilla-theme).

Thank you

**Comment by dathwa** [comment]
Hi @daftspunk. 
ocms 3.6.30. rainlab/user 3.1.3

Sorry for the delay. 
I've tried this on a fresh install with rainlab/vanilla theme and it's still happening.

**Comment by daftspunk** [comment]
Hey @dathwa 

We tried it too, but it works as expected (backend stays logged in). 

Can you give the step-by-step instructions so we can see it? Also, do you select "Remember Me" when you login to the backend?
