### ISSUE TITLE
cant restrict the user on page by group

### ISSUE THREAD

**Issue by LogendherDev** [rainlab/user-plugin#563]
I am using the latest version of rainlab/user-plugin i cant make a group restriction, on a page

staff group restricted to manager portal page only managers are allowed

i cant find any documentation related to that, previous version has this features not now

if there is a way, kindly update in documentation. and in this issue

**Comment by daftspunk** [comment]
Hi @LogendherDev 

It is mentioned in the upgrade guide here:
- https://github.com/rainlab/user-plugin/blob/master/UPGRADE.md#session-component

**Comment by LogendherDev** [comment]
thanks i got it, but previous versions it is there in components, so that make me, work very easily... Plz consider this feature in component side in upcoming versions.

**Comment by daftspunk** [comment]
This feature has been restored in v3.6.0
