### ISSUE TITLE
Validation message confused language

### ISSUE THREAD

**Issue by chrisvidal** [rainlab/user-plugin#569]
I am usind the new `registration` component and overriding the registration htm markup.
when I am submiting the registration form, with empty fields on purpose, I received a validation error message which contains 2 languages:

it mixes up french and english: `Le champ first name est obligatoire.`

seems rather strange to me, can this be fixed ?

**Comment by apinard** [comment]
there must be a placeholder :name

**Comment by chrisvidal** [comment]
what do you mean ?

**Comment by chrisvidal** [comment]
the site definition is set to use French.
so I am guessing the validation message is getting the message in french for this reason.
but why does it not take the field name in french as well ?

**Comment by daftspunk** [comment]
The value is taken from the attribute name (`first_name`), and Laravel tries to guess its natural language ("first name"). It means the attribute is untranslated.

For now, you can translate it as a key called `validation.attributes.first_name`.

**Comment by chrisvidal** [comment]
I see, tnaks @daftspunk 

where do I set this `validation.attributes.first_name` please ?

**Comment by daftspunk** [comment]
You can place it here:

- **app/lang/en/validation.php**

```php
<?php

return [
    'attributes' => [
        'first_name' => 'First Name'
    ]
];
```

**Comment by chrisvidal** [comment]
dang! that works well !

and when I need to publish my app to production, I need to copy manually this `validation` file I guess ?

**Comment by daftspunk** [comment]
Yes , publish the entire `app` directory when you publish.

Alternatively, you can use `{ "validation.attributes.first_name": "First Name }` in JSON
