### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by ianturner02** [rainlab/user-plugin#57]
Hi there, i tried to update the site just and it came up with a message that the beta version has ended and we need to upgrade the RC version? it also says that the plugins may not yet be compatable, could you advise if yours is please before i upgrade.

Many Thanks

Ian

**Comment by SaifurRahmanMohsin** [comment]
Now that October is in RC, a lot of plugins have moved to RC as well. I recommend you to backup your website and download and install a fresh copy of October from the website. Read this for more info >> http://octobercms.com/beta#fresh-install
