### ISSUE TITLE
Problem with first_name field after the migration to v3.0

### ISSUE THREAD

**Issue by LordRazen** [rainlab/user-plugin#572]
I think I found a bug with the migration from Rainlab Users v2 to v3. 

Within migrate_v3_0_0.php, the plugin adds the first_name field:
`$table->string('first_name')->nullable();`

Afterwards, you're supposed to run the "MigrateV1Command", but within this command, nothing with the "first_name" is happening. 

How if you check the model for the User, those are the validation rules: 
```
    public $rules = [
        'first_name' => ['required', 'string', 'max:255'],
```

This migration leads to empty first_name fields in the database which throw a bug if the model is saved. I guess some kind of migration like "copy username to first_name if first_name is null" might help already.

**Comment by daftspunk** [comment]
The following query should populate the `first_name` attribute:

```php
Db::update("update users set first_name=name, last_name=surname");
```

This code is found in the migrate_v3_0_0 migration. I've checked the clean-up migration, and nothing seems out of place.

All looks good here!
