### ISSUE TITLE
Cannot catch the rainlab.user.beforeAuthenticate event

### ISSUE THREAD

**Issue by LordRazen** [rainlab/user-plugin#573]
I installed October v3.7.5 and Rainlab Users v3.1.3.

I try to modify the functionality with listening to this event, but I just cannot catch it. 

```
Event::listen('rainlab.user.login', function ($user) {
    trace_log("This works");
});
Event::listen('rainlab.user.beforeAuthenticate', function ($component, $credentials) {
    trace_log("This does not work");
});
```

Looking at the ActionLogin.php from Rainlab Users, there's a note about version 3.7 already: 
https://github.com/rainlab/user-plugin/blob/46d0e619dd17c78c215134ff1adfcd255ba1b7e2/components/authentication/ActionLogin.php#L43C1-L55C10

So I replaced it with the suggested line but still I cannot fetch this event. 

Did I missunderstood it and the event is not thrown on every login? I debugged through the Authentification component and it should be thrown. Checking the EventEmitter.php from the system traits, I see that code does not run in local or global event, it uses the last return value there. 

**So, what needs fixing here:** 
- Please Fix the Event so it can actually be fetched again. 
- Looking at this documentation: https://github.com/rainlab/user-plugin/blob/46d0e619dd17c78c215134ff1adfcd255ba1b7e2/docs/events.md
I guess "Before the user is attempting to authenticate using the Account component." should ne about the Authentication component, not the Account component aynmore, right?

**Comment by daftspunk** [comment]
Fixed in de3f81f775728e1b0b413d51581b68bead03e560
