### ISSUE TITLE
Show register or sign in form separately

### ISSUE THREAD

**Issue by nozreh** [rainlab/user-plugin#60]
Hi guys, I'm quite new in Octobercms and starting a new project using the user plugin, after enabling the 'account' component in my page, I can see that it shows both sign in and registration form, is there a way for me to show them separately? like I want to show the registration form in homepage, then show sign in  form in a different page.

**Comment by vojtasvoboda** [comment]
Hold Cmd key (or Ctrl) and double-click on `{% component 'account' %}` (directly to component word). Than you can edit partial templates - keep only login form and move registration form to another template.

**Comment by AlexYoung28** [comment]
I've tried that but don't seem to work

**Comment by vojtasvoboda** [comment]
Check this video at 4:52 - https://www.facebook.com/octobercms/posts/821446651302133

**Comment by LaravelNick** [comment]
I'm experiencing exactly the same problem, with the latest build.

Cannot get rainlab/user/components/account/register.htm to display.

rainlab/user/components/account/default.htm seems to kick in instead.

Could it be a routing issue?

**Comment by daftspunk** [comment]
This is as simple as customising the default markup. See the docs for more info: http://octobercms.com/docs/cms/components#customizing-default-markup
