### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by NeriJunior** [rainlab/user-plugin#62]
Translate the forms without translate plugin.

**Comment by daftspunk** [comment]
???

**Comment by NeriJunior** [comment]
How can I translate the sample forms like the accounts component?
Without using the translate plugin.

**Comment by daftspunk** [comment]
This article should be helpful:
http://octobercms.com/docs/plugin/localization

You can easily customise the front-end markup of any component, this is a feature built-in to October.
