### ISSUE TITLE
problem with sign out link...

### ISSUE THREAD

**Issue by agcamacho** [rainlab/user-plugin#67]
i tried this code for a logout link : <a data-request="onLogout" data-request-data="redirect: '/good-bye'">Sign out</a>

but it's creating a clickable link, it's just text that says, "Sign out"...

i tried : <a href="#" data-request="onLogout" data-request-data="redirect: '/good-bye'">Sign out</a>

this makes the link clickable, but it's not ending the session. any suggestions?

**Comment by metal-software** [comment]
I believe you need to add the OctoberCMS Ajax Framework and extras by adding this:
    {% framework extras %}
with your footer area scripts

**Comment by alvaro-canepa** [comment]
The link for "sign out" must be visible. Doesn't work for hidden items, like sub menu.

**Comment by croesike** [comment]
Doesn't work for me either, the {% framework extra %} is in the page. But I can't figure out how to sign out.

**Comment by GeGeek** [comment]
Thanks @metal-software your solution worked for me :)

**Comment by MaxShvets** [comment]
Try adding [session] to the top of your page

**Comment by lsemple** [comment]
I added [session] to the top of my Layout (default). and then I put this in my Nav Bar

                {{ nav.render_menu(links) }}
                {% if user %}
                    <li class="dropdown">
                        <button
                        
                            data-request="onLogout"
                            class="btn btn-sm navbar-btn btn-primary navbar-right hidden-sm hidden-xs">
                            Log out
                    </li>
                {% else %}
                <li>
                    <button
                        onclick="window.location='{{ 'signin'|page }}'"
                        class="btn btn-sm navbar-btn btn-primary navbar-right hidden-sm hidden-xs">
                        Sign in
                    </button>
                </li>

                {% endif %}
