### ISSUE TITLE
Remove extra fields from DB and backend

### ISSUE THREAD

**Issue by dubcanada** [rainlab/user-plugin#73]
Hello,

This may not be the opinion of everyone. But I don't think it makes sense to automatically create a bunch of extra columns if they are not used all the time.

I think only the main columns.

* id
* name (maybe)
* email
* password
* activation_code
* persist_code
* reset_password_code
* permissions
* is_activated
* activated_at
* last_login
* created_at
* updated_at
* username
* surname (maybe)

Should be created, and maybe not even the first name/last name columns.

The extra columns should be part of something else to adds all the "extra" stuff.

Thoughts?

**Comment by daftspunk** [comment]
We have to be careful not to get too granular. The current columns are not required, in general. If we were to strip them out and move them to separate plugins, we might end up with

RainLab.User
RainLab.UserProfile
RainLab.UserLocations

These plugins by themselves are difficult to justify. Is there a compelling reason why this stuff shouldn't be baked in?

**Comment by dubcanada** [comment]
I agree it's important not to get too granular, but having a bunch of extras when all people really need is username/email and password (such as in my case where I am removing everything but email and password from both the DB and the backend). It just seems like extra work that shouldn't need to be done.

If I want state/country/what ever I should have to add those, or install something that adds those. Rather then install something then have to remove them.

There already is a plugin http://octobercms.com/plugin/indikator-user which does nothing but add a bunch of other fields. I don't see why there couldn't also be a UserProfile plugin that adds back in all the address stuff.

**Comment by daftspunk** [comment]
The original intention was to give standard fields that can be relied upon by other plugins, so we didn't have instances where a column was called: street_addr, street_address, st_addr, address, etc.

I see your point though, locations adds a fair amount of bulk. We could make RainLab.User 2.0 and RainLab.UserExtras or something.

I will leave this open to action.

**Comment by daftspunk** [comment]
This was actioned a while ago as RainLab.User, RainLab.UserPlus and RainLab.Location plugins.
