### ISSUE TITLE
Upgrade problem not show avatar image

### ISSUE THREAD

**Issue by ribsousa** [rainlab/user-plugin#74]
A have a problem, after making system upgrade to the latest october version  build 250, the variable path not return the correct path for the avatar image:

the array content return:

```{"id":"112","disk_name":"553f63dd8fbed291660246.png","file_name":"f1.png","file_size":"1166992","content_type":"image\/png","title":null,"description":null,"field":"avatar","sort_order":"112","created_at":"2015-04-28 10:41:33","updated_at":"2015-04-28 10:41:38","path":"\/storage\/app\/uploads\/public\/553\/f63\/dd8\/553f63dd8fbed291660246.png","extension":"png"}```

The variable path print:   **-1**

**Comment by daftspunk** [comment]
Fixed build 251
