### ISSUE TITLE
Is it possible to login with url ?

### ISSUE THREAD

**Issue by sulazix** [rainlab/user-plugin#83]
Is it possible to login with a request like "https://website.com/october/login?user=toto&password=toto1234" ? or through a JSON request ? I'm building a basic android app in whitch I want my user to be able to register the credential in "settings" and then use them to login automaticaly.

**Comment by LukeTowers** [comment]
You should be able to send a post request to the URL with the required information, just inspect your network request in devtools when you do it over the web and replicate that through whatever APIs are available to you as an android developer.
