### ISSUE TITLE
Frontend auth check ignore backend?

### ISSUE THREAD

**Issue by dubcanada** [rainlab/user-plugin#84]
Hello,

I am wondering if there is a way to ignore the backend users with the auth check? Like I have a bunch of redirects on certain pages depending on if the user is logged in or not. But I don't want them to proc if your a backend user (so they can see the pages, or edit them or what not).

Any thoughts on how to do this? `Auth::check()` seems to be how it is done but I don't see any way to determine if they are backend or not.

**Comment by daftspunk** [comment]
Use `BackendAuth::check()`
