### ISSUE TITLE
Login / Redirect problems

### ISSUE THREAD

**Issue by Jakob96** [rainlab/user-plugin#92]
Hello!

I have set up a partial with the account components (account/session) placed on a page. The account component is configurated to redirect to a protected page. But after I enter the correct username and password the user input is placed in the url (like this, <code>sign-in?login="username"&password="password in uncrypted format(!)"</code>) and nothing more (no redirect or anything). 

How can I fix this?

**Comment by hybridvision** [comment]
Hello,

It sounds like you don't have the October framework JavaScript loaded correctly - make sure that you have `{% framework extras %}` at the bottom of your layout file.

If that is missing or there are some other JS errors, the login form action won't be handled by the framework and you'll see the behaviour you describe. Check your browser console for any errors.

Good luck!
