### ISSUE TITLE
Login attribute  - Username

### ISSUE THREAD

**Issue by voidshah** [rainlab/user-plugin#93]
1. I set the Login attribute to Username
2. Then I try to Register from default registration form and recive the message "The username field is required"
3. I added input field name="username" to register.htm
4. Now my registration form has four input fields: name, username, email, password
5. I set, for example, the username field as "Testuser"
6. But, when I finished registration, the username field contains a value equal to email !!! The value of the username that I entered, not stored in the model !

protected $fillable = [
        'name',
        'surname',
        'login',
        'email',
        'password',
        'password_confirmation',
        'company',
        'phone',
        'street_addr',
        'city',
        'zip',
        'country',
        'state'
    ];
I think it happens because there is no 'username' in the $fillable.
The same issue occurs in onUpdate method.
Adding 'username' to $fillable fixes the issue.

Sorry for my bad english :(

**Comment by tremst** [comment]
i'm having the same issue, if i want to register a user it tells me that the registation requires username option but its not available by default.

Login works like a charm on the other hand.

**Comment by daftspunk** [comment]
This was fixed a while ago, if not, please relog another issue.
