### ISSUE TITLE
Activation Url should be a component setting or activation should be it's own component.

### ISSUE THREAD

**Issue by jayalfredprufrock** [rainlab/user-plugin#97]
I'm trying to put my login/signup forms within a modal, and thus the account component is attached to my main layout to make it available on all pages. This causes issues with the way activations work, since it assumes the activation url is whatever url the registration happened on. This means the email link generated is always wrong. If the activation url was a parameter of the Account component, I could create a separate page for activation and point the component to that. 

Alternatively, activation could be broken out into it's own component since the Account component already performs quite a few functions.

**Comment by bekerov** [comment]
same problem!

**Comment by SaifurRahmanMohsin** [comment]
+1
I just wrote about the same thing in #193

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
