### ISSUE TITLE
How to edit account component?

### ISSUE THREAD

**Issue by allw1994** [rainlab/user-plugin#98]
hi,

trying to edit the account components to add fields, but i cannot track the code back far enough, i have found onupdate(), but then i just hit a wall. do you have documentation that details things like this?

thanks!

**Comment by daftspunk** [comment]
See OB-10 and OB-18 for details on this

http://octobercms.com/support/article/ob-10
http://octobercms.com/support/article/ob-18

You either need to add the fields as "fillable" or roll your own handler.

**Comment by iboved** [comment]
@daftspunk how to "roll your own handler"?

I have [extended](https://octobercms.com/support/article/ob-10) this plugin using my custom Profile model (like in your video). Now, on the frontend, I want to add the ability to change my custom fields from related profiles table. I added relation between User and Profile, it works. But now I need to add my custom logic to update related Profile model when user change its fields. How to extend/override the onUpdate method?

Thanks!

**Comment by daftspunk** [comment]
Hi @iboved, you can extend handlers by defining a higher priority handler. So for example in your page code,

```php
url = "/mypage"
==
// Higher priority local handler
function onUpdate()
{
    // Call the component's handler
    $this->myComponent->onUpdate();
}
==
...
