### ISSUE TITLE
Translating flash messages

### ISSUE THREAD

**Issue by GeGeek** [rainlab/user-plugin#99]
Hi,

i would like to translate flash messages, but actually i can't find the solution.
I tried this code but it doesn't work:

function onSave()
{
    // Sets a successful message
    Flash::success('Settings successfully saved!');

```
// Sets an error message
Flash::error('Error saving settings');

// Sets a warning message
Flash::warning('There was a problem but no worries');

// Sets an informative message
Flash::info('Just a heads up about the settings');
```

}

Even if i change onSve for onUpdate..

Thanks

**Comment by gergo85** [comment]
Use this code:
`Flash::success(Lang::get('rainlab.user::lang.category.string'));`

**Comment by LukeTowers** [comment]
Related: #223
